import type { LucideIcon } from "lucide-react";
import {
  Activity,
  Search,
  FileText,
  Settings,
  Clock,
  AlertTriangle,
  CheckCircle2,
  XCircle,
  Eye,
  TrendingUp,
  TrendingDown,
  Minus,
  RefreshCw,
  Download,
  Upload,
  ShieldCheck,
  Target,
  Zap,
  Brain,
  Sparkles,
  ArrowUpRight,
  ArrowDownRight,
  Minimize2,
  Maximize2,
  Filter,
  X,
  Plus,
  Trash2,
  Edit3,
  Save,
  Undo,
  Redo,
  Copy,
  Share2,
  Printer,
  Mail,
  Bell,
  Bookmark,
  Flag,
  Rocket,
  Lightbulb,
  Wand2,
  Bot,
  Cpu,
  Gauge,
  Ruler,
  Scale,
  TrendingUp as TrendUp,
  TrendingDown as TrendDown,
  Minimize as MinimizeIcon,
  Maximize as MaximizeIcon,
  ZoomIn,
  ZoomOut,
  Move,
  GripVertical,
  GripHorizontal,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  Home,
  Menu,
  Settings2,
  HelpCircle,
  InfoIcon,
  Check,
  AlertTriangle as AlertTriangleIcon,
  Circle,
  Square,
  Triangle,
  Diamond,
  Hexagon,
  Pentagon,
  Octagon,
  Star as StarIcon,
  Circle as CircleIcon,
  Square as SquareIcon,
  Triangle as TriangleIcon,
  Hash,
  Compass,
  Target as TargetIcon,
  ShoppingCart,
  MapPin,
  ShieldCheck as ShieldCheckIcon,
  Image,
  ImageOff,
  Link,
  Link2,
  Unlink,
  Globe,
  Server,
  Database,
  GitBranch,
  Split,
  Merge,
  Columns,
  Copy as CopyIcon,
  Share2 as Share2Icon,
  Printer as PrinterIcon,
  Mail as MailIcon,
  Bell as BellIcon,
  Bookmark as BookmarkIcon,
  Flag as FlagIcon,
  Rocket as RocketIcon,
  Lightbulb as LightbulbIcon,
  Wand2 as Wand2Icon,
  Bot as BotIcon,
  Cpu as CpuIcon,
  Gauge as GaugeIcon,
  Ruler as RulerIcon,
  Scale as ScaleIcon,
} from "lucide-react";

export const API_BASE = import.meta.env.VITE_API_URL || "http://localhost:8000/api/v1";

export const F06_NAV = [
  { label: "Overview", value: "overview", icon: Activity },
  { label: "Pages", value: "pages", icon: FileText },
  { label: "SEO Audit", value: "seo-audit", icon: ShieldCheck },
  { label: "Keywords", value: "keywords", icon: Target },
  { label: "Meta Tags", value: "meta-tags", icon: Edit3 },
  { label: "Headings", value: "headings", icon: Hash },
  { label: "Content", value: "content", icon: FileText },
  { label: "Images", value: "images", icon: Image },
  { label: "Internal Links", value: "internal-links", icon: Link },
  { label: "External Links", value: "external-links", icon: Link2 },
  { label: "Canonical", value: "canonical", icon: Globe },
  { label: "Robots", value: "robots", icon: ShieldCheck },
  { label: "Sitemap", value: "sitemap", icon: Globe },
  { label: "Schema", value: "schema", icon: Database },
  { label: "Answer Readiness", value: "answer-readiness", icon: HelpCircle },
  { label: "AI Recommendations", value: "ai-recommendations", icon: Brain },
  { label: "Bulk Actions", value: "bulk-actions", icon: Zap },
  { label: "History", value: "history", icon: Clock },
  { label: "Logs", value: "logs", icon: AlertTriangle },
  { label: "Settings", value: "settings", icon: Settings2 },
] as const;

export const INTENT_COLORS = {
  informational: "bg-blue-500/10 text-blue-500 border-blue-500/20",
  navigational: "bg-green-500/10 text-green-500 border-green-500/20",
  commercial: "bg-amber-500/10 text-amber-500 border-amber-500/20",
  transactional: "bg-purple-500/10 text-purple-500 border-purple-500/20",
  local: "bg-emerald-500/10 text-emerald-500 border-emerald-500/20",
  branded: "bg-indigo-500/10 text-indigo-500 border-indigo-500/20",
  question: "bg-cyan-500/10 text-cyan-500 border-cyan-500/20",
};

export const STATUS_COLORS = {
  active: "bg-success/10 text-success border-success/20",
  inactive: "bg-muted text-muted-foreground border-border",
  pending: "bg-warning/15 text-warning-foreground border-warning/30",
  error: "bg-destructive/10 text-destructive border-destructive/20",
  scanned: "bg-success/10 text-success border-success/20",
  skipped: "bg-muted text-muted-foreground border-border",
  passed: "bg-success/10 text-success border-success/20",
  failed: "bg-destructive/10 text-destructive border-destructive/20",
  warning: "bg-warning/15 text-warning-foreground border-warning/30",
  critical: "bg-destructive/10 text-destructive border-destructive/20",
  high: "bg-warning/15 text-warning-foreground border-warning/30",
  medium: "bg-muted text-muted-foreground border-border",
  low: "bg-muted text-muted-foreground border-border",
  easy: "bg-success/10 text-success border-success/20",
  moderate: "bg-warning/15 text-warning-foreground border-warning/30",
  hard: "bg-destructive/10 text-destructive border-destructive/20",
  optimal: "bg-success/10 text-success border-success/20",
  underused: "bg-warning/15 text-warning-foreground border-warning/30",
  overused: "bg-destructive/10 text-destructive border-destructive/20",
  missing: "bg-destructive/10 text-destructive border-destructive/20",
  completed: "bg-success/10 text-success border-success/20",
  running: "bg-info/10 text-info border-info/20",
  approved: "bg-success/10 text-success border-success/20",
  rejected: "bg-destructive/10 text-destructive border-destructive/20",
  submitted: "bg-success/10 text-success border-success/20",
  unknown: "bg-muted text-muted-foreground border-border",
  audit: "bg-info/10 text-info border-info/20",
  validation: "bg-info/10 text-info border-info/20",
  processing: "bg-info/10 text-info border-info/20",
};

export const SEVERITY_COLORS = {
  critical: "bg-destructive/10 text-destructive border-destructive/20",
  high: "bg-warning/15 text-warning-foreground border-warning/30",
  medium: "bg-muted text-muted-foreground border-border",
  low: "bg-muted text-muted-foreground border-border",
};

export const DIFFICULTY_COLORS = {
  easy: "bg-success/10 text-success",
  moderate: "bg-warning/15 text-warning-foreground",
  hard: "bg-destructive/10 text-destructive",
};

export const PRIORITY_ORDER = { critical: 0, high: 1, medium: 2, low: 3 } as const;

export const SEO_STATUSES = ["scanned", "error", "pending", "skipped"] as const;

export const SCHEMA_TYPES = [
  "Organization",
  "Website",
  "Article",
  "FAQ",
  "Breadcrumb",
  "Product",
  "Review",
  "Event",
  "Video",
  "LocalBusiness",
  "Person",
  "JobPosting",
  "Course",
  "HowTo",
  "Recipe",
  "SoftwareApplication",
] as const;

export const EXPORT_FORMATS = ["csv", "xlsx", "pdf"] as const;

export const ARROW_UP = ArrowUpRight;
export const ARROW_DOWN = ArrowDownRight;
export const ARROW_FLAT = Minus;