import { createFileRoute } from "@tanstack/react-router";
import { PageHeader } from "@/components/page-header";
import { Button } from "@/components/ui/button";
import { Download, FileText, Mail, Calendar, Plus } from "lucide-react";
import { motion } from "framer-motion";

export const Route = createFileRoute("/_app/reports/")({
  head: () => ({
    meta: [
      { title: "Reports — Nebula" },
      { name: "description", content: "Generate, schedule, and share investor-grade marketing reports — PDF, CSV, or automated email." },
      { property: "og:title", content: "Reports — Nebula" },
      { property: "og:description", content: "Investor-grade marketing reports on demand." },
    ],
  }),
  component: Reports,
});

const reports = [
  { name: "Monthly SEO Executive Summary", type: "PDF", updated: "2h ago" },
  { name: "Core Web Vitals — 90 day", type: "PDF", updated: "Yesterday" },
  { name: "Keyword universe export", type: "CSV", updated: "3d ago" },
  { name: "Competitor movement", type: "PDF", updated: "1w ago" },
];

function Reports() {
  return (
    <div>
      <PageHeader
        eyebrow="Section 10"
        title="Reports"
        description="Board-ready reports. Generated by AI, formatted by design."
        actions={
          <Button className="rounded-xl h-10 gradient-primary text-white border-0 shadow-[var(--shadow-glow)]">
            <Plus className="size-4" /> New report
          </Button>
        }
      />

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
        {[
          { icon: Download, l: "Download PDF", d: "Formatted, branded, one-click" },
          { icon: FileText, l: "Download CSV", d: "Raw data for BI tools" },
          { icon: Mail, l: "Email report", d: "Send to stakeholders" },
          { icon: Calendar, l: "Schedule reports", d: "Weekly · Monthly · Quarterly" },
        ].map((x, i) => (
          <motion.button
            key={x.l}
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: i * 0.05 }}
            className="rounded-2xl border border-border bg-card p-5 text-left card-hover"
          >
            <div className="size-11 rounded-xl gradient-primary grid place-items-center mb-3">
              <x.icon className="size-5 text-white" />
            </div>
            <div className="text-sm font-semibold">{x.l}</div>
            <div className="text-xs text-muted-foreground mt-1">{x.d}</div>
          </motion.button>
        ))}
      </div>

      <div className="rounded-3xl border border-border bg-card overflow-hidden">
        <div className="p-5 border-b border-border text-lg font-semibold">Recent reports</div>
        <table className="w-full text-sm">
          <thead className="bg-muted/40 text-xs uppercase tracking-widest text-muted-foreground">
            <tr>
              <th className="text-left px-5 py-3 font-medium">Name</th>
              <th className="text-left px-5 py-3 font-medium">Type</th>
              <th className="text-left px-5 py-3 font-medium">Updated</th>
              <th className="text-right px-5 py-3 font-medium">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-border">
            {reports.map((r) => (
              <tr key={r.name} className="hover:bg-muted/30 transition">
                <td className="px-5 py-3 font-medium">{r.name}</td>
                <td className="px-5 py-3 text-muted-foreground">{r.type}</td>
                <td className="px-5 py-3 text-muted-foreground">{r.updated}</td>
                <td className="px-5 py-3 text-right">
                  <Button variant="outline" size="sm" className="rounded-lg"><Download className="size-3.5" /> Download</Button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
