import { Link, useRouterState } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { Activity, BookOpen, CheckCircle2, Download, FileText, Filter, History, Plus, Search, ShieldCheck, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
const nav=[["Overview","/search-knowledge"],["Search Architecture","/search-knowledge/google-search-architecture"],["SERP Features","/search-knowledge/serp-features"],["Algorithm Updates","/search-knowledge/google-algorithm-updates"],["Search Operators","/search-knowledge/search-operators"],["Search Intent","/search-knowledge/search-intent"],["Device Behaviour","/search-knowledge/device-behaviour"],["Market Analysis","/search-knowledge/market-analysis"],["Knowledge Rules","/search-knowledge/knowledge-rules"],["Version History","/search-knowledge/version-history"],["Approvals","/search-knowledge/approvals"],["Activity Logs","/search-knowledge/activity-logs"],["Settings","/search-knowledge/settings"]] as const;
export function SearchKnowledgeNav(){const path=useRouterState({select:s=>s.location.pathname});return <div className="mb-6 rounded-2xl border border-border bg-card p-2"><nav className="flex flex-wrap gap-1.5" role="tablist" aria-label="Search Knowledge">{nav.map(([name,to])=><Link key={to} to={to} role="tab" aria-selected={path===to} className={`inline-flex h-10 items-center rounded-xl border px-3.5 text-sm font-medium whitespace-nowrap transition ${path===to?"border-transparent bg-gradient-to-r from-primary/12 to-accent/8 text-foreground":"border-transparent text-muted-foreground hover:border-border/60 hover:bg-muted/40 hover:text-foreground"}`}>{name}</Link>)}</nav></div>}
export function KnowledgeWorkbench({title,description,controls,ai}:{title:string;description:string;controls:string[];ai:string}){const [query,setQuery]=useState("");const items=useMemo(()=>controls.filter(x=>x.toLowerCase().includes(query.toLowerCase())),[controls,query]);return <div><SearchKnowledgeNav/><div className="flex flex-col md:flex-row justify-between gap-4 mb-6"><div><h1 className="text-2xl font-semibold">{title}</h1><p className="mt-1 text-sm text-muted-foreground">{description}</p></div><Button><Plus className="size-4"/>Create record</Button></div><div className="grid grid-cols-2 xl:grid-cols-4 gap-4 mb-6">{[["Knowledge health","92%",ShieldCheck],["Pending reviews","4",History],["Latest version","v2.8",BookOpen],["Recent activity","28",Activity]].map(([l,v,I])=>{const Icon=I as typeof Activity;return <Card key={l as string} className="p-5"><div className="flex justify-between text-[11px] uppercase tracking-wider text-muted-foreground">{l as string}<Icon className="size-4 text-primary"/></div><p className="text-2xl font-semibold mt-2">{v as string}</p></Card>})}</div><div className="grid xl:grid-cols-3 gap-5"><Card className="xl:col-span-2 p-5"><div className="flex flex-wrap justify-between gap-3 mb-4"><div className="relative w-full sm:w-80"><Search className="absolute size-4 top-2.5 left-3 text-muted-foreground"/><Input className="pl-9" value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${title.toLowerCase()}...`}/></div><div className="flex gap-2"><Button size="sm" variant="outline"><Filter className="size-4"/>Filter</Button><Button size="sm" variant="outline"><Download className="size-4"/>Export</Button></div></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="border-y text-left text-[11px] uppercase tracking-wider text-muted-foreground"><tr>{["Name","Category","Owner","Version","Status","Last updated"].map(h=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{items.map((item,i)=><tr className="border-b" key={item}><td className="p-3 font-medium">{item}</td><td className="p-3">{title}</td><td className="p-3">SEO Owner</td><td className="p-3">v2.{i+3}</td><td className="p-3"><Badge variant={i===1?"outline":"secondary"}>{i===1?"Review":"Published"}</Badge></td><td className="p-3 text-muted-foreground">{i+1}h ago</td></tr>)}</tbody></table></div></Card><div className="space-y-5"><Card className="p-5"><div className="flex gap-2 items-center text-sm font-semibold"><Sparkles className="size-4 text-primary"/>AI summary</div><p className="mt-3 text-sm leading-relaxed">{ai}</p></Card><Card className="p-5"><p className="text-sm font-semibold">Governance</p><div className="mt-3 space-y-2 text-xs"><div className="rounded-lg border p-3">Source evidence required</div><div className="rounded-lg border p-3">SEO owner approval</div><div className="rounded-lg border p-3">Versioned and auditable</div></div></Card></div></div></div>}
