/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSearchConsoleRouteImport } from './routes/_app/search-console'
import { Route as AppSearchKnowledgeRouteImport } from './routes/_app/search-knowledge'
import { Route as AppWebsiteFoundationRouteImport } from './routes/_app/website-foundation'
import { Route as AppBusinessProfileIndexRouteImport } from './routes/_app/business-profile/index'
import { Route as AppCompetitorsIndexRouteImport } from './routes/_app/competitors/index'
import { Route as AppGoogleProductsIndexRouteImport } from './routes/_app/google-products/index'
import { Route as AppKeywordsIndexRouteImport } from './routes/_app/keywords/index'
import { Route as AppMobileIndexRouteImport } from './routes/_app/mobile/index'
import { Route as AppPerformanceIndexRouteImport } from './routes/_app/performance/index'
import { Route as AppReportsIndexRouteImport } from './routes/_app/reports/index'
import { Route as AppSearchConsoleIndexRouteImport } from './routes/_app/search-console/index'
import { Route as AppSearchConsoleAmpRouteImport } from './routes/_app/search-console/amp'
import { Route as AppSearchConsoleCountriesRouteImport } from './routes/_app/search-console/countries'
import { Route as AppSearchConsoleCoverageRouteImport } from './routes/_app/search-console/coverage'
import { Route as AppSearchConsoleCwvRouteImport } from './routes/_app/search-console/cwv'
import { Route as AppSearchConsoleDevicesRouteImport } from './routes/_app/search-console/devices'
import { Route as AppSearchConsoleLinksRouteImport } from './routes/_app/search-console/links'
import { Route as AppSearchConsoleManualActionsRouteImport } from './routes/_app/search-console/manual-actions'
import { Route as AppSearchConsoleMobileUsabilityRouteImport } from './routes/_app/search-console/mobile-usability'
import { Route as AppSearchConsolePagesRouteImport } from './routes/_app/search-console/pages'
import { Route as AppSearchConsolePerformanceRouteImport } from './routes/_app/search-console/performance'
import { Route as AppSearchConsolePropertyDetailsRouteImport } from './routes/_app/search-console/property-details'
import { Route as AppSearchConsoleQueriesRouteImport } from './routes/_app/search-console/queries'
import { Route as AppSearchConsoleSitemapsRouteImport } from './routes/_app/search-console/sitemaps'
import { Route as AppSearchConsoleUrlInspectionRouteImport } from './routes/_app/search-console/url-inspection'
import { Route as AppSearchConsoleVerificationRouteImport } from './routes/_app/search-console/verification'
import { Route as AppSearchKnowledgeIndexRouteImport } from './routes/_app/search-knowledge/index'
import { Route as AppSearchKnowledgeActivityLogsRouteImport } from './routes/_app/search-knowledge/activity-logs'
import { Route as AppSearchKnowledgeAiSearchOverviewRouteImport } from './routes/_app/search-knowledge/ai-search-overview'
import { Route as AppSearchKnowledgeApprovalsRouteImport } from './routes/_app/search-knowledge/approvals'
import { Route as AppSearchKnowledgeDeviceBehaviourRouteImport } from './routes/_app/search-knowledge/device-behaviour'
import { Route as AppSearchKnowledgeFeaturedSnippetsRouteImport } from './routes/_app/search-knowledge/featured-snippets'
import { Route as AppSearchKnowledgeFutureTrendsRouteImport } from './routes/_app/search-knowledge/future-trends'
import { Route as AppSearchKnowledgeGoogleAlgorithmUpdatesRouteImport } from './routes/_app/search-knowledge/google-algorithm-updates'
import { Route as AppSearchKnowledgeGoogleRankingFactorsRouteImport } from './routes/_app/search-knowledge/google-ranking-factors'
import { Route as AppSearchKnowledgeGoogleSearchArchitectureRouteImport } from './routes/_app/search-knowledge/google-search-architecture'
import { Route as AppSearchKnowledgeImageSearchRouteImport } from './routes/_app/search-knowledge/image-search'
import { Route as AppSearchKnowledgeKnowledgeGraphRouteImport } from './routes/_app/search-knowledge/knowledge-graph'
import { Route as AppSearchKnowledgeKnowledgeRulesRouteImport } from './routes/_app/search-knowledge/knowledge-rules'
import { Route as AppSearchKnowledgeLocalSearchRouteImport } from './routes/_app/search-knowledge/local-search'
import { Route as AppSearchKnowledgeMarketAnalysisRouteImport } from './routes/_app/search-knowledge/market-analysis'
import { Route as AppSearchKnowledgeNewsSearchRouteImport } from './routes/_app/search-knowledge/news-search'
import { Route as AppSearchKnowledgePeopleAlsoAskRouteImport } from './routes/_app/search-knowledge/people-also-ask'
import { Route as AppSearchKnowledgeRichResultsRouteImport } from './routes/_app/search-knowledge/rich-results'
import { Route as AppSearchKnowledgeSearchIntentRouteImport } from './routes/_app/search-knowledge/search-intent'
import { Route as AppSearchKnowledgeSearchOperatorsRouteImport } from './routes/_app/search-knowledge/search-operators'
import { Route as AppSearchKnowledgeSerpFeaturesRouteImport } from './routes/_app/search-knowledge/serp-features'
import { Route as AppSearchKnowledgeSerpLayoutRouteImport } from './routes/_app/search-knowledge/serp-layout'
import { Route as AppSearchKnowledgeSettingsRouteImport } from './routes/_app/search-knowledge/settings'
import { Route as AppSearchKnowledgeShoppingSearchRouteImport } from './routes/_app/search-knowledge/shopping-search'
import { Route as AppSearchKnowledgeVersionHistoryRouteImport } from './routes/_app/search-knowledge/version-history'
import { Route as AppSearchKnowledgeVideoSearchRouteImport } from './routes/_app/search-knowledge/video-search'
import { Route as AppSearchKnowledgeVoiceSearchRouteImport } from './routes/_app/search-knowledge/voice-search'
import { Route as AppSeoAnalyzerIndexRouteImport } from './routes/_app/seo-analyzer/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppTrackingIndexRouteImport } from './routes/_app/tracking/index'
import { Route as AppTrackingActivityLogsRouteImport } from './routes/_app/tracking/activity-logs'
import { Route as AppTrackingApprovalsRouteImport } from './routes/_app/tracking/approvals'
import { Route as AppTrackingBusinessGoalsRouteImport } from './routes/_app/tracking/business-goals'
import { Route as AppTrackingConfigurationRouteImport } from './routes/_app/tracking/configuration'
import { Route as AppTrackingConsentRouteImport } from './routes/_app/tracking/consent'
import { Route as AppTrackingContactFormsRouteImport } from './routes/_app/tracking/contact-forms'
import { Route as AppTrackingConversionStrategyRouteImport } from './routes/_app/tracking/conversion-strategy'
import { Route as AppTrackingEventsRouteImport } from './routes/_app/tracking/events'
import { Route as AppTrackingKpiManagementRouteImport } from './routes/_app/tracking/kpi-management'
import { Route as AppTrackingMeasurementPlanRouteImport } from './routes/_app/tracking/measurement-plan'
import { Route as AppTrackingOperationsRouteImport } from './routes/_app/tracking/operations'
import { Route as AppTrackingRoutingRouteImport } from './routes/_app/tracking/routing'
import { Route as AppTrackingSettingsRouteImport } from './routes/_app/tracking/settings'
import { Route as AppTrackingSpamProtectionRouteImport } from './routes/_app/tracking/spam-protection'
import { Route as AppTrackingTestingRouteImport } from './routes/_app/tracking/testing'
import { Route as AppWebsiteFoundationIndexRouteImport } from './routes/_app/website-foundation/index'
import { Route as AppWebsiteFoundationApprovalsRouteImport } from './routes/_app/website-foundation/approvals'
import { Route as AppWebsiteFoundationAuditRouteImport } from './routes/_app/website-foundation/audit'
import { Route as AppWebsiteFoundationAutomationRouteImport } from './routes/_app/website-foundation/automation'
import { Route as AppWebsiteFoundationBacklogRouteImport } from './routes/_app/website-foundation/backlog'
import { Route as AppWebsiteFoundationBrandRouteImport } from './routes/_app/website-foundation/brand'
import { Route as AppWebsiteFoundationDeploymentsRouteImport } from './routes/_app/website-foundation/deployments'
import { Route as AppWebsiteFoundationFormsRouteImport } from './routes/_app/website-foundation/forms'
import { Route as AppWebsiteFoundationInventoryRouteImport } from './routes/_app/website-foundation/inventory'
import { Route as AppWebsiteFoundationLogsRouteImport } from './routes/_app/website-foundation/logs'
import { Route as AppWebsiteFoundationOverviewRouteImport } from './routes/_app/website-foundation/overview'
import { Route as AppWebsiteFoundationPerformanceRouteImport } from './routes/_app/website-foundation/performance'
import { Route as AppWebsiteFoundationPluginsRouteImport } from './routes/_app/website-foundation/plugins'
import { Route as AppWebsiteFoundationResponsiveRouteImport } from './routes/_app/website-foundation/responsive'
import { Route as AppWebsiteFoundationRollbackRouteImport } from './routes/_app/website-foundation/rollback'
import { Route as AppWebsiteFoundationThemesRouteImport } from './routes/_app/website-foundation/themes'
import { Route as AppWebsiteFoundationWizardRouteImport } from './routes/_app/website-foundation/wizard'
import { Route as AppWebsiteFoundationWordpressRouteImport } from './routes/_app/website-foundation/wordpress'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchConsoleRoute = AppSearchConsoleRouteImport.update({
  id: '/search-console',
  path: '/search-console',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchKnowledgeRoute = AppSearchKnowledgeRouteImport.update({
  id: '/search-knowledge',
  path: '/search-knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppWebsiteFoundationRoute = AppWebsiteFoundationRouteImport.update({
  id: '/website-foundation',
  path: '/website-foundation',
  getParentRoute: () => AppRoute,
} as any)
const AppBusinessProfileIndexRoute = AppBusinessProfileIndexRouteImport.update({
  id: '/business-profile/',
  path: '/business-profile/',
  getParentRoute: () => AppRoute,
} as any)
const AppCompetitorsIndexRoute = AppCompetitorsIndexRouteImport.update({
  id: '/competitors/',
  path: '/competitors/',
  getParentRoute: () => AppRoute,
} as any)
const AppGoogleProductsIndexRoute = AppGoogleProductsIndexRouteImport.update({
  id: '/google-products/',
  path: '/google-products/',
  getParentRoute: () => AppRoute,
} as any)
const AppKeywordsIndexRoute = AppKeywordsIndexRouteImport.update({
  id: '/keywords/',
  path: '/keywords/',
  getParentRoute: () => AppRoute,
} as any)
const AppMobileIndexRoute = AppMobileIndexRouteImport.update({
  id: '/mobile/',
  path: '/mobile/',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceIndexRoute = AppPerformanceIndexRouteImport.update({
  id: '/performance/',
  path: '/performance/',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchConsoleIndexRoute = AppSearchConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSearchConsoleRoute,
} as any)
const AppSearchConsoleAmpRoute = AppSearchConsoleAmpRouteImport.update({
  id: '/amp',
  path: '/amp',
  getParentRoute: () => AppSearchConsoleRoute,
} as any)
const AppSearchConsoleCountriesRoute =
  AppSearchConsoleCountriesRouteImport.update({
    id: '/countries',
    path: '/countries',
    getParentRoute: () => AppSearchConsoleRoute,
  } as any)
const AppSearchConsoleCoverageRoute =
  AppSearchConsoleCoverageRouteImport.update({
    id: '/coverage',
    path: '/coverage',
    getParentRoute: () => AppSearchConsoleRoute,
  } as any)
const AppSearchConsoleCwvRoute = AppSearchConsoleCwvRouteImport.update({
  id: '/cwv',
  path: '/cwv',
  getParentRoute: () => AppSearchConsoleRoute,
} as any)
const AppSearchConsoleDevicesRoute = AppSearchConsoleDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AppSearchConsoleRoute,
} as any)
const AppSearchConsoleLinksRoute = AppSearchConsoleLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AppSearchConsoleRoute,
} as any)
const AppSearchConsoleManualActionsRoute =
  AppSearchConsoleManualActionsRouteImport.update({
    id: '/manual-actions',
    path: '/manual-actions',
    getParentRoute: () => AppSearchConsoleRoute,
  } as any)
const AppSearchConsoleMobileUsabilityRoute =
  AppSearchConsoleMobileUsabilityRouteImport.update({
    id: '/mobile-usability',
    path: '/mobile-usability',
    getParentRoute: () => AppSearchConsoleRoute,
  } as any)
const AppSearchConsolePagesRoute = AppSearchConsolePagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AppSearchConsoleRoute,
} as any)
const AppSearchConsolePerformanceRoute =
  AppSearchConsolePerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AppSearchConsoleRoute,
  } as any)
const AppSearchConsolePropertyDetailsRoute =
  AppSearchConsolePropertyDetailsRouteImport.update({
    id: '/property-details',
    path: '/property-details',
    getParentRoute: () => AppSearchConsoleRoute,
  } as any)
const AppSearchConsoleQueriesRoute = AppSearchConsoleQueriesRouteImport.update({
  id: '/queries',
  path: '/queries',
  getParentRoute: () => AppSearchConsoleRoute,
} as any)
const AppSearchConsoleSitemapsRoute =
  AppSearchConsoleSitemapsRouteImport.update({
    id: '/sitemaps',
    path: '/sitemaps',
    getParentRoute: () => AppSearchConsoleRoute,
  } as any)
const AppSearchConsoleUrlInspectionRoute =
  AppSearchConsoleUrlInspectionRouteImport.update({
    id: '/url-inspection',
    path: '/url-inspection',
    getParentRoute: () => AppSearchConsoleRoute,
  } as any)
const AppSearchConsoleVerificationRoute =
  AppSearchConsoleVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => AppSearchConsoleRoute,
  } as any)
const AppSearchKnowledgeIndexRoute = AppSearchKnowledgeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSearchKnowledgeRoute,
} as any)
const AppSearchKnowledgeActivityLogsRoute =
  AppSearchKnowledgeActivityLogsRouteImport.update({
    id: '/activity-logs',
    path: '/activity-logs',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgeAiSearchOverviewRoute =
  AppSearchKnowledgeAiSearchOverviewRouteImport.update({
    id: '/ai-search-overview',
    path: '/ai-search-overview',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgeApprovalsRoute =
  AppSearchKnowledgeApprovalsRouteImport.update({
    id: '/approvals',
    path: '/approvals',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgeDeviceBehaviourRoute =
  AppSearchKnowledgeDeviceBehaviourRouteImport.update({
    id: '/device-behaviour',
    path: '/device-behaviour',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgeFeaturedSnippetsRoute =
  AppSearchKnowledgeFeaturedSnippetsRouteImport.update({
    id: '/featured-snippets',
    path: '/featured-snippets',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgeFutureTrendsRoute =
  AppSearchKnowledgeFutureTrendsRouteImport.update({
    id: '/future-trends',
    path: '/future-trends',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgeGoogleAlgorithmUpdatesRoute =
  AppSearchKnowledgeGoogleAlgorithmUpdatesRouteImport.update({
    id: '/google-algorithm-updates',
    path: '/google-algorithm-updates',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgeGoogleRankingFactorsRoute =
  AppSearchKnowledgeGoogleRankingFactorsRouteImport.update({
    id: '/google-ranking-factors',
    path: '/google-ranking-factors',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgeGoogleSearchArchitectureRoute =
  AppSearchKnowledgeGoogleSearchArchitectureRouteImport.update({
    id: '/google-search-architecture',
    path: '/google-search-architecture',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgeImageSearchRoute =
  AppSearchKnowledgeImageSearchRouteImport.update({
    id: '/image-search',
    path: '/image-search',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgeKnowledgeGraphRoute =
  AppSearchKnowledgeKnowledgeGraphRouteImport.update({
    id: '/knowledge-graph',
    path: '/knowledge-graph',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgeKnowledgeRulesRoute =
  AppSearchKnowledgeKnowledgeRulesRouteImport.update({
    id: '/knowledge-rules',
    path: '/knowledge-rules',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgeLocalSearchRoute =
  AppSearchKnowledgeLocalSearchRouteImport.update({
    id: '/local-search',
    path: '/local-search',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgeMarketAnalysisRoute =
  AppSearchKnowledgeMarketAnalysisRouteImport.update({
    id: '/market-analysis',
    path: '/market-analysis',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgeNewsSearchRoute =
  AppSearchKnowledgeNewsSearchRouteImport.update({
    id: '/news-search',
    path: '/news-search',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgePeopleAlsoAskRoute =
  AppSearchKnowledgePeopleAlsoAskRouteImport.update({
    id: '/people-also-ask',
    path: '/people-also-ask',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgeRichResultsRoute =
  AppSearchKnowledgeRichResultsRouteImport.update({
    id: '/rich-results',
    path: '/rich-results',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgeSearchIntentRoute =
  AppSearchKnowledgeSearchIntentRouteImport.update({
    id: '/search-intent',
    path: '/search-intent',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgeSearchOperatorsRoute =
  AppSearchKnowledgeSearchOperatorsRouteImport.update({
    id: '/search-operators',
    path: '/search-operators',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgeSerpFeaturesRoute =
  AppSearchKnowledgeSerpFeaturesRouteImport.update({
    id: '/serp-features',
    path: '/serp-features',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgeSerpLayoutRoute =
  AppSearchKnowledgeSerpLayoutRouteImport.update({
    id: '/serp-layout',
    path: '/serp-layout',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgeSettingsRoute =
  AppSearchKnowledgeSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgeShoppingSearchRoute =
  AppSearchKnowledgeShoppingSearchRouteImport.update({
    id: '/shopping-search',
    path: '/shopping-search',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgeVersionHistoryRoute =
  AppSearchKnowledgeVersionHistoryRouteImport.update({
    id: '/version-history',
    path: '/version-history',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgeVideoSearchRoute =
  AppSearchKnowledgeVideoSearchRouteImport.update({
    id: '/video-search',
    path: '/video-search',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgeVoiceSearchRoute =
  AppSearchKnowledgeVoiceSearchRouteImport.update({
    id: '/voice-search',
    path: '/voice-search',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSeoAnalyzerIndexRoute = AppSeoAnalyzerIndexRouteImport.update({
  id: '/seo-analyzer/',
  path: '/seo-analyzer/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackingIndexRoute = AppTrackingIndexRouteImport.update({
  id: '/tracking/',
  path: '/tracking/',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackingActivityLogsRoute = AppTrackingActivityLogsRouteImport.update({
  id: '/tracking/activity-logs',
  path: '/tracking/activity-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackingApprovalsRoute = AppTrackingApprovalsRouteImport.update({
  id: '/tracking/approvals',
  path: '/tracking/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackingBusinessGoalsRoute =
  AppTrackingBusinessGoalsRouteImport.update({
    id: '/tracking/business-goals',
    path: '/tracking/business-goals',
    getParentRoute: () => AppRoute,
  } as any)
const AppTrackingConfigurationRoute =
  AppTrackingConfigurationRouteImport.update({
    id: '/tracking/configuration',
    path: '/tracking/configuration',
    getParentRoute: () => AppRoute,
  } as any)
const AppTrackingConsentRoute = AppTrackingConsentRouteImport.update({
  id: '/tracking/consent',
  path: '/tracking/consent',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackingContactFormsRoute = AppTrackingContactFormsRouteImport.update({
  id: '/tracking/contact-forms',
  path: '/tracking/contact-forms',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackingConversionStrategyRoute =
  AppTrackingConversionStrategyRouteImport.update({
    id: '/tracking/conversion-strategy',
    path: '/tracking/conversion-strategy',
    getParentRoute: () => AppRoute,
  } as any)
const AppTrackingEventsRoute = AppTrackingEventsRouteImport.update({
  id: '/tracking/events',
  path: '/tracking/events',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackingKpiManagementRoute =
  AppTrackingKpiManagementRouteImport.update({
    id: '/tracking/kpi-management',
    path: '/tracking/kpi-management',
    getParentRoute: () => AppRoute,
  } as any)
const AppTrackingMeasurementPlanRoute =
  AppTrackingMeasurementPlanRouteImport.update({
    id: '/tracking/measurement-plan',
    path: '/tracking/measurement-plan',
    getParentRoute: () => AppRoute,
  } as any)
const AppTrackingOperationsRoute = AppTrackingOperationsRouteImport.update({
  id: '/tracking/operations',
  path: '/tracking/operations',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackingRoutingRoute = AppTrackingRoutingRouteImport.update({
  id: '/tracking/routing',
  path: '/tracking/routing',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackingSettingsRoute = AppTrackingSettingsRouteImport.update({
  id: '/tracking/settings',
  path: '/tracking/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackingSpamProtectionRoute =
  AppTrackingSpamProtectionRouteImport.update({
    id: '/tracking/spam-protection',
    path: '/tracking/spam-protection',
    getParentRoute: () => AppRoute,
  } as any)
const AppTrackingTestingRoute = AppTrackingTestingRouteImport.update({
  id: '/tracking/testing',
  path: '/tracking/testing',
  getParentRoute: () => AppRoute,
} as any)
const AppWebsiteFoundationIndexRoute =
  AppWebsiteFoundationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppWebsiteFoundationRoute,
  } as any)
const AppWebsiteFoundationApprovalsRoute =
  AppWebsiteFoundationApprovalsRouteImport.update({
    id: '/approvals',
    path: '/approvals',
    getParentRoute: () => AppWebsiteFoundationRoute,
  } as any)
const AppWebsiteFoundationAuditRoute =
  AppWebsiteFoundationAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AppWebsiteFoundationRoute,
  } as any)
const AppWebsiteFoundationAutomationRoute =
  AppWebsiteFoundationAutomationRouteImport.update({
    id: '/automation',
    path: '/automation',
    getParentRoute: () => AppWebsiteFoundationRoute,
  } as any)
const AppWebsiteFoundationBacklogRoute =
  AppWebsiteFoundationBacklogRouteImport.update({
    id: '/backlog',
    path: '/backlog',
    getParentRoute: () => AppWebsiteFoundationRoute,
  } as any)
const AppWebsiteFoundationBrandRoute =
  AppWebsiteFoundationBrandRouteImport.update({
    id: '/brand',
    path: '/brand',
    getParentRoute: () => AppWebsiteFoundationRoute,
  } as any)
const AppWebsiteFoundationDeploymentsRoute =
  AppWebsiteFoundationDeploymentsRouteImport.update({
    id: '/deployments',
    path: '/deployments',
    getParentRoute: () => AppWebsiteFoundationRoute,
  } as any)
const AppWebsiteFoundationFormsRoute =
  AppWebsiteFoundationFormsRouteImport.update({
    id: '/forms',
    path: '/forms',
    getParentRoute: () => AppWebsiteFoundationRoute,
  } as any)
const AppWebsiteFoundationInventoryRoute =
  AppWebsiteFoundationInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AppWebsiteFoundationRoute,
  } as any)
const AppWebsiteFoundationLogsRoute =
  AppWebsiteFoundationLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AppWebsiteFoundationRoute,
  } as any)
const AppWebsiteFoundationOverviewRoute =
  AppWebsiteFoundationOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AppWebsiteFoundationRoute,
  } as any)
const AppWebsiteFoundationPerformanceRoute =
  AppWebsiteFoundationPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AppWebsiteFoundationRoute,
  } as any)
const AppWebsiteFoundationPluginsRoute =
  AppWebsiteFoundationPluginsRouteImport.update({
    id: '/plugins',
    path: '/plugins',
    getParentRoute: () => AppWebsiteFoundationRoute,
  } as any)
const AppWebsiteFoundationResponsiveRoute =
  AppWebsiteFoundationResponsiveRouteImport.update({
    id: '/responsive',
    path: '/responsive',
    getParentRoute: () => AppWebsiteFoundationRoute,
  } as any)
const AppWebsiteFoundationRollbackRoute =
  AppWebsiteFoundationRollbackRouteImport.update({
    id: '/rollback',
    path: '/rollback',
    getParentRoute: () => AppWebsiteFoundationRoute,
  } as any)
const AppWebsiteFoundationThemesRoute =
  AppWebsiteFoundationThemesRouteImport.update({
    id: '/themes',
    path: '/themes',
    getParentRoute: () => AppWebsiteFoundationRoute,
  } as any)
const AppWebsiteFoundationWizardRoute =
  AppWebsiteFoundationWizardRouteImport.update({
    id: '/wizard',
    path: '/wizard',
    getParentRoute: () => AppWebsiteFoundationRoute,
  } as any)
const AppWebsiteFoundationWordpressRoute =
  AppWebsiteFoundationWordpressRouteImport.update({
    id: '/wordpress',
    path: '/wordpress',
    getParentRoute: () => AppWebsiteFoundationRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/search-console': typeof AppSearchConsoleRouteWithChildren
  '/search-knowledge': typeof AppSearchKnowledgeRouteWithChildren
  '/website-foundation': typeof AppWebsiteFoundationRouteWithChildren
  '/search-console/amp': typeof AppSearchConsoleAmpRoute
  '/search-console/countries': typeof AppSearchConsoleCountriesRoute
  '/search-console/coverage': typeof AppSearchConsoleCoverageRoute
  '/search-console/cwv': typeof AppSearchConsoleCwvRoute
  '/search-console/devices': typeof AppSearchConsoleDevicesRoute
  '/search-console/links': typeof AppSearchConsoleLinksRoute
  '/search-console/manual-actions': typeof AppSearchConsoleManualActionsRoute
  '/search-console/mobile-usability': typeof AppSearchConsoleMobileUsabilityRoute
  '/search-console/pages': typeof AppSearchConsolePagesRoute
  '/search-console/performance': typeof AppSearchConsolePerformanceRoute
  '/search-console/property-details': typeof AppSearchConsolePropertyDetailsRoute
  '/search-console/queries': typeof AppSearchConsoleQueriesRoute
  '/search-console/sitemaps': typeof AppSearchConsoleSitemapsRoute
  '/search-console/url-inspection': typeof AppSearchConsoleUrlInspectionRoute
  '/search-console/verification': typeof AppSearchConsoleVerificationRoute
  '/search-knowledge/activity-logs': typeof AppSearchKnowledgeActivityLogsRoute
  '/search-knowledge/ai-search-overview': typeof AppSearchKnowledgeAiSearchOverviewRoute
  '/search-knowledge/approvals': typeof AppSearchKnowledgeApprovalsRoute
  '/search-knowledge/device-behaviour': typeof AppSearchKnowledgeDeviceBehaviourRoute
  '/search-knowledge/featured-snippets': typeof AppSearchKnowledgeFeaturedSnippetsRoute
  '/search-knowledge/future-trends': typeof AppSearchKnowledgeFutureTrendsRoute
  '/search-knowledge/google-algorithm-updates': typeof AppSearchKnowledgeGoogleAlgorithmUpdatesRoute
  '/search-knowledge/google-ranking-factors': typeof AppSearchKnowledgeGoogleRankingFactorsRoute
  '/search-knowledge/google-search-architecture': typeof AppSearchKnowledgeGoogleSearchArchitectureRoute
  '/search-knowledge/image-search': typeof AppSearchKnowledgeImageSearchRoute
  '/search-knowledge/knowledge-graph': typeof AppSearchKnowledgeKnowledgeGraphRoute
  '/search-knowledge/knowledge-rules': typeof AppSearchKnowledgeKnowledgeRulesRoute
  '/search-knowledge/local-search': typeof AppSearchKnowledgeLocalSearchRoute
  '/search-knowledge/market-analysis': typeof AppSearchKnowledgeMarketAnalysisRoute
  '/search-knowledge/news-search': typeof AppSearchKnowledgeNewsSearchRoute
  '/search-knowledge/people-also-ask': typeof AppSearchKnowledgePeopleAlsoAskRoute
  '/search-knowledge/rich-results': typeof AppSearchKnowledgeRichResultsRoute
  '/search-knowledge/search-intent': typeof AppSearchKnowledgeSearchIntentRoute
  '/search-knowledge/search-operators': typeof AppSearchKnowledgeSearchOperatorsRoute
  '/search-knowledge/serp-features': typeof AppSearchKnowledgeSerpFeaturesRoute
  '/search-knowledge/serp-layout': typeof AppSearchKnowledgeSerpLayoutRoute
  '/search-knowledge/settings': typeof AppSearchKnowledgeSettingsRoute
  '/search-knowledge/shopping-search': typeof AppSearchKnowledgeShoppingSearchRoute
  '/search-knowledge/version-history': typeof AppSearchKnowledgeVersionHistoryRoute
  '/search-knowledge/video-search': typeof AppSearchKnowledgeVideoSearchRoute
  '/search-knowledge/voice-search': typeof AppSearchKnowledgeVoiceSearchRoute
  '/tracking/activity-logs': typeof AppTrackingActivityLogsRoute
  '/tracking/approvals': typeof AppTrackingApprovalsRoute
  '/tracking/business-goals': typeof AppTrackingBusinessGoalsRoute
  '/tracking/configuration': typeof AppTrackingConfigurationRoute
  '/tracking/consent': typeof AppTrackingConsentRoute
  '/tracking/contact-forms': typeof AppTrackingContactFormsRoute
  '/tracking/conversion-strategy': typeof AppTrackingConversionStrategyRoute
  '/tracking/events': typeof AppTrackingEventsRoute
  '/tracking/kpi-management': typeof AppTrackingKpiManagementRoute
  '/tracking/measurement-plan': typeof AppTrackingMeasurementPlanRoute
  '/tracking/operations': typeof AppTrackingOperationsRoute
  '/tracking/routing': typeof AppTrackingRoutingRoute
  '/tracking/settings': typeof AppTrackingSettingsRoute
  '/tracking/spam-protection': typeof AppTrackingSpamProtectionRoute
  '/tracking/testing': typeof AppTrackingTestingRoute
  '/website-foundation/approvals': typeof AppWebsiteFoundationApprovalsRoute
  '/website-foundation/audit': typeof AppWebsiteFoundationAuditRoute
  '/website-foundation/automation': typeof AppWebsiteFoundationAutomationRoute
  '/website-foundation/backlog': typeof AppWebsiteFoundationBacklogRoute
  '/website-foundation/brand': typeof AppWebsiteFoundationBrandRoute
  '/website-foundation/deployments': typeof AppWebsiteFoundationDeploymentsRoute
  '/website-foundation/forms': typeof AppWebsiteFoundationFormsRoute
  '/website-foundation/inventory': typeof AppWebsiteFoundationInventoryRoute
  '/website-foundation/logs': typeof AppWebsiteFoundationLogsRoute
  '/website-foundation/overview': typeof AppWebsiteFoundationOverviewRoute
  '/website-foundation/performance': typeof AppWebsiteFoundationPerformanceRoute
  '/website-foundation/plugins': typeof AppWebsiteFoundationPluginsRoute
  '/website-foundation/responsive': typeof AppWebsiteFoundationResponsiveRoute
  '/website-foundation/rollback': typeof AppWebsiteFoundationRollbackRoute
  '/website-foundation/themes': typeof AppWebsiteFoundationThemesRoute
  '/website-foundation/wizard': typeof AppWebsiteFoundationWizardRoute
  '/website-foundation/wordpress': typeof AppWebsiteFoundationWordpressRoute
  '/business-profile/': typeof AppBusinessProfileIndexRoute
  '/competitors/': typeof AppCompetitorsIndexRoute
  '/google-products/': typeof AppGoogleProductsIndexRoute
  '/keywords/': typeof AppKeywordsIndexRoute
  '/mobile/': typeof AppMobileIndexRoute
  '/performance/': typeof AppPerformanceIndexRoute
  '/reports/': typeof AppReportsIndexRoute
  '/search-console/': typeof AppSearchConsoleIndexRoute
  '/search-knowledge/': typeof AppSearchKnowledgeIndexRoute
  '/seo-analyzer/': typeof AppSeoAnalyzerIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/tracking/': typeof AppTrackingIndexRoute
  '/website-foundation/': typeof AppWebsiteFoundationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/search-console/amp': typeof AppSearchConsoleAmpRoute
  '/search-console/countries': typeof AppSearchConsoleCountriesRoute
  '/search-console/coverage': typeof AppSearchConsoleCoverageRoute
  '/search-console/cwv': typeof AppSearchConsoleCwvRoute
  '/search-console/devices': typeof AppSearchConsoleDevicesRoute
  '/search-console/links': typeof AppSearchConsoleLinksRoute
  '/search-console/manual-actions': typeof AppSearchConsoleManualActionsRoute
  '/search-console/mobile-usability': typeof AppSearchConsoleMobileUsabilityRoute
  '/search-console/pages': typeof AppSearchConsolePagesRoute
  '/search-console/performance': typeof AppSearchConsolePerformanceRoute
  '/search-console/property-details': typeof AppSearchConsolePropertyDetailsRoute
  '/search-console/queries': typeof AppSearchConsoleQueriesRoute
  '/search-console/sitemaps': typeof AppSearchConsoleSitemapsRoute
  '/search-console/url-inspection': typeof AppSearchConsoleUrlInspectionRoute
  '/search-console/verification': typeof AppSearchConsoleVerificationRoute
  '/search-knowledge/activity-logs': typeof AppSearchKnowledgeActivityLogsRoute
  '/search-knowledge/ai-search-overview': typeof AppSearchKnowledgeAiSearchOverviewRoute
  '/search-knowledge/approvals': typeof AppSearchKnowledgeApprovalsRoute
  '/search-knowledge/device-behaviour': typeof AppSearchKnowledgeDeviceBehaviourRoute
  '/search-knowledge/featured-snippets': typeof AppSearchKnowledgeFeaturedSnippetsRoute
  '/search-knowledge/future-trends': typeof AppSearchKnowledgeFutureTrendsRoute
  '/search-knowledge/google-algorithm-updates': typeof AppSearchKnowledgeGoogleAlgorithmUpdatesRoute
  '/search-knowledge/google-ranking-factors': typeof AppSearchKnowledgeGoogleRankingFactorsRoute
  '/search-knowledge/google-search-architecture': typeof AppSearchKnowledgeGoogleSearchArchitectureRoute
  '/search-knowledge/image-search': typeof AppSearchKnowledgeImageSearchRoute
  '/search-knowledge/knowledge-graph': typeof AppSearchKnowledgeKnowledgeGraphRoute
  '/search-knowledge/knowledge-rules': typeof AppSearchKnowledgeKnowledgeRulesRoute
  '/search-knowledge/local-search': typeof AppSearchKnowledgeLocalSearchRoute
  '/search-knowledge/market-analysis': typeof AppSearchKnowledgeMarketAnalysisRoute
  '/search-knowledge/news-search': typeof AppSearchKnowledgeNewsSearchRoute
  '/search-knowledge/people-also-ask': typeof AppSearchKnowledgePeopleAlsoAskRoute
  '/search-knowledge/rich-results': typeof AppSearchKnowledgeRichResultsRoute
  '/search-knowledge/search-intent': typeof AppSearchKnowledgeSearchIntentRoute
  '/search-knowledge/search-operators': typeof AppSearchKnowledgeSearchOperatorsRoute
  '/search-knowledge/serp-features': typeof AppSearchKnowledgeSerpFeaturesRoute
  '/search-knowledge/serp-layout': typeof AppSearchKnowledgeSerpLayoutRoute
  '/search-knowledge/settings': typeof AppSearchKnowledgeSettingsRoute
  '/search-knowledge/shopping-search': typeof AppSearchKnowledgeShoppingSearchRoute
  '/search-knowledge/version-history': typeof AppSearchKnowledgeVersionHistoryRoute
  '/search-knowledge/video-search': typeof AppSearchKnowledgeVideoSearchRoute
  '/search-knowledge/voice-search': typeof AppSearchKnowledgeVoiceSearchRoute
  '/tracking/activity-logs': typeof AppTrackingActivityLogsRoute
  '/tracking/approvals': typeof AppTrackingApprovalsRoute
  '/tracking/business-goals': typeof AppTrackingBusinessGoalsRoute
  '/tracking/configuration': typeof AppTrackingConfigurationRoute
  '/tracking/consent': typeof AppTrackingConsentRoute
  '/tracking/contact-forms': typeof AppTrackingContactFormsRoute
  '/tracking/conversion-strategy': typeof AppTrackingConversionStrategyRoute
  '/tracking/events': typeof AppTrackingEventsRoute
  '/tracking/kpi-management': typeof AppTrackingKpiManagementRoute
  '/tracking/measurement-plan': typeof AppTrackingMeasurementPlanRoute
  '/tracking/operations': typeof AppTrackingOperationsRoute
  '/tracking/routing': typeof AppTrackingRoutingRoute
  '/tracking/settings': typeof AppTrackingSettingsRoute
  '/tracking/spam-protection': typeof AppTrackingSpamProtectionRoute
  '/tracking/testing': typeof AppTrackingTestingRoute
  '/website-foundation/approvals': typeof AppWebsiteFoundationApprovalsRoute
  '/website-foundation/audit': typeof AppWebsiteFoundationAuditRoute
  '/website-foundation/automation': typeof AppWebsiteFoundationAutomationRoute
  '/website-foundation/backlog': typeof AppWebsiteFoundationBacklogRoute
  '/website-foundation/brand': typeof AppWebsiteFoundationBrandRoute
  '/website-foundation/deployments': typeof AppWebsiteFoundationDeploymentsRoute
  '/website-foundation/forms': typeof AppWebsiteFoundationFormsRoute
  '/website-foundation/inventory': typeof AppWebsiteFoundationInventoryRoute
  '/website-foundation/logs': typeof AppWebsiteFoundationLogsRoute
  '/website-foundation/overview': typeof AppWebsiteFoundationOverviewRoute
  '/website-foundation/performance': typeof AppWebsiteFoundationPerformanceRoute
  '/website-foundation/plugins': typeof AppWebsiteFoundationPluginsRoute
  '/website-foundation/responsive': typeof AppWebsiteFoundationResponsiveRoute
  '/website-foundation/rollback': typeof AppWebsiteFoundationRollbackRoute
  '/website-foundation/themes': typeof AppWebsiteFoundationThemesRoute
  '/website-foundation/wizard': typeof AppWebsiteFoundationWizardRoute
  '/website-foundation/wordpress': typeof AppWebsiteFoundationWordpressRoute
  '/business-profile': typeof AppBusinessProfileIndexRoute
  '/competitors': typeof AppCompetitorsIndexRoute
  '/google-products': typeof AppGoogleProductsIndexRoute
  '/keywords': typeof AppKeywordsIndexRoute
  '/mobile': typeof AppMobileIndexRoute
  '/performance': typeof AppPerformanceIndexRoute
  '/reports': typeof AppReportsIndexRoute
  '/search-console': typeof AppSearchConsoleIndexRoute
  '/search-knowledge': typeof AppSearchKnowledgeIndexRoute
  '/seo-analyzer': typeof AppSeoAnalyzerIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/tracking': typeof AppTrackingIndexRoute
  '/website-foundation': typeof AppWebsiteFoundationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/search-console': typeof AppSearchConsoleRouteWithChildren
  '/_app/search-knowledge': typeof AppSearchKnowledgeRouteWithChildren
  '/_app/website-foundation': typeof AppWebsiteFoundationRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/search-console/amp': typeof AppSearchConsoleAmpRoute
  '/_app/search-console/countries': typeof AppSearchConsoleCountriesRoute
  '/_app/search-console/coverage': typeof AppSearchConsoleCoverageRoute
  '/_app/search-console/cwv': typeof AppSearchConsoleCwvRoute
  '/_app/search-console/devices': typeof AppSearchConsoleDevicesRoute
  '/_app/search-console/links': typeof AppSearchConsoleLinksRoute
  '/_app/search-console/manual-actions': typeof AppSearchConsoleManualActionsRoute
  '/_app/search-console/mobile-usability': typeof AppSearchConsoleMobileUsabilityRoute
  '/_app/search-console/pages': typeof AppSearchConsolePagesRoute
  '/_app/search-console/performance': typeof AppSearchConsolePerformanceRoute
  '/_app/search-console/property-details': typeof AppSearchConsolePropertyDetailsRoute
  '/_app/search-console/queries': typeof AppSearchConsoleQueriesRoute
  '/_app/search-console/sitemaps': typeof AppSearchConsoleSitemapsRoute
  '/_app/search-console/url-inspection': typeof AppSearchConsoleUrlInspectionRoute
  '/_app/search-console/verification': typeof AppSearchConsoleVerificationRoute
  '/_app/search-knowledge/activity-logs': typeof AppSearchKnowledgeActivityLogsRoute
  '/_app/search-knowledge/ai-search-overview': typeof AppSearchKnowledgeAiSearchOverviewRoute
  '/_app/search-knowledge/approvals': typeof AppSearchKnowledgeApprovalsRoute
  '/_app/search-knowledge/device-behaviour': typeof AppSearchKnowledgeDeviceBehaviourRoute
  '/_app/search-knowledge/featured-snippets': typeof AppSearchKnowledgeFeaturedSnippetsRoute
  '/_app/search-knowledge/future-trends': typeof AppSearchKnowledgeFutureTrendsRoute
  '/_app/search-knowledge/google-algorithm-updates': typeof AppSearchKnowledgeGoogleAlgorithmUpdatesRoute
  '/_app/search-knowledge/google-ranking-factors': typeof AppSearchKnowledgeGoogleRankingFactorsRoute
  '/_app/search-knowledge/google-search-architecture': typeof AppSearchKnowledgeGoogleSearchArchitectureRoute
  '/_app/search-knowledge/image-search': typeof AppSearchKnowledgeImageSearchRoute
  '/_app/search-knowledge/knowledge-graph': typeof AppSearchKnowledgeKnowledgeGraphRoute
  '/_app/search-knowledge/knowledge-rules': typeof AppSearchKnowledgeKnowledgeRulesRoute
  '/_app/search-knowledge/local-search': typeof AppSearchKnowledgeLocalSearchRoute
  '/_app/search-knowledge/market-analysis': typeof AppSearchKnowledgeMarketAnalysisRoute
  '/_app/search-knowledge/news-search': typeof AppSearchKnowledgeNewsSearchRoute
  '/_app/search-knowledge/people-also-ask': typeof AppSearchKnowledgePeopleAlsoAskRoute
  '/_app/search-knowledge/rich-results': typeof AppSearchKnowledgeRichResultsRoute
  '/_app/search-knowledge/search-intent': typeof AppSearchKnowledgeSearchIntentRoute
  '/_app/search-knowledge/search-operators': typeof AppSearchKnowledgeSearchOperatorsRoute
  '/_app/search-knowledge/serp-features': typeof AppSearchKnowledgeSerpFeaturesRoute
  '/_app/search-knowledge/serp-layout': typeof AppSearchKnowledgeSerpLayoutRoute
  '/_app/search-knowledge/settings': typeof AppSearchKnowledgeSettingsRoute
  '/_app/search-knowledge/shopping-search': typeof AppSearchKnowledgeShoppingSearchRoute
  '/_app/search-knowledge/version-history': typeof AppSearchKnowledgeVersionHistoryRoute
  '/_app/search-knowledge/video-search': typeof AppSearchKnowledgeVideoSearchRoute
  '/_app/search-knowledge/voice-search': typeof AppSearchKnowledgeVoiceSearchRoute
  '/_app/tracking/activity-logs': typeof AppTrackingActivityLogsRoute
  '/_app/tracking/approvals': typeof AppTrackingApprovalsRoute
  '/_app/tracking/business-goals': typeof AppTrackingBusinessGoalsRoute
  '/_app/tracking/configuration': typeof AppTrackingConfigurationRoute
  '/_app/tracking/consent': typeof AppTrackingConsentRoute
  '/_app/tracking/contact-forms': typeof AppTrackingContactFormsRoute
  '/_app/tracking/conversion-strategy': typeof AppTrackingConversionStrategyRoute
  '/_app/tracking/events': typeof AppTrackingEventsRoute
  '/_app/tracking/kpi-management': typeof AppTrackingKpiManagementRoute
  '/_app/tracking/measurement-plan': typeof AppTrackingMeasurementPlanRoute
  '/_app/tracking/operations': typeof AppTrackingOperationsRoute
  '/_app/tracking/routing': typeof AppTrackingRoutingRoute
  '/_app/tracking/settings': typeof AppTrackingSettingsRoute
  '/_app/tracking/spam-protection': typeof AppTrackingSpamProtectionRoute
  '/_app/tracking/testing': typeof AppTrackingTestingRoute
  '/_app/website-foundation/approvals': typeof AppWebsiteFoundationApprovalsRoute
  '/_app/website-foundation/audit': typeof AppWebsiteFoundationAuditRoute
  '/_app/website-foundation/automation': typeof AppWebsiteFoundationAutomationRoute
  '/_app/website-foundation/backlog': typeof AppWebsiteFoundationBacklogRoute
  '/_app/website-foundation/brand': typeof AppWebsiteFoundationBrandRoute
  '/_app/website-foundation/deployments': typeof AppWebsiteFoundationDeploymentsRoute
  '/_app/website-foundation/forms': typeof AppWebsiteFoundationFormsRoute
  '/_app/website-foundation/inventory': typeof AppWebsiteFoundationInventoryRoute
  '/_app/website-foundation/logs': typeof AppWebsiteFoundationLogsRoute
  '/_app/website-foundation/overview': typeof AppWebsiteFoundationOverviewRoute
  '/_app/website-foundation/performance': typeof AppWebsiteFoundationPerformanceRoute
  '/_app/website-foundation/plugins': typeof AppWebsiteFoundationPluginsRoute
  '/_app/website-foundation/responsive': typeof AppWebsiteFoundationResponsiveRoute
  '/_app/website-foundation/rollback': typeof AppWebsiteFoundationRollbackRoute
  '/_app/website-foundation/themes': typeof AppWebsiteFoundationThemesRoute
  '/_app/website-foundation/wizard': typeof AppWebsiteFoundationWizardRoute
  '/_app/website-foundation/wordpress': typeof AppWebsiteFoundationWordpressRoute
  '/_app/business-profile/': typeof AppBusinessProfileIndexRoute
  '/_app/competitors/': typeof AppCompetitorsIndexRoute
  '/_app/google-products/': typeof AppGoogleProductsIndexRoute
  '/_app/keywords/': typeof AppKeywordsIndexRoute
  '/_app/mobile/': typeof AppMobileIndexRoute
  '/_app/performance/': typeof AppPerformanceIndexRoute
  '/_app/reports/': typeof AppReportsIndexRoute
  '/_app/search-console/': typeof AppSearchConsoleIndexRoute
  '/_app/search-knowledge/': typeof AppSearchKnowledgeIndexRoute
  '/_app/seo-analyzer/': typeof AppSeoAnalyzerIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/tracking/': typeof AppTrackingIndexRoute
  '/_app/website-foundation/': typeof AppWebsiteFoundationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/search-console'
    | '/search-knowledge'
    | '/website-foundation'
    | '/search-console/amp'
    | '/search-console/countries'
    | '/search-console/coverage'
    | '/search-console/cwv'
    | '/search-console/devices'
    | '/search-console/links'
    | '/search-console/manual-actions'
    | '/search-console/mobile-usability'
    | '/search-console/pages'
    | '/search-console/performance'
    | '/search-console/property-details'
    | '/search-console/queries'
    | '/search-console/sitemaps'
    | '/search-console/url-inspection'
    | '/search-console/verification'
    | '/search-knowledge/activity-logs'
    | '/search-knowledge/ai-search-overview'
    | '/search-knowledge/approvals'
    | '/search-knowledge/device-behaviour'
    | '/search-knowledge/featured-snippets'
    | '/search-knowledge/future-trends'
    | '/search-knowledge/google-algorithm-updates'
    | '/search-knowledge/google-ranking-factors'
    | '/search-knowledge/google-search-architecture'
    | '/search-knowledge/image-search'
    | '/search-knowledge/knowledge-graph'
    | '/search-knowledge/knowledge-rules'
    | '/search-knowledge/local-search'
    | '/search-knowledge/market-analysis'
    | '/search-knowledge/news-search'
    | '/search-knowledge/people-also-ask'
    | '/search-knowledge/rich-results'
    | '/search-knowledge/search-intent'
    | '/search-knowledge/search-operators'
    | '/search-knowledge/serp-features'
    | '/search-knowledge/serp-layout'
    | '/search-knowledge/settings'
    | '/search-knowledge/shopping-search'
    | '/search-knowledge/version-history'
    | '/search-knowledge/video-search'
    | '/search-knowledge/voice-search'
    | '/tracking/activity-logs'
    | '/tracking/approvals'
    | '/tracking/business-goals'
    | '/tracking/configuration'
    | '/tracking/consent'
    | '/tracking/contact-forms'
    | '/tracking/conversion-strategy'
    | '/tracking/events'
    | '/tracking/kpi-management'
    | '/tracking/measurement-plan'
    | '/tracking/operations'
    | '/tracking/routing'
    | '/tracking/settings'
    | '/tracking/spam-protection'
    | '/tracking/testing'
    | '/website-foundation/approvals'
    | '/website-foundation/audit'
    | '/website-foundation/automation'
    | '/website-foundation/backlog'
    | '/website-foundation/brand'
    | '/website-foundation/deployments'
    | '/website-foundation/forms'
    | '/website-foundation/inventory'
    | '/website-foundation/logs'
    | '/website-foundation/overview'
    | '/website-foundation/performance'
    | '/website-foundation/plugins'
    | '/website-foundation/responsive'
    | '/website-foundation/rollback'
    | '/website-foundation/themes'
    | '/website-foundation/wizard'
    | '/website-foundation/wordpress'
    | '/business-profile/'
    | '/competitors/'
    | '/google-products/'
    | '/keywords/'
    | '/mobile/'
    | '/performance/'
    | '/reports/'
    | '/search-console/'
    | '/search-knowledge/'
    | '/seo-analyzer/'
    | '/settings/'
    | '/tracking/'
    | '/website-foundation/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search-console/amp'
    | '/search-console/countries'
    | '/search-console/coverage'
    | '/search-console/cwv'
    | '/search-console/devices'
    | '/search-console/links'
    | '/search-console/manual-actions'
    | '/search-console/mobile-usability'
    | '/search-console/pages'
    | '/search-console/performance'
    | '/search-console/property-details'
    | '/search-console/queries'
    | '/search-console/sitemaps'
    | '/search-console/url-inspection'
    | '/search-console/verification'
    | '/search-knowledge/activity-logs'
    | '/search-knowledge/ai-search-overview'
    | '/search-knowledge/approvals'
    | '/search-knowledge/device-behaviour'
    | '/search-knowledge/featured-snippets'
    | '/search-knowledge/future-trends'
    | '/search-knowledge/google-algorithm-updates'
    | '/search-knowledge/google-ranking-factors'
    | '/search-knowledge/google-search-architecture'
    | '/search-knowledge/image-search'
    | '/search-knowledge/knowledge-graph'
    | '/search-knowledge/knowledge-rules'
    | '/search-knowledge/local-search'
    | '/search-knowledge/market-analysis'
    | '/search-knowledge/news-search'
    | '/search-knowledge/people-also-ask'
    | '/search-knowledge/rich-results'
    | '/search-knowledge/search-intent'
    | '/search-knowledge/search-operators'
    | '/search-knowledge/serp-features'
    | '/search-knowledge/serp-layout'
    | '/search-knowledge/settings'
    | '/search-knowledge/shopping-search'
    | '/search-knowledge/version-history'
    | '/search-knowledge/video-search'
    | '/search-knowledge/voice-search'
    | '/tracking/activity-logs'
    | '/tracking/approvals'
    | '/tracking/business-goals'
    | '/tracking/configuration'
    | '/tracking/consent'
    | '/tracking/contact-forms'
    | '/tracking/conversion-strategy'
    | '/tracking/events'
    | '/tracking/kpi-management'
    | '/tracking/measurement-plan'
    | '/tracking/operations'
    | '/tracking/routing'
    | '/tracking/settings'
    | '/tracking/spam-protection'
    | '/tracking/testing'
    | '/website-foundation/approvals'
    | '/website-foundation/audit'
    | '/website-foundation/automation'
    | '/website-foundation/backlog'
    | '/website-foundation/brand'
    | '/website-foundation/deployments'
    | '/website-foundation/forms'
    | '/website-foundation/inventory'
    | '/website-foundation/logs'
    | '/website-foundation/overview'
    | '/website-foundation/performance'
    | '/website-foundation/plugins'
    | '/website-foundation/responsive'
    | '/website-foundation/rollback'
    | '/website-foundation/themes'
    | '/website-foundation/wizard'
    | '/website-foundation/wordpress'
    | '/business-profile'
    | '/competitors'
    | '/google-products'
    | '/keywords'
    | '/mobile'
    | '/performance'
    | '/reports'
    | '/search-console'
    | '/search-knowledge'
    | '/seo-analyzer'
    | '/settings'
    | '/tracking'
    | '/website-foundation'
  id:
    | '__root__'
    | '/_app'
    | '/_app/search-console'
    | '/_app/search-knowledge'
    | '/_app/website-foundation'
    | '/_app/'
    | '/_app/search-console/amp'
    | '/_app/search-console/countries'
    | '/_app/search-console/coverage'
    | '/_app/search-console/cwv'
    | '/_app/search-console/devices'
    | '/_app/search-console/links'
    | '/_app/search-console/manual-actions'
    | '/_app/search-console/mobile-usability'
    | '/_app/search-console/pages'
    | '/_app/search-console/performance'
    | '/_app/search-console/property-details'
    | '/_app/search-console/queries'
    | '/_app/search-console/sitemaps'
    | '/_app/search-console/url-inspection'
    | '/_app/search-console/verification'
    | '/_app/search-knowledge/activity-logs'
    | '/_app/search-knowledge/ai-search-overview'
    | '/_app/search-knowledge/approvals'
    | '/_app/search-knowledge/device-behaviour'
    | '/_app/search-knowledge/featured-snippets'
    | '/_app/search-knowledge/future-trends'
    | '/_app/search-knowledge/google-algorithm-updates'
    | '/_app/search-knowledge/google-ranking-factors'
    | '/_app/search-knowledge/google-search-architecture'
    | '/_app/search-knowledge/image-search'
    | '/_app/search-knowledge/knowledge-graph'
    | '/_app/search-knowledge/knowledge-rules'
    | '/_app/search-knowledge/local-search'
    | '/_app/search-knowledge/market-analysis'
    | '/_app/search-knowledge/news-search'
    | '/_app/search-knowledge/people-also-ask'
    | '/_app/search-knowledge/rich-results'
    | '/_app/search-knowledge/search-intent'
    | '/_app/search-knowledge/search-operators'
    | '/_app/search-knowledge/serp-features'
    | '/_app/search-knowledge/serp-layout'
    | '/_app/search-knowledge/settings'
    | '/_app/search-knowledge/shopping-search'
    | '/_app/search-knowledge/version-history'
    | '/_app/search-knowledge/video-search'
    | '/_app/search-knowledge/voice-search'
    | '/_app/tracking/activity-logs'
    | '/_app/tracking/approvals'
    | '/_app/tracking/business-goals'
    | '/_app/tracking/configuration'
    | '/_app/tracking/consent'
    | '/_app/tracking/contact-forms'
    | '/_app/tracking/conversion-strategy'
    | '/_app/tracking/events'
    | '/_app/tracking/kpi-management'
    | '/_app/tracking/measurement-plan'
    | '/_app/tracking/operations'
    | '/_app/tracking/routing'
    | '/_app/tracking/settings'
    | '/_app/tracking/spam-protection'
    | '/_app/tracking/testing'
    | '/_app/website-foundation/approvals'
    | '/_app/website-foundation/audit'
    | '/_app/website-foundation/automation'
    | '/_app/website-foundation/backlog'
    | '/_app/website-foundation/brand'
    | '/_app/website-foundation/deployments'
    | '/_app/website-foundation/forms'
    | '/_app/website-foundation/inventory'
    | '/_app/website-foundation/logs'
    | '/_app/website-foundation/overview'
    | '/_app/website-foundation/performance'
    | '/_app/website-foundation/plugins'
    | '/_app/website-foundation/responsive'
    | '/_app/website-foundation/rollback'
    | '/_app/website-foundation/themes'
    | '/_app/website-foundation/wizard'
    | '/_app/website-foundation/wordpress'
    | '/_app/business-profile/'
    | '/_app/competitors/'
    | '/_app/google-products/'
    | '/_app/keywords/'
    | '/_app/mobile/'
    | '/_app/performance/'
    | '/_app/reports/'
    | '/_app/search-console/'
    | '/_app/search-knowledge/'
    | '/_app/seo-analyzer/'
    | '/_app/settings/'
    | '/_app/tracking/'
    | '/_app/website-foundation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search-console': {
      id: '/_app/search-console'
      path: '/search-console'
      fullPath: '/search-console'
      preLoaderRoute: typeof AppSearchConsoleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search-knowledge': {
      id: '/_app/search-knowledge'
      path: '/search-knowledge'
      fullPath: '/search-knowledge'
      preLoaderRoute: typeof AppSearchKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/website-foundation': {
      id: '/_app/website-foundation'
      path: '/website-foundation'
      fullPath: '/website-foundation'
      preLoaderRoute: typeof AppWebsiteFoundationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/business-profile/': {
      id: '/_app/business-profile/'
      path: '/business-profile'
      fullPath: '/business-profile/'
      preLoaderRoute: typeof AppBusinessProfileIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/competitors/': {
      id: '/_app/competitors/'
      path: '/competitors'
      fullPath: '/competitors/'
      preLoaderRoute: typeof AppCompetitorsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/google-products/': {
      id: '/_app/google-products/'
      path: '/google-products'
      fullPath: '/google-products/'
      preLoaderRoute: typeof AppGoogleProductsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/keywords/': {
      id: '/_app/keywords/'
      path: '/keywords'
      fullPath: '/keywords/'
      preLoaderRoute: typeof AppKeywordsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mobile/': {
      id: '/_app/mobile/'
      path: '/mobile'
      fullPath: '/mobile/'
      preLoaderRoute: typeof AppMobileIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/performance/': {
      id: '/_app/performance/'
      path: '/performance'
      fullPath: '/performance/'
      preLoaderRoute: typeof AppPerformanceIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/': {
      id: '/_app/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search-console/': {
      id: '/_app/search-console/'
      path: '/'
      fullPath: '/search-console/'
      preLoaderRoute: typeof AppSearchConsoleIndexRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-console/amp': {
      id: '/_app/search-console/amp'
      path: '/amp'
      fullPath: '/search-console/amp'
      preLoaderRoute: typeof AppSearchConsoleAmpRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-console/countries': {
      id: '/_app/search-console/countries'
      path: '/countries'
      fullPath: '/search-console/countries'
      preLoaderRoute: typeof AppSearchConsoleCountriesRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-console/coverage': {
      id: '/_app/search-console/coverage'
      path: '/coverage'
      fullPath: '/search-console/coverage'
      preLoaderRoute: typeof AppSearchConsoleCoverageRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-console/cwv': {
      id: '/_app/search-console/cwv'
      path: '/cwv'
      fullPath: '/search-console/cwv'
      preLoaderRoute: typeof AppSearchConsoleCwvRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-console/devices': {
      id: '/_app/search-console/devices'
      path: '/devices'
      fullPath: '/search-console/devices'
      preLoaderRoute: typeof AppSearchConsoleDevicesRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-console/links': {
      id: '/_app/search-console/links'
      path: '/links'
      fullPath: '/search-console/links'
      preLoaderRoute: typeof AppSearchConsoleLinksRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-console/manual-actions': {
      id: '/_app/search-console/manual-actions'
      path: '/manual-actions'
      fullPath: '/search-console/manual-actions'
      preLoaderRoute: typeof AppSearchConsoleManualActionsRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-console/mobile-usability': {
      id: '/_app/search-console/mobile-usability'
      path: '/mobile-usability'
      fullPath: '/search-console/mobile-usability'
      preLoaderRoute: typeof AppSearchConsoleMobileUsabilityRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-console/pages': {
      id: '/_app/search-console/pages'
      path: '/pages'
      fullPath: '/search-console/pages'
      preLoaderRoute: typeof AppSearchConsolePagesRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-console/performance': {
      id: '/_app/search-console/performance'
      path: '/performance'
      fullPath: '/search-console/performance'
      preLoaderRoute: typeof AppSearchConsolePerformanceRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-console/property-details': {
      id: '/_app/search-console/property-details'
      path: '/property-details'
      fullPath: '/search-console/property-details'
      preLoaderRoute: typeof AppSearchConsolePropertyDetailsRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-console/queries': {
      id: '/_app/search-console/queries'
      path: '/queries'
      fullPath: '/search-console/queries'
      preLoaderRoute: typeof AppSearchConsoleQueriesRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-console/sitemaps': {
      id: '/_app/search-console/sitemaps'
      path: '/sitemaps'
      fullPath: '/search-console/sitemaps'
      preLoaderRoute: typeof AppSearchConsoleSitemapsRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-console/url-inspection': {
      id: '/_app/search-console/url-inspection'
      path: '/url-inspection'
      fullPath: '/search-console/url-inspection'
      preLoaderRoute: typeof AppSearchConsoleUrlInspectionRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-console/verification': {
      id: '/_app/search-console/verification'
      path: '/verification'
      fullPath: '/search-console/verification'
      preLoaderRoute: typeof AppSearchConsoleVerificationRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-knowledge/': {
      id: '/_app/search-knowledge/'
      path: '/'
      fullPath: '/search-knowledge/'
      preLoaderRoute: typeof AppSearchKnowledgeIndexRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/activity-logs': {
      id: '/_app/search-knowledge/activity-logs'
      path: '/activity-logs'
      fullPath: '/search-knowledge/activity-logs'
      preLoaderRoute: typeof AppSearchKnowledgeActivityLogsRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/ai-search-overview': {
      id: '/_app/search-knowledge/ai-search-overview'
      path: '/ai-search-overview'
      fullPath: '/search-knowledge/ai-search-overview'
      preLoaderRoute: typeof AppSearchKnowledgeAiSearchOverviewRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/approvals': {
      id: '/_app/search-knowledge/approvals'
      path: '/approvals'
      fullPath: '/search-knowledge/approvals'
      preLoaderRoute: typeof AppSearchKnowledgeApprovalsRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/device-behaviour': {
      id: '/_app/search-knowledge/device-behaviour'
      path: '/device-behaviour'
      fullPath: '/search-knowledge/device-behaviour'
      preLoaderRoute: typeof AppSearchKnowledgeDeviceBehaviourRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/featured-snippets': {
      id: '/_app/search-knowledge/featured-snippets'
      path: '/featured-snippets'
      fullPath: '/search-knowledge/featured-snippets'
      preLoaderRoute: typeof AppSearchKnowledgeFeaturedSnippetsRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/future-trends': {
      id: '/_app/search-knowledge/future-trends'
      path: '/future-trends'
      fullPath: '/search-knowledge/future-trends'
      preLoaderRoute: typeof AppSearchKnowledgeFutureTrendsRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/google-algorithm-updates': {
      id: '/_app/search-knowledge/google-algorithm-updates'
      path: '/google-algorithm-updates'
      fullPath: '/search-knowledge/google-algorithm-updates'
      preLoaderRoute: typeof AppSearchKnowledgeGoogleAlgorithmUpdatesRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/google-ranking-factors': {
      id: '/_app/search-knowledge/google-ranking-factors'
      path: '/google-ranking-factors'
      fullPath: '/search-knowledge/google-ranking-factors'
      preLoaderRoute: typeof AppSearchKnowledgeGoogleRankingFactorsRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/google-search-architecture': {
      id: '/_app/search-knowledge/google-search-architecture'
      path: '/google-search-architecture'
      fullPath: '/search-knowledge/google-search-architecture'
      preLoaderRoute: typeof AppSearchKnowledgeGoogleSearchArchitectureRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/image-search': {
      id: '/_app/search-knowledge/image-search'
      path: '/image-search'
      fullPath: '/search-knowledge/image-search'
      preLoaderRoute: typeof AppSearchKnowledgeImageSearchRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/knowledge-graph': {
      id: '/_app/search-knowledge/knowledge-graph'
      path: '/knowledge-graph'
      fullPath: '/search-knowledge/knowledge-graph'
      preLoaderRoute: typeof AppSearchKnowledgeKnowledgeGraphRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/knowledge-rules': {
      id: '/_app/search-knowledge/knowledge-rules'
      path: '/knowledge-rules'
      fullPath: '/search-knowledge/knowledge-rules'
      preLoaderRoute: typeof AppSearchKnowledgeKnowledgeRulesRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/local-search': {
      id: '/_app/search-knowledge/local-search'
      path: '/local-search'
      fullPath: '/search-knowledge/local-search'
      preLoaderRoute: typeof AppSearchKnowledgeLocalSearchRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/market-analysis': {
      id: '/_app/search-knowledge/market-analysis'
      path: '/market-analysis'
      fullPath: '/search-knowledge/market-analysis'
      preLoaderRoute: typeof AppSearchKnowledgeMarketAnalysisRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/news-search': {
      id: '/_app/search-knowledge/news-search'
      path: '/news-search'
      fullPath: '/search-knowledge/news-search'
      preLoaderRoute: typeof AppSearchKnowledgeNewsSearchRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/people-also-ask': {
      id: '/_app/search-knowledge/people-also-ask'
      path: '/people-also-ask'
      fullPath: '/search-knowledge/people-also-ask'
      preLoaderRoute: typeof AppSearchKnowledgePeopleAlsoAskRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/rich-results': {
      id: '/_app/search-knowledge/rich-results'
      path: '/rich-results'
      fullPath: '/search-knowledge/rich-results'
      preLoaderRoute: typeof AppSearchKnowledgeRichResultsRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/search-intent': {
      id: '/_app/search-knowledge/search-intent'
      path: '/search-intent'
      fullPath: '/search-knowledge/search-intent'
      preLoaderRoute: typeof AppSearchKnowledgeSearchIntentRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/search-operators': {
      id: '/_app/search-knowledge/search-operators'
      path: '/search-operators'
      fullPath: '/search-knowledge/search-operators'
      preLoaderRoute: typeof AppSearchKnowledgeSearchOperatorsRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/serp-features': {
      id: '/_app/search-knowledge/serp-features'
      path: '/serp-features'
      fullPath: '/search-knowledge/serp-features'
      preLoaderRoute: typeof AppSearchKnowledgeSerpFeaturesRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/serp-layout': {
      id: '/_app/search-knowledge/serp-layout'
      path: '/serp-layout'
      fullPath: '/search-knowledge/serp-layout'
      preLoaderRoute: typeof AppSearchKnowledgeSerpLayoutRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/settings': {
      id: '/_app/search-knowledge/settings'
      path: '/settings'
      fullPath: '/search-knowledge/settings'
      preLoaderRoute: typeof AppSearchKnowledgeSettingsRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/shopping-search': {
      id: '/_app/search-knowledge/shopping-search'
      path: '/shopping-search'
      fullPath: '/search-knowledge/shopping-search'
      preLoaderRoute: typeof AppSearchKnowledgeShoppingSearchRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/version-history': {
      id: '/_app/search-knowledge/version-history'
      path: '/version-history'
      fullPath: '/search-knowledge/version-history'
      preLoaderRoute: typeof AppSearchKnowledgeVersionHistoryRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/video-search': {
      id: '/_app/search-knowledge/video-search'
      path: '/video-search'
      fullPath: '/search-knowledge/video-search'
      preLoaderRoute: typeof AppSearchKnowledgeVideoSearchRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/voice-search': {
      id: '/_app/search-knowledge/voice-search'
      path: '/voice-search'
      fullPath: '/search-knowledge/voice-search'
      preLoaderRoute: typeof AppSearchKnowledgeVoiceSearchRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/seo-analyzer/': {
      id: '/_app/seo-analyzer/'
      path: '/seo-analyzer'
      fullPath: '/seo-analyzer/'
      preLoaderRoute: typeof AppSeoAnalyzerIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking/': {
      id: '/_app/tracking/'
      path: '/tracking'
      fullPath: '/tracking/'
      preLoaderRoute: typeof AppTrackingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking/activity-logs': {
      id: '/_app/tracking/activity-logs'
      path: '/tracking/activity-logs'
      fullPath: '/tracking/activity-logs'
      preLoaderRoute: typeof AppTrackingActivityLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking/approvals': {
      id: '/_app/tracking/approvals'
      path: '/tracking/approvals'
      fullPath: '/tracking/approvals'
      preLoaderRoute: typeof AppTrackingApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking/business-goals': {
      id: '/_app/tracking/business-goals'
      path: '/tracking/business-goals'
      fullPath: '/tracking/business-goals'
      preLoaderRoute: typeof AppTrackingBusinessGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking/configuration': {
      id: '/_app/tracking/configuration'
      path: '/tracking/configuration'
      fullPath: '/tracking/configuration'
      preLoaderRoute: typeof AppTrackingConfigurationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking/consent': {
      id: '/_app/tracking/consent'
      path: '/tracking/consent'
      fullPath: '/tracking/consent'
      preLoaderRoute: typeof AppTrackingConsentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking/contact-forms': {
      id: '/_app/tracking/contact-forms'
      path: '/tracking/contact-forms'
      fullPath: '/tracking/contact-forms'
      preLoaderRoute: typeof AppTrackingContactFormsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking/conversion-strategy': {
      id: '/_app/tracking/conversion-strategy'
      path: '/tracking/conversion-strategy'
      fullPath: '/tracking/conversion-strategy'
      preLoaderRoute: typeof AppTrackingConversionStrategyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking/events': {
      id: '/_app/tracking/events'
      path: '/tracking/events'
      fullPath: '/tracking/events'
      preLoaderRoute: typeof AppTrackingEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking/kpi-management': {
      id: '/_app/tracking/kpi-management'
      path: '/tracking/kpi-management'
      fullPath: '/tracking/kpi-management'
      preLoaderRoute: typeof AppTrackingKpiManagementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking/measurement-plan': {
      id: '/_app/tracking/measurement-plan'
      path: '/tracking/measurement-plan'
      fullPath: '/tracking/measurement-plan'
      preLoaderRoute: typeof AppTrackingMeasurementPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking/operations': {
      id: '/_app/tracking/operations'
      path: '/tracking/operations'
      fullPath: '/tracking/operations'
      preLoaderRoute: typeof AppTrackingOperationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking/routing': {
      id: '/_app/tracking/routing'
      path: '/tracking/routing'
      fullPath: '/tracking/routing'
      preLoaderRoute: typeof AppTrackingRoutingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking/settings': {
      id: '/_app/tracking/settings'
      path: '/tracking/settings'
      fullPath: '/tracking/settings'
      preLoaderRoute: typeof AppTrackingSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking/spam-protection': {
      id: '/_app/tracking/spam-protection'
      path: '/tracking/spam-protection'
      fullPath: '/tracking/spam-protection'
      preLoaderRoute: typeof AppTrackingSpamProtectionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking/testing': {
      id: '/_app/tracking/testing'
      path: '/tracking/testing'
      fullPath: '/tracking/testing'
      preLoaderRoute: typeof AppTrackingTestingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/website-foundation/': {
      id: '/_app/website-foundation/'
      path: '/'
      fullPath: '/website-foundation/'
      preLoaderRoute: typeof AppWebsiteFoundationIndexRouteImport
      parentRoute: typeof AppWebsiteFoundationRoute
    }
    '/_app/website-foundation/approvals': {
      id: '/_app/website-foundation/approvals'
      path: '/approvals'
      fullPath: '/website-foundation/approvals'
      preLoaderRoute: typeof AppWebsiteFoundationApprovalsRouteImport
      parentRoute: typeof AppWebsiteFoundationRoute
    }
    '/_app/website-foundation/audit': {
      id: '/_app/website-foundation/audit'
      path: '/audit'
      fullPath: '/website-foundation/audit'
      preLoaderRoute: typeof AppWebsiteFoundationAuditRouteImport
      parentRoute: typeof AppWebsiteFoundationRoute
    }
    '/_app/website-foundation/automation': {
      id: '/_app/website-foundation/automation'
      path: '/automation'
      fullPath: '/website-foundation/automation'
      preLoaderRoute: typeof AppWebsiteFoundationAutomationRouteImport
      parentRoute: typeof AppWebsiteFoundationRoute
    }
    '/_app/website-foundation/backlog': {
      id: '/_app/website-foundation/backlog'
      path: '/backlog'
      fullPath: '/website-foundation/backlog'
      preLoaderRoute: typeof AppWebsiteFoundationBacklogRouteImport
      parentRoute: typeof AppWebsiteFoundationRoute
    }
    '/_app/website-foundation/brand': {
      id: '/_app/website-foundation/brand'
      path: '/brand'
      fullPath: '/website-foundation/brand'
      preLoaderRoute: typeof AppWebsiteFoundationBrandRouteImport
      parentRoute: typeof AppWebsiteFoundationRoute
    }
    '/_app/website-foundation/deployments': {
      id: '/_app/website-foundation/deployments'
      path: '/deployments'
      fullPath: '/website-foundation/deployments'
      preLoaderRoute: typeof AppWebsiteFoundationDeploymentsRouteImport
      parentRoute: typeof AppWebsiteFoundationRoute
    }
    '/_app/website-foundation/forms': {
      id: '/_app/website-foundation/forms'
      path: '/forms'
      fullPath: '/website-foundation/forms'
      preLoaderRoute: typeof AppWebsiteFoundationFormsRouteImport
      parentRoute: typeof AppWebsiteFoundationRoute
    }
    '/_app/website-foundation/inventory': {
      id: '/_app/website-foundation/inventory'
      path: '/inventory'
      fullPath: '/website-foundation/inventory'
      preLoaderRoute: typeof AppWebsiteFoundationInventoryRouteImport
      parentRoute: typeof AppWebsiteFoundationRoute
    }
    '/_app/website-foundation/logs': {
      id: '/_app/website-foundation/logs'
      path: '/logs'
      fullPath: '/website-foundation/logs'
      preLoaderRoute: typeof AppWebsiteFoundationLogsRouteImport
      parentRoute: typeof AppWebsiteFoundationRoute
    }
    '/_app/website-foundation/overview': {
      id: '/_app/website-foundation/overview'
      path: '/overview'
      fullPath: '/website-foundation/overview'
      preLoaderRoute: typeof AppWebsiteFoundationOverviewRouteImport
      parentRoute: typeof AppWebsiteFoundationRoute
    }
    '/_app/website-foundation/performance': {
      id: '/_app/website-foundation/performance'
      path: '/performance'
      fullPath: '/website-foundation/performance'
      preLoaderRoute: typeof AppWebsiteFoundationPerformanceRouteImport
      parentRoute: typeof AppWebsiteFoundationRoute
    }
    '/_app/website-foundation/plugins': {
      id: '/_app/website-foundation/plugins'
      path: '/plugins'
      fullPath: '/website-foundation/plugins'
      preLoaderRoute: typeof AppWebsiteFoundationPluginsRouteImport
      parentRoute: typeof AppWebsiteFoundationRoute
    }
    '/_app/website-foundation/responsive': {
      id: '/_app/website-foundation/responsive'
      path: '/responsive'
      fullPath: '/website-foundation/responsive'
      preLoaderRoute: typeof AppWebsiteFoundationResponsiveRouteImport
      parentRoute: typeof AppWebsiteFoundationRoute
    }
    '/_app/website-foundation/rollback': {
      id: '/_app/website-foundation/rollback'
      path: '/rollback'
      fullPath: '/website-foundation/rollback'
      preLoaderRoute: typeof AppWebsiteFoundationRollbackRouteImport
      parentRoute: typeof AppWebsiteFoundationRoute
    }
    '/_app/website-foundation/themes': {
      id: '/_app/website-foundation/themes'
      path: '/themes'
      fullPath: '/website-foundation/themes'
      preLoaderRoute: typeof AppWebsiteFoundationThemesRouteImport
      parentRoute: typeof AppWebsiteFoundationRoute
    }
    '/_app/website-foundation/wizard': {
      id: '/_app/website-foundation/wizard'
      path: '/wizard'
      fullPath: '/website-foundation/wizard'
      preLoaderRoute: typeof AppWebsiteFoundationWizardRouteImport
      parentRoute: typeof AppWebsiteFoundationRoute
    }
    '/_app/website-foundation/wordpress': {
      id: '/_app/website-foundation/wordpress'
      path: '/wordpress'
      fullPath: '/website-foundation/wordpress'
      preLoaderRoute: typeof AppWebsiteFoundationWordpressRouteImport
      parentRoute: typeof AppWebsiteFoundationRoute
    }
  }
}

interface AppSearchConsoleRouteChildren {
  AppSearchConsoleAmpRoute: typeof AppSearchConsoleAmpRoute
  AppSearchConsoleCountriesRoute: typeof AppSearchConsoleCountriesRoute
  AppSearchConsoleCoverageRoute: typeof AppSearchConsoleCoverageRoute
  AppSearchConsoleCwvRoute: typeof AppSearchConsoleCwvRoute
  AppSearchConsoleDevicesRoute: typeof AppSearchConsoleDevicesRoute
  AppSearchConsoleLinksRoute: typeof AppSearchConsoleLinksRoute
  AppSearchConsoleManualActionsRoute: typeof AppSearchConsoleManualActionsRoute
  AppSearchConsoleMobileUsabilityRoute: typeof AppSearchConsoleMobileUsabilityRoute
  AppSearchConsolePagesRoute: typeof AppSearchConsolePagesRoute
  AppSearchConsolePerformanceRoute: typeof AppSearchConsolePerformanceRoute
  AppSearchConsolePropertyDetailsRoute: typeof AppSearchConsolePropertyDetailsRoute
  AppSearchConsoleQueriesRoute: typeof AppSearchConsoleQueriesRoute
  AppSearchConsoleSitemapsRoute: typeof AppSearchConsoleSitemapsRoute
  AppSearchConsoleUrlInspectionRoute: typeof AppSearchConsoleUrlInspectionRoute
  AppSearchConsoleVerificationRoute: typeof AppSearchConsoleVerificationRoute
  AppSearchConsoleIndexRoute: typeof AppSearchConsoleIndexRoute
}

const AppSearchConsoleRouteChildren: AppSearchConsoleRouteChildren = {
  AppSearchConsoleAmpRoute: AppSearchConsoleAmpRoute,
  AppSearchConsoleCountriesRoute: AppSearchConsoleCountriesRoute,
  AppSearchConsoleCoverageRoute: AppSearchConsoleCoverageRoute,
  AppSearchConsoleCwvRoute: AppSearchConsoleCwvRoute,
  AppSearchConsoleDevicesRoute: AppSearchConsoleDevicesRoute,
  AppSearchConsoleLinksRoute: AppSearchConsoleLinksRoute,
  AppSearchConsoleManualActionsRoute: AppSearchConsoleManualActionsRoute,
  AppSearchConsoleMobileUsabilityRoute: AppSearchConsoleMobileUsabilityRoute,
  AppSearchConsolePagesRoute: AppSearchConsolePagesRoute,
  AppSearchConsolePerformanceRoute: AppSearchConsolePerformanceRoute,
  AppSearchConsolePropertyDetailsRoute: AppSearchConsolePropertyDetailsRoute,
  AppSearchConsoleQueriesRoute: AppSearchConsoleQueriesRoute,
  AppSearchConsoleSitemapsRoute: AppSearchConsoleSitemapsRoute,
  AppSearchConsoleUrlInspectionRoute: AppSearchConsoleUrlInspectionRoute,
  AppSearchConsoleVerificationRoute: AppSearchConsoleVerificationRoute,
  AppSearchConsoleIndexRoute: AppSearchConsoleIndexRoute,
}

const AppSearchConsoleRouteWithChildren =
  AppSearchConsoleRoute._addFileChildren(AppSearchConsoleRouteChildren)

interface AppSearchKnowledgeRouteChildren {
  AppSearchKnowledgeActivityLogsRoute: typeof AppSearchKnowledgeActivityLogsRoute
  AppSearchKnowledgeAiSearchOverviewRoute: typeof AppSearchKnowledgeAiSearchOverviewRoute
  AppSearchKnowledgeApprovalsRoute: typeof AppSearchKnowledgeApprovalsRoute
  AppSearchKnowledgeDeviceBehaviourRoute: typeof AppSearchKnowledgeDeviceBehaviourRoute
  AppSearchKnowledgeFeaturedSnippetsRoute: typeof AppSearchKnowledgeFeaturedSnippetsRoute
  AppSearchKnowledgeFutureTrendsRoute: typeof AppSearchKnowledgeFutureTrendsRoute
  AppSearchKnowledgeGoogleAlgorithmUpdatesRoute: typeof AppSearchKnowledgeGoogleAlgorithmUpdatesRoute
  AppSearchKnowledgeGoogleRankingFactorsRoute: typeof AppSearchKnowledgeGoogleRankingFactorsRoute
  AppSearchKnowledgeGoogleSearchArchitectureRoute: typeof AppSearchKnowledgeGoogleSearchArchitectureRoute
  AppSearchKnowledgeImageSearchRoute: typeof AppSearchKnowledgeImageSearchRoute
  AppSearchKnowledgeKnowledgeGraphRoute: typeof AppSearchKnowledgeKnowledgeGraphRoute
  AppSearchKnowledgeKnowledgeRulesRoute: typeof AppSearchKnowledgeKnowledgeRulesRoute
  AppSearchKnowledgeLocalSearchRoute: typeof AppSearchKnowledgeLocalSearchRoute
  AppSearchKnowledgeMarketAnalysisRoute: typeof AppSearchKnowledgeMarketAnalysisRoute
  AppSearchKnowledgeNewsSearchRoute: typeof AppSearchKnowledgeNewsSearchRoute
  AppSearchKnowledgePeopleAlsoAskRoute: typeof AppSearchKnowledgePeopleAlsoAskRoute
  AppSearchKnowledgeRichResultsRoute: typeof AppSearchKnowledgeRichResultsRoute
  AppSearchKnowledgeSearchIntentRoute: typeof AppSearchKnowledgeSearchIntentRoute
  AppSearchKnowledgeSearchOperatorsRoute: typeof AppSearchKnowledgeSearchOperatorsRoute
  AppSearchKnowledgeSerpFeaturesRoute: typeof AppSearchKnowledgeSerpFeaturesRoute
  AppSearchKnowledgeSerpLayoutRoute: typeof AppSearchKnowledgeSerpLayoutRoute
  AppSearchKnowledgeSettingsRoute: typeof AppSearchKnowledgeSettingsRoute
  AppSearchKnowledgeShoppingSearchRoute: typeof AppSearchKnowledgeShoppingSearchRoute
  AppSearchKnowledgeVersionHistoryRoute: typeof AppSearchKnowledgeVersionHistoryRoute
  AppSearchKnowledgeVideoSearchRoute: typeof AppSearchKnowledgeVideoSearchRoute
  AppSearchKnowledgeVoiceSearchRoute: typeof AppSearchKnowledgeVoiceSearchRoute
  AppSearchKnowledgeIndexRoute: typeof AppSearchKnowledgeIndexRoute
}

const AppSearchKnowledgeRouteChildren: AppSearchKnowledgeRouteChildren = {
  AppSearchKnowledgeActivityLogsRoute: AppSearchKnowledgeActivityLogsRoute,
  AppSearchKnowledgeAiSearchOverviewRoute:
    AppSearchKnowledgeAiSearchOverviewRoute,
  AppSearchKnowledgeApprovalsRoute: AppSearchKnowledgeApprovalsRoute,
  AppSearchKnowledgeDeviceBehaviourRoute:
    AppSearchKnowledgeDeviceBehaviourRoute,
  AppSearchKnowledgeFeaturedSnippetsRoute:
    AppSearchKnowledgeFeaturedSnippetsRoute,
  AppSearchKnowledgeFutureTrendsRoute: AppSearchKnowledgeFutureTrendsRoute,
  AppSearchKnowledgeGoogleAlgorithmUpdatesRoute:
    AppSearchKnowledgeGoogleAlgorithmUpdatesRoute,
  AppSearchKnowledgeGoogleRankingFactorsRoute:
    AppSearchKnowledgeGoogleRankingFactorsRoute,
  AppSearchKnowledgeGoogleSearchArchitectureRoute:
    AppSearchKnowledgeGoogleSearchArchitectureRoute,
  AppSearchKnowledgeImageSearchRoute: AppSearchKnowledgeImageSearchRoute,
  AppSearchKnowledgeKnowledgeGraphRoute: AppSearchKnowledgeKnowledgeGraphRoute,
  AppSearchKnowledgeKnowledgeRulesRoute: AppSearchKnowledgeKnowledgeRulesRoute,
  AppSearchKnowledgeLocalSearchRoute: AppSearchKnowledgeLocalSearchRoute,
  AppSearchKnowledgeMarketAnalysisRoute: AppSearchKnowledgeMarketAnalysisRoute,
  AppSearchKnowledgeNewsSearchRoute: AppSearchKnowledgeNewsSearchRoute,
  AppSearchKnowledgePeopleAlsoAskRoute: AppSearchKnowledgePeopleAlsoAskRoute,
  AppSearchKnowledgeRichResultsRoute: AppSearchKnowledgeRichResultsRoute,
  AppSearchKnowledgeSearchIntentRoute: AppSearchKnowledgeSearchIntentRoute,
  AppSearchKnowledgeSearchOperatorsRoute:
    AppSearchKnowledgeSearchOperatorsRoute,
  AppSearchKnowledgeSerpFeaturesRoute: AppSearchKnowledgeSerpFeaturesRoute,
  AppSearchKnowledgeSerpLayoutRoute: AppSearchKnowledgeSerpLayoutRoute,
  AppSearchKnowledgeSettingsRoute: AppSearchKnowledgeSettingsRoute,
  AppSearchKnowledgeShoppingSearchRoute: AppSearchKnowledgeShoppingSearchRoute,
  AppSearchKnowledgeVersionHistoryRoute: AppSearchKnowledgeVersionHistoryRoute,
  AppSearchKnowledgeVideoSearchRoute: AppSearchKnowledgeVideoSearchRoute,
  AppSearchKnowledgeVoiceSearchRoute: AppSearchKnowledgeVoiceSearchRoute,
  AppSearchKnowledgeIndexRoute: AppSearchKnowledgeIndexRoute,
}

const AppSearchKnowledgeRouteWithChildren =
  AppSearchKnowledgeRoute._addFileChildren(AppSearchKnowledgeRouteChildren)

interface AppWebsiteFoundationRouteChildren {
  AppWebsiteFoundationApprovalsRoute: typeof AppWebsiteFoundationApprovalsRoute
  AppWebsiteFoundationAuditRoute: typeof AppWebsiteFoundationAuditRoute
  AppWebsiteFoundationAutomationRoute: typeof AppWebsiteFoundationAutomationRoute
  AppWebsiteFoundationBacklogRoute: typeof AppWebsiteFoundationBacklogRoute
  AppWebsiteFoundationBrandRoute: typeof AppWebsiteFoundationBrandRoute
  AppWebsiteFoundationDeploymentsRoute: typeof AppWebsiteFoundationDeploymentsRoute
  AppWebsiteFoundationFormsRoute: typeof AppWebsiteFoundationFormsRoute
  AppWebsiteFoundationInventoryRoute: typeof AppWebsiteFoundationInventoryRoute
  AppWebsiteFoundationLogsRoute: typeof AppWebsiteFoundationLogsRoute
  AppWebsiteFoundationOverviewRoute: typeof AppWebsiteFoundationOverviewRoute
  AppWebsiteFoundationPerformanceRoute: typeof AppWebsiteFoundationPerformanceRoute
  AppWebsiteFoundationPluginsRoute: typeof AppWebsiteFoundationPluginsRoute
  AppWebsiteFoundationResponsiveRoute: typeof AppWebsiteFoundationResponsiveRoute
  AppWebsiteFoundationRollbackRoute: typeof AppWebsiteFoundationRollbackRoute
  AppWebsiteFoundationThemesRoute: typeof AppWebsiteFoundationThemesRoute
  AppWebsiteFoundationWizardRoute: typeof AppWebsiteFoundationWizardRoute
  AppWebsiteFoundationWordpressRoute: typeof AppWebsiteFoundationWordpressRoute
  AppWebsiteFoundationIndexRoute: typeof AppWebsiteFoundationIndexRoute
}

const AppWebsiteFoundationRouteChildren: AppWebsiteFoundationRouteChildren = {
  AppWebsiteFoundationApprovalsRoute: AppWebsiteFoundationApprovalsRoute,
  AppWebsiteFoundationAuditRoute: AppWebsiteFoundationAuditRoute,
  AppWebsiteFoundationAutomationRoute: AppWebsiteFoundationAutomationRoute,
  AppWebsiteFoundationBacklogRoute: AppWebsiteFoundationBacklogRoute,
  AppWebsiteFoundationBrandRoute: AppWebsiteFoundationBrandRoute,
  AppWebsiteFoundationDeploymentsRoute: AppWebsiteFoundationDeploymentsRoute,
  AppWebsiteFoundationFormsRoute: AppWebsiteFoundationFormsRoute,
  AppWebsiteFoundationInventoryRoute: AppWebsiteFoundationInventoryRoute,
  AppWebsiteFoundationLogsRoute: AppWebsiteFoundationLogsRoute,
  AppWebsiteFoundationOverviewRoute: AppWebsiteFoundationOverviewRoute,
  AppWebsiteFoundationPerformanceRoute: AppWebsiteFoundationPerformanceRoute,
  AppWebsiteFoundationPluginsRoute: AppWebsiteFoundationPluginsRoute,
  AppWebsiteFoundationResponsiveRoute: AppWebsiteFoundationResponsiveRoute,
  AppWebsiteFoundationRollbackRoute: AppWebsiteFoundationRollbackRoute,
  AppWebsiteFoundationThemesRoute: AppWebsiteFoundationThemesRoute,
  AppWebsiteFoundationWizardRoute: AppWebsiteFoundationWizardRoute,
  AppWebsiteFoundationWordpressRoute: AppWebsiteFoundationWordpressRoute,
  AppWebsiteFoundationIndexRoute: AppWebsiteFoundationIndexRoute,
}

const AppWebsiteFoundationRouteWithChildren =
  AppWebsiteFoundationRoute._addFileChildren(AppWebsiteFoundationRouteChildren)

interface AppRouteChildren {
  AppSearchConsoleRoute: typeof AppSearchConsoleRouteWithChildren
  AppSearchKnowledgeRoute: typeof AppSearchKnowledgeRouteWithChildren
  AppWebsiteFoundationRoute: typeof AppWebsiteFoundationRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppTrackingActivityLogsRoute: typeof AppTrackingActivityLogsRoute
  AppTrackingApprovalsRoute: typeof AppTrackingApprovalsRoute
  AppTrackingBusinessGoalsRoute: typeof AppTrackingBusinessGoalsRoute
  AppTrackingConfigurationRoute: typeof AppTrackingConfigurationRoute
  AppTrackingConsentRoute: typeof AppTrackingConsentRoute
  AppTrackingContactFormsRoute: typeof AppTrackingContactFormsRoute
  AppTrackingConversionStrategyRoute: typeof AppTrackingConversionStrategyRoute
  AppTrackingEventsRoute: typeof AppTrackingEventsRoute
  AppTrackingKpiManagementRoute: typeof AppTrackingKpiManagementRoute
  AppTrackingMeasurementPlanRoute: typeof AppTrackingMeasurementPlanRoute
  AppTrackingOperationsRoute: typeof AppTrackingOperationsRoute
  AppTrackingRoutingRoute: typeof AppTrackingRoutingRoute
  AppTrackingSettingsRoute: typeof AppTrackingSettingsRoute
  AppTrackingSpamProtectionRoute: typeof AppTrackingSpamProtectionRoute
  AppTrackingTestingRoute: typeof AppTrackingTestingRoute
  AppBusinessProfileIndexRoute: typeof AppBusinessProfileIndexRoute
  AppCompetitorsIndexRoute: typeof AppCompetitorsIndexRoute
  AppGoogleProductsIndexRoute: typeof AppGoogleProductsIndexRoute
  AppKeywordsIndexRoute: typeof AppKeywordsIndexRoute
  AppMobileIndexRoute: typeof AppMobileIndexRoute
  AppPerformanceIndexRoute: typeof AppPerformanceIndexRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
  AppSeoAnalyzerIndexRoute: typeof AppSeoAnalyzerIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppTrackingIndexRoute: typeof AppTrackingIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSearchConsoleRoute: AppSearchConsoleRouteWithChildren,
  AppSearchKnowledgeRoute: AppSearchKnowledgeRouteWithChildren,
  AppWebsiteFoundationRoute: AppWebsiteFoundationRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppTrackingActivityLogsRoute: AppTrackingActivityLogsRoute,
  AppTrackingApprovalsRoute: AppTrackingApprovalsRoute,
  AppTrackingBusinessGoalsRoute: AppTrackingBusinessGoalsRoute,
  AppTrackingConfigurationRoute: AppTrackingConfigurationRoute,
  AppTrackingConsentRoute: AppTrackingConsentRoute,
  AppTrackingContactFormsRoute: AppTrackingContactFormsRoute,
  AppTrackingConversionStrategyRoute: AppTrackingConversionStrategyRoute,
  AppTrackingEventsRoute: AppTrackingEventsRoute,
  AppTrackingKpiManagementRoute: AppTrackingKpiManagementRoute,
  AppTrackingMeasurementPlanRoute: AppTrackingMeasurementPlanRoute,
  AppTrackingOperationsRoute: AppTrackingOperationsRoute,
  AppTrackingRoutingRoute: AppTrackingRoutingRoute,
  AppTrackingSettingsRoute: AppTrackingSettingsRoute,
  AppTrackingSpamProtectionRoute: AppTrackingSpamProtectionRoute,
  AppTrackingTestingRoute: AppTrackingTestingRoute,
  AppBusinessProfileIndexRoute: AppBusinessProfileIndexRoute,
  AppCompetitorsIndexRoute: AppCompetitorsIndexRoute,
  AppGoogleProductsIndexRoute: AppGoogleProductsIndexRoute,
  AppKeywordsIndexRoute: AppKeywordsIndexRoute,
  AppMobileIndexRoute: AppMobileIndexRoute,
  AppPerformanceIndexRoute: AppPerformanceIndexRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
  AppSeoAnalyzerIndexRoute: AppSeoAnalyzerIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppTrackingIndexRoute: AppTrackingIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
