/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSearchConsoleRouteImport } from './routes/_app/search-console'
import { Route as AppSearchKnowledgeRouteImport } from './routes/_app/search-knowledge'
import { Route as AppWebsiteFoundationRouteImport } from './routes/_app/website-foundation'
import { Route as AppAuditIndexRouteImport } from './routes/_app/audit/index'
import { Route as AppBusinessKeywordCompetitorIndexRouteImport } from './routes/_app/business-keyword-competitor/index'
import { Route as AppBusinessProfileIndexRouteImport } from './routes/_app/business-profile/index'
import { Route as AppBusinessIndexRouteImport } from './routes/_app/business/index'
import { Route as AppCompetitorsIndexRouteImport } from './routes/_app/competitors/index'
import { Route as AppFoundationIndexRouteImport } from './routes/_app/foundation/index'
import { Route as AppGoogleProductsIndexRouteImport } from './routes/_app/google-products/index'
import { Route as AppKeywordsIndexRouteImport } from './routes/_app/keywords/index'
import { Route as AppMobileIndexRouteImport } from './routes/_app/mobile/index'
import { Route as AppOnpageSeoIndexRouteImport } from './routes/_app/onpage-seo/index'
import { Route as AppPerformanceIndexRouteImport } from './routes/_app/performance/index'
import { Route as AppReportsIndexRouteImport } from './routes/_app/reports/index'
import { Route as AppSearchConsoleIndexRouteImport } from './routes/_app/search-console/index'
import { Route as AppSearchConsoleAmpRouteImport } from './routes/_app/search-console/amp'
import { Route as AppSearchConsoleCountriesRouteImport } from './routes/_app/search-console/countries'
import { Route as AppSearchConsoleCoverageRouteImport } from './routes/_app/search-console/coverage'
import { Route as AppSearchConsoleCwvRouteImport } from './routes/_app/search-console/cwv'
import { Route as AppSearchConsoleDevicesRouteImport } from './routes/_app/search-console/devices'
import { Route as AppSearchConsoleLinksRouteImport } from './routes/_app/search-console/links'
import { Route as AppSearchConsoleManualActionsRouteImport } from './routes/_app/search-console/manual-actions'
import { Route as AppSearchConsoleMobileUsabilityRouteImport } from './routes/_app/search-console/mobile-usability'
import { Route as AppSearchConsolePagesRouteImport } from './routes/_app/search-console/pages'
import { Route as AppSearchConsolePerformanceRouteImport } from './routes/_app/search-console/performance'
import { Route as AppSearchConsolePropertyDetailsRouteImport } from './routes/_app/search-console/property-details'
import { Route as AppSearchConsoleQueriesRouteImport } from './routes/_app/search-console/queries'
import { Route as AppSearchConsoleSitemapsRouteImport } from './routes/_app/search-console/sitemaps'
import { Route as AppSearchConsoleUrlInspectionRouteImport } from './routes/_app/search-console/url-inspection'
import { Route as AppSearchConsoleVerificationRouteImport } from './routes/_app/search-console/verification'
import { Route as AppSearchKnowledgeIndexRouteImport } from './routes/_app/search-knowledge/index'
import { Route as AppSearchKnowledgeAlgorithmUpdatesRouteImport } from './routes/_app/search-knowledge/algorithm-updates'
import { Route as AppSearchKnowledgeDocumentationRouteImport } from './routes/_app/search-knowledge/documentation'
import { Route as AppSearchKnowledgeKnowledgeBaseRouteImport } from './routes/_app/search-knowledge/knowledge-base'
import { Route as AppSearchKnowledgeSearchOperatorsRouteImport } from './routes/_app/search-knowledge/search-operators'
import { Route as AppSearchKnowledgeSerpFeaturesRouteImport } from './routes/_app/search-knowledge/serp-features'
import { Route as AppSearchKnowledgeSyncLogsRouteImport } from './routes/_app/search-knowledge/sync-logs'
import { Route as AppSearchKnowledgeVersionsRouteImport } from './routes/_app/search-knowledge/versions'
import { Route as AppSeoAnalyzerIndexRouteImport } from './routes/_app/seo-analyzer/index'
import { Route as AppSeoIndexRouteImport } from './routes/_app/seo/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppTrackingFoundationIndexRouteImport } from './routes/_app/tracking-foundation/index'
import { Route as AppTrackingFoundationAuditRouteImport } from './routes/_app/tracking-foundation/audit'
import { Route as AppTrackingFoundationConsentRouteImport } from './routes/_app/tracking-foundation/consent'
import { Route as AppTrackingFoundationEventsRouteImport } from './routes/_app/tracking-foundation/events'
import { Route as AppTrackingFoundationFormsRouteImport } from './routes/_app/tracking-foundation/forms'
import { Route as AppTrackingFoundationMeasurementPlanRouteImport } from './routes/_app/tracking-foundation/measurement-plan'
import { Route as AppTrackingFoundationRoutingRouteImport } from './routes/_app/tracking-foundation/routing'
import { Route as AppTrackingFoundationSubmissionsRouteImport } from './routes/_app/tracking-foundation/submissions'
import { Route as AppTrackingFoundationTrackingRouteImport } from './routes/_app/tracking-foundation/tracking'
import { Route as AppTrackingFoundationValidationRouteImport } from './routes/_app/tracking-foundation/validation'
import { Route as AppTrackingFoundationVerificationRouteImport } from './routes/_app/tracking-foundation/verification'
import { Route as AppTrackingIndexRouteImport } from './routes/_app/tracking/index'
import { Route as AppTrackingActivityLogsRouteImport } from './routes/_app/tracking/activity-logs'
import { Route as AppTrackingApprovalsRouteImport } from './routes/_app/tracking/approvals'
import { Route as AppTrackingAuditLogsRouteImport } from './routes/_app/tracking/audit-logs'
import { Route as AppTrackingBusinessGoalsRouteImport } from './routes/_app/tracking/business-goals'
import { Route as AppTrackingConfigurationRouteImport } from './routes/_app/tracking/configuration'
import { Route as AppTrackingConsentRouteImport } from './routes/_app/tracking/consent'
import { Route as AppTrackingContactFormsRouteImport } from './routes/_app/tracking/contact-forms'
import { Route as AppTrackingConversionStrategyRouteImport } from './routes/_app/tracking/conversion-strategy'
import { Route as AppTrackingDeliveryLogsRouteImport } from './routes/_app/tracking/delivery-logs'
import { Route as AppTrackingEventsRouteImport } from './routes/_app/tracking/events'
import { Route as AppTrackingFormBuilderRouteImport } from './routes/_app/tracking/form-builder'
import { Route as AppTrackingKpiManagementRouteImport } from './routes/_app/tracking/kpi-management'
import { Route as AppTrackingMeasurementPlanRouteImport } from './routes/_app/tracking/measurement-plan'
import { Route as AppTrackingOperationsRouteImport } from './routes/_app/tracking/operations'
import { Route as AppTrackingProvidersRouteImport } from './routes/_app/tracking/providers'
import { Route as AppTrackingRetryLogsRouteImport } from './routes/_app/tracking/retry-logs'
import { Route as AppTrackingRoutingRouteImport } from './routes/_app/tracking/routing'
import { Route as AppTrackingSettingsRouteImport } from './routes/_app/tracking/settings'
import { Route as AppTrackingSpamProtectionRouteImport } from './routes/_app/tracking/spam-protection'
import { Route as AppTrackingSubmissionsRouteImport } from './routes/_app/tracking/submissions'
import { Route as AppTrackingTestingRouteImport } from './routes/_app/tracking/testing'
import { Route as AppTrackingVerificationRouteImport } from './routes/_app/tracking/verification'
import { Route as AppWebsiteFoundationIndexRouteImport } from './routes/_app/website-foundation/index'
import { Route as AppWebsiteFoundationBrandRouteImport } from './routes/_app/website-foundation/brand'
import { Route as AppWebsiteFoundationFormsRouteImport } from './routes/_app/website-foundation/forms'
import { Route as AppWebsiteFoundationInventoryRouteImport } from './routes/_app/website-foundation/inventory'
import { Route as AppWebsiteFoundationOverviewRouteImport } from './routes/_app/website-foundation/overview'
import { Route as AppWebsiteFoundationPerformanceRouteImport } from './routes/_app/website-foundation/performance'
import { Route as AppWebsiteFoundationPluginsRouteImport } from './routes/_app/website-foundation/plugins'
import { Route as AppWebsiteFoundationResponsiveRouteImport } from './routes/_app/website-foundation/responsive'
import { Route as AppWebsiteFoundationSslRouteImport } from './routes/_app/website-foundation/ssl'
import { Route as AppWebsiteFoundationThemesRouteImport } from './routes/_app/website-foundation/themes'
import { Route as AppWebsiteFoundationWizardRouteImport } from './routes/_app/website-foundation/wizard'
import { Route as AppWebsiteFoundationWordpressRouteImport } from './routes/_app/website-foundation/wordpress'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchConsoleRoute = AppSearchConsoleRouteImport.update({
  id: '/search-console',
  path: '/search-console',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchKnowledgeRoute = AppSearchKnowledgeRouteImport.update({
  id: '/search-knowledge',
  path: '/search-knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppWebsiteFoundationRoute = AppWebsiteFoundationRouteImport.update({
  id: '/website-foundation',
  path: '/website-foundation',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditIndexRoute = AppAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => AppRoute,
} as any)
const AppBusinessKeywordCompetitorIndexRoute =
  AppBusinessKeywordCompetitorIndexRouteImport.update({
    id: '/business-keyword-competitor/',
    path: '/business-keyword-competitor/',
    getParentRoute: () => AppRoute,
  } as any)
const AppBusinessProfileIndexRoute = AppBusinessProfileIndexRouteImport.update({
  id: '/business-profile/',
  path: '/business-profile/',
  getParentRoute: () => AppRoute,
} as any)
const AppBusinessIndexRoute = AppBusinessIndexRouteImport.update({
  id: '/business/',
  path: '/business/',
  getParentRoute: () => AppRoute,
} as any)
const AppCompetitorsIndexRoute = AppCompetitorsIndexRouteImport.update({
  id: '/competitors/',
  path: '/competitors/',
  getParentRoute: () => AppRoute,
} as any)
const AppFoundationIndexRoute = AppFoundationIndexRouteImport.update({
  id: '/foundation/',
  path: '/foundation/',
  getParentRoute: () => AppRoute,
} as any)
const AppGoogleProductsIndexRoute = AppGoogleProductsIndexRouteImport.update({
  id: '/google-products/',
  path: '/google-products/',
  getParentRoute: () => AppRoute,
} as any)
const AppKeywordsIndexRoute = AppKeywordsIndexRouteImport.update({
  id: '/keywords/',
  path: '/keywords/',
  getParentRoute: () => AppRoute,
} as any)
const AppMobileIndexRoute = AppMobileIndexRouteImport.update({
  id: '/mobile/',
  path: '/mobile/',
  getParentRoute: () => AppRoute,
} as any)
const AppOnpageSeoIndexRoute = AppOnpageSeoIndexRouteImport.update({
  id: '/onpage-seo/',
  path: '/onpage-seo/',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceIndexRoute = AppPerformanceIndexRouteImport.update({
  id: '/performance/',
  path: '/performance/',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchConsoleIndexRoute = AppSearchConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSearchConsoleRoute,
} as any)
const AppSearchConsoleAmpRoute = AppSearchConsoleAmpRouteImport.update({
  id: '/amp',
  path: '/amp',
  getParentRoute: () => AppSearchConsoleRoute,
} as any)
const AppSearchConsoleCountriesRoute =
  AppSearchConsoleCountriesRouteImport.update({
    id: '/countries',
    path: '/countries',
    getParentRoute: () => AppSearchConsoleRoute,
  } as any)
const AppSearchConsoleCoverageRoute =
  AppSearchConsoleCoverageRouteImport.update({
    id: '/coverage',
    path: '/coverage',
    getParentRoute: () => AppSearchConsoleRoute,
  } as any)
const AppSearchConsoleCwvRoute = AppSearchConsoleCwvRouteImport.update({
  id: '/cwv',
  path: '/cwv',
  getParentRoute: () => AppSearchConsoleRoute,
} as any)
const AppSearchConsoleDevicesRoute = AppSearchConsoleDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AppSearchConsoleRoute,
} as any)
const AppSearchConsoleLinksRoute = AppSearchConsoleLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AppSearchConsoleRoute,
} as any)
const AppSearchConsoleManualActionsRoute =
  AppSearchConsoleManualActionsRouteImport.update({
    id: '/manual-actions',
    path: '/manual-actions',
    getParentRoute: () => AppSearchConsoleRoute,
  } as any)
const AppSearchConsoleMobileUsabilityRoute =
  AppSearchConsoleMobileUsabilityRouteImport.update({
    id: '/mobile-usability',
    path: '/mobile-usability',
    getParentRoute: () => AppSearchConsoleRoute,
  } as any)
const AppSearchConsolePagesRoute = AppSearchConsolePagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AppSearchConsoleRoute,
} as any)
const AppSearchConsolePerformanceRoute =
  AppSearchConsolePerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AppSearchConsoleRoute,
  } as any)
const AppSearchConsolePropertyDetailsRoute =
  AppSearchConsolePropertyDetailsRouteImport.update({
    id: '/property-details',
    path: '/property-details',
    getParentRoute: () => AppSearchConsoleRoute,
  } as any)
const AppSearchConsoleQueriesRoute = AppSearchConsoleQueriesRouteImport.update({
  id: '/queries',
  path: '/queries',
  getParentRoute: () => AppSearchConsoleRoute,
} as any)
const AppSearchConsoleSitemapsRoute =
  AppSearchConsoleSitemapsRouteImport.update({
    id: '/sitemaps',
    path: '/sitemaps',
    getParentRoute: () => AppSearchConsoleRoute,
  } as any)
const AppSearchConsoleUrlInspectionRoute =
  AppSearchConsoleUrlInspectionRouteImport.update({
    id: '/url-inspection',
    path: '/url-inspection',
    getParentRoute: () => AppSearchConsoleRoute,
  } as any)
const AppSearchConsoleVerificationRoute =
  AppSearchConsoleVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => AppSearchConsoleRoute,
  } as any)
const AppSearchKnowledgeIndexRoute = AppSearchKnowledgeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSearchKnowledgeRoute,
} as any)
const AppSearchKnowledgeAlgorithmUpdatesRoute =
  AppSearchKnowledgeAlgorithmUpdatesRouteImport.update({
    id: '/algorithm-updates',
    path: '/algorithm-updates',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgeDocumentationRoute =
  AppSearchKnowledgeDocumentationRouteImport.update({
    id: '/documentation',
    path: '/documentation',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgeKnowledgeBaseRoute =
  AppSearchKnowledgeKnowledgeBaseRouteImport.update({
    id: '/knowledge-base',
    path: '/knowledge-base',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgeSearchOperatorsRoute =
  AppSearchKnowledgeSearchOperatorsRouteImport.update({
    id: '/search-operators',
    path: '/search-operators',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgeSerpFeaturesRoute =
  AppSearchKnowledgeSerpFeaturesRouteImport.update({
    id: '/serp-features',
    path: '/serp-features',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgeSyncLogsRoute =
  AppSearchKnowledgeSyncLogsRouteImport.update({
    id: '/sync-logs',
    path: '/sync-logs',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgeVersionsRoute =
  AppSearchKnowledgeVersionsRouteImport.update({
    id: '/versions',
    path: '/versions',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSeoAnalyzerIndexRoute = AppSeoAnalyzerIndexRouteImport.update({
  id: '/seo-analyzer/',
  path: '/seo-analyzer/',
  getParentRoute: () => AppRoute,
} as any)
const AppSeoIndexRoute = AppSeoIndexRouteImport.update({
  id: '/seo/',
  path: '/seo/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackingFoundationIndexRoute =
  AppTrackingFoundationIndexRouteImport.update({
    id: '/tracking-foundation/',
    path: '/tracking-foundation/',
    getParentRoute: () => AppRoute,
  } as any)
const AppTrackingFoundationAuditRoute =
  AppTrackingFoundationAuditRouteImport.update({
    id: '/tracking-foundation/audit',
    path: '/tracking-foundation/audit',
    getParentRoute: () => AppRoute,
  } as any)
const AppTrackingFoundationConsentRoute =
  AppTrackingFoundationConsentRouteImport.update({
    id: '/tracking-foundation/consent',
    path: '/tracking-foundation/consent',
    getParentRoute: () => AppRoute,
  } as any)
const AppTrackingFoundationEventsRoute =
  AppTrackingFoundationEventsRouteImport.update({
    id: '/tracking-foundation/events',
    path: '/tracking-foundation/events',
    getParentRoute: () => AppRoute,
  } as any)
const AppTrackingFoundationFormsRoute =
  AppTrackingFoundationFormsRouteImport.update({
    id: '/tracking-foundation/forms',
    path: '/tracking-foundation/forms',
    getParentRoute: () => AppRoute,
  } as any)
const AppTrackingFoundationMeasurementPlanRoute =
  AppTrackingFoundationMeasurementPlanRouteImport.update({
    id: '/tracking-foundation/measurement-plan',
    path: '/tracking-foundation/measurement-plan',
    getParentRoute: () => AppRoute,
  } as any)
const AppTrackingFoundationRoutingRoute =
  AppTrackingFoundationRoutingRouteImport.update({
    id: '/tracking-foundation/routing',
    path: '/tracking-foundation/routing',
    getParentRoute: () => AppRoute,
  } as any)
const AppTrackingFoundationSubmissionsRoute =
  AppTrackingFoundationSubmissionsRouteImport.update({
    id: '/tracking-foundation/submissions',
    path: '/tracking-foundation/submissions',
    getParentRoute: () => AppRoute,
  } as any)
const AppTrackingFoundationTrackingRoute =
  AppTrackingFoundationTrackingRouteImport.update({
    id: '/tracking-foundation/tracking',
    path: '/tracking-foundation/tracking',
    getParentRoute: () => AppRoute,
  } as any)
const AppTrackingFoundationValidationRoute =
  AppTrackingFoundationValidationRouteImport.update({
    id: '/tracking-foundation/validation',
    path: '/tracking-foundation/validation',
    getParentRoute: () => AppRoute,
  } as any)
const AppTrackingFoundationVerificationRoute =
  AppTrackingFoundationVerificationRouteImport.update({
    id: '/tracking-foundation/verification',
    path: '/tracking-foundation/verification',
    getParentRoute: () => AppRoute,
  } as any)
const AppTrackingIndexRoute = AppTrackingIndexRouteImport.update({
  id: '/tracking/',
  path: '/tracking/',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackingActivityLogsRoute = AppTrackingActivityLogsRouteImport.update({
  id: '/tracking/activity-logs',
  path: '/tracking/activity-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackingApprovalsRoute = AppTrackingApprovalsRouteImport.update({
  id: '/tracking/approvals',
  path: '/tracking/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackingAuditLogsRoute = AppTrackingAuditLogsRouteImport.update({
  id: '/tracking/audit-logs',
  path: '/tracking/audit-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackingBusinessGoalsRoute =
  AppTrackingBusinessGoalsRouteImport.update({
    id: '/tracking/business-goals',
    path: '/tracking/business-goals',
    getParentRoute: () => AppRoute,
  } as any)
const AppTrackingConfigurationRoute =
  AppTrackingConfigurationRouteImport.update({
    id: '/tracking/configuration',
    path: '/tracking/configuration',
    getParentRoute: () => AppRoute,
  } as any)
const AppTrackingConsentRoute = AppTrackingConsentRouteImport.update({
  id: '/tracking/consent',
  path: '/tracking/consent',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackingContactFormsRoute = AppTrackingContactFormsRouteImport.update({
  id: '/tracking/contact-forms',
  path: '/tracking/contact-forms',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackingConversionStrategyRoute =
  AppTrackingConversionStrategyRouteImport.update({
    id: '/tracking/conversion-strategy',
    path: '/tracking/conversion-strategy',
    getParentRoute: () => AppRoute,
  } as any)
const AppTrackingDeliveryLogsRoute = AppTrackingDeliveryLogsRouteImport.update({
  id: '/tracking/delivery-logs',
  path: '/tracking/delivery-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackingEventsRoute = AppTrackingEventsRouteImport.update({
  id: '/tracking/events',
  path: '/tracking/events',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackingFormBuilderRoute = AppTrackingFormBuilderRouteImport.update({
  id: '/tracking/form-builder',
  path: '/tracking/form-builder',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackingKpiManagementRoute =
  AppTrackingKpiManagementRouteImport.update({
    id: '/tracking/kpi-management',
    path: '/tracking/kpi-management',
    getParentRoute: () => AppRoute,
  } as any)
const AppTrackingMeasurementPlanRoute =
  AppTrackingMeasurementPlanRouteImport.update({
    id: '/tracking/measurement-plan',
    path: '/tracking/measurement-plan',
    getParentRoute: () => AppRoute,
  } as any)
const AppTrackingOperationsRoute = AppTrackingOperationsRouteImport.update({
  id: '/tracking/operations',
  path: '/tracking/operations',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackingProvidersRoute = AppTrackingProvidersRouteImport.update({
  id: '/tracking/providers',
  path: '/tracking/providers',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackingRetryLogsRoute = AppTrackingRetryLogsRouteImport.update({
  id: '/tracking/retry-logs',
  path: '/tracking/retry-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackingRoutingRoute = AppTrackingRoutingRouteImport.update({
  id: '/tracking/routing',
  path: '/tracking/routing',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackingSettingsRoute = AppTrackingSettingsRouteImport.update({
  id: '/tracking/settings',
  path: '/tracking/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackingSpamProtectionRoute =
  AppTrackingSpamProtectionRouteImport.update({
    id: '/tracking/spam-protection',
    path: '/tracking/spam-protection',
    getParentRoute: () => AppRoute,
  } as any)
const AppTrackingSubmissionsRoute = AppTrackingSubmissionsRouteImport.update({
  id: '/tracking/submissions',
  path: '/tracking/submissions',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackingTestingRoute = AppTrackingTestingRouteImport.update({
  id: '/tracking/testing',
  path: '/tracking/testing',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackingVerificationRoute = AppTrackingVerificationRouteImport.update({
  id: '/tracking/verification',
  path: '/tracking/verification',
  getParentRoute: () => AppRoute,
} as any)
const AppWebsiteFoundationIndexRoute =
  AppWebsiteFoundationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppWebsiteFoundationRoute,
  } as any)
const AppWebsiteFoundationBrandRoute =
  AppWebsiteFoundationBrandRouteImport.update({
    id: '/brand',
    path: '/brand',
    getParentRoute: () => AppWebsiteFoundationRoute,
  } as any)
const AppWebsiteFoundationFormsRoute =
  AppWebsiteFoundationFormsRouteImport.update({
    id: '/forms',
    path: '/forms',
    getParentRoute: () => AppWebsiteFoundationRoute,
  } as any)
const AppWebsiteFoundationInventoryRoute =
  AppWebsiteFoundationInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AppWebsiteFoundationRoute,
  } as any)
const AppWebsiteFoundationOverviewRoute =
  AppWebsiteFoundationOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AppWebsiteFoundationRoute,
  } as any)
const AppWebsiteFoundationPerformanceRoute =
  AppWebsiteFoundationPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AppWebsiteFoundationRoute,
  } as any)
const AppWebsiteFoundationPluginsRoute =
  AppWebsiteFoundationPluginsRouteImport.update({
    id: '/plugins',
    path: '/plugins',
    getParentRoute: () => AppWebsiteFoundationRoute,
  } as any)
const AppWebsiteFoundationResponsiveRoute =
  AppWebsiteFoundationResponsiveRouteImport.update({
    id: '/responsive',
    path: '/responsive',
    getParentRoute: () => AppWebsiteFoundationRoute,
  } as any)
const AppWebsiteFoundationSslRoute = AppWebsiteFoundationSslRouteImport.update({
  id: '/ssl',
  path: '/ssl',
  getParentRoute: () => AppWebsiteFoundationRoute,
} as any)
const AppWebsiteFoundationThemesRoute =
  AppWebsiteFoundationThemesRouteImport.update({
    id: '/themes',
    path: '/themes',
    getParentRoute: () => AppWebsiteFoundationRoute,
  } as any)
const AppWebsiteFoundationWizardRoute =
  AppWebsiteFoundationWizardRouteImport.update({
    id: '/wizard',
    path: '/wizard',
    getParentRoute: () => AppWebsiteFoundationRoute,
  } as any)
const AppWebsiteFoundationWordpressRoute =
  AppWebsiteFoundationWordpressRouteImport.update({
    id: '/wordpress',
    path: '/wordpress',
    getParentRoute: () => AppWebsiteFoundationRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/search-console': typeof AppSearchConsoleRouteWithChildren
  '/search-knowledge': typeof AppSearchKnowledgeRouteWithChildren
  '/website-foundation': typeof AppWebsiteFoundationRouteWithChildren
  '/search-console/amp': typeof AppSearchConsoleAmpRoute
  '/search-console/countries': typeof AppSearchConsoleCountriesRoute
  '/search-console/coverage': typeof AppSearchConsoleCoverageRoute
  '/search-console/cwv': typeof AppSearchConsoleCwvRoute
  '/search-console/devices': typeof AppSearchConsoleDevicesRoute
  '/search-console/links': typeof AppSearchConsoleLinksRoute
  '/search-console/manual-actions': typeof AppSearchConsoleManualActionsRoute
  '/search-console/mobile-usability': typeof AppSearchConsoleMobileUsabilityRoute
  '/search-console/pages': typeof AppSearchConsolePagesRoute
  '/search-console/performance': typeof AppSearchConsolePerformanceRoute
  '/search-console/property-details': typeof AppSearchConsolePropertyDetailsRoute
  '/search-console/queries': typeof AppSearchConsoleQueriesRoute
  '/search-console/sitemaps': typeof AppSearchConsoleSitemapsRoute
  '/search-console/url-inspection': typeof AppSearchConsoleUrlInspectionRoute
  '/search-console/verification': typeof AppSearchConsoleVerificationRoute
  '/search-knowledge/algorithm-updates': typeof AppSearchKnowledgeAlgorithmUpdatesRoute
  '/search-knowledge/documentation': typeof AppSearchKnowledgeDocumentationRoute
  '/search-knowledge/knowledge-base': typeof AppSearchKnowledgeKnowledgeBaseRoute
  '/search-knowledge/search-operators': typeof AppSearchKnowledgeSearchOperatorsRoute
  '/search-knowledge/serp-features': typeof AppSearchKnowledgeSerpFeaturesRoute
  '/search-knowledge/sync-logs': typeof AppSearchKnowledgeSyncLogsRoute
  '/search-knowledge/versions': typeof AppSearchKnowledgeVersionsRoute
  '/tracking-foundation/audit': typeof AppTrackingFoundationAuditRoute
  '/tracking-foundation/consent': typeof AppTrackingFoundationConsentRoute
  '/tracking-foundation/events': typeof AppTrackingFoundationEventsRoute
  '/tracking-foundation/forms': typeof AppTrackingFoundationFormsRoute
  '/tracking-foundation/measurement-plan': typeof AppTrackingFoundationMeasurementPlanRoute
  '/tracking-foundation/routing': typeof AppTrackingFoundationRoutingRoute
  '/tracking-foundation/submissions': typeof AppTrackingFoundationSubmissionsRoute
  '/tracking-foundation/tracking': typeof AppTrackingFoundationTrackingRoute
  '/tracking-foundation/validation': typeof AppTrackingFoundationValidationRoute
  '/tracking-foundation/verification': typeof AppTrackingFoundationVerificationRoute
  '/tracking/activity-logs': typeof AppTrackingActivityLogsRoute
  '/tracking/approvals': typeof AppTrackingApprovalsRoute
  '/tracking/audit-logs': typeof AppTrackingAuditLogsRoute
  '/tracking/business-goals': typeof AppTrackingBusinessGoalsRoute
  '/tracking/configuration': typeof AppTrackingConfigurationRoute
  '/tracking/consent': typeof AppTrackingConsentRoute
  '/tracking/contact-forms': typeof AppTrackingContactFormsRoute
  '/tracking/conversion-strategy': typeof AppTrackingConversionStrategyRoute
  '/tracking/delivery-logs': typeof AppTrackingDeliveryLogsRoute
  '/tracking/events': typeof AppTrackingEventsRoute
  '/tracking/form-builder': typeof AppTrackingFormBuilderRoute
  '/tracking/kpi-management': typeof AppTrackingKpiManagementRoute
  '/tracking/measurement-plan': typeof AppTrackingMeasurementPlanRoute
  '/tracking/operations': typeof AppTrackingOperationsRoute
  '/tracking/providers': typeof AppTrackingProvidersRoute
  '/tracking/retry-logs': typeof AppTrackingRetryLogsRoute
  '/tracking/routing': typeof AppTrackingRoutingRoute
  '/tracking/settings': typeof AppTrackingSettingsRoute
  '/tracking/spam-protection': typeof AppTrackingSpamProtectionRoute
  '/tracking/submissions': typeof AppTrackingSubmissionsRoute
  '/tracking/testing': typeof AppTrackingTestingRoute
  '/tracking/verification': typeof AppTrackingVerificationRoute
  '/website-foundation/brand': typeof AppWebsiteFoundationBrandRoute
  '/website-foundation/forms': typeof AppWebsiteFoundationFormsRoute
  '/website-foundation/inventory': typeof AppWebsiteFoundationInventoryRoute
  '/website-foundation/overview': typeof AppWebsiteFoundationOverviewRoute
  '/website-foundation/performance': typeof AppWebsiteFoundationPerformanceRoute
  '/website-foundation/plugins': typeof AppWebsiteFoundationPluginsRoute
  '/website-foundation/responsive': typeof AppWebsiteFoundationResponsiveRoute
  '/website-foundation/ssl': typeof AppWebsiteFoundationSslRoute
  '/website-foundation/themes': typeof AppWebsiteFoundationThemesRoute
  '/website-foundation/wizard': typeof AppWebsiteFoundationWizardRoute
  '/website-foundation/wordpress': typeof AppWebsiteFoundationWordpressRoute
  '/audit/': typeof AppAuditIndexRoute
  '/business-keyword-competitor/': typeof AppBusinessKeywordCompetitorIndexRoute
  '/business-profile/': typeof AppBusinessProfileIndexRoute
  '/business/': typeof AppBusinessIndexRoute
  '/competitors/': typeof AppCompetitorsIndexRoute
  '/foundation/': typeof AppFoundationIndexRoute
  '/google-products/': typeof AppGoogleProductsIndexRoute
  '/keywords/': typeof AppKeywordsIndexRoute
  '/mobile/': typeof AppMobileIndexRoute
  '/onpage-seo/': typeof AppOnpageSeoIndexRoute
  '/performance/': typeof AppPerformanceIndexRoute
  '/reports/': typeof AppReportsIndexRoute
  '/search-console/': typeof AppSearchConsoleIndexRoute
  '/search-knowledge/': typeof AppSearchKnowledgeIndexRoute
  '/seo-analyzer/': typeof AppSeoAnalyzerIndexRoute
  '/seo/': typeof AppSeoIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/tracking-foundation/': typeof AppTrackingFoundationIndexRoute
  '/tracking/': typeof AppTrackingIndexRoute
  '/website-foundation/': typeof AppWebsiteFoundationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/search-console/amp': typeof AppSearchConsoleAmpRoute
  '/search-console/countries': typeof AppSearchConsoleCountriesRoute
  '/search-console/coverage': typeof AppSearchConsoleCoverageRoute
  '/search-console/cwv': typeof AppSearchConsoleCwvRoute
  '/search-console/devices': typeof AppSearchConsoleDevicesRoute
  '/search-console/links': typeof AppSearchConsoleLinksRoute
  '/search-console/manual-actions': typeof AppSearchConsoleManualActionsRoute
  '/search-console/mobile-usability': typeof AppSearchConsoleMobileUsabilityRoute
  '/search-console/pages': typeof AppSearchConsolePagesRoute
  '/search-console/performance': typeof AppSearchConsolePerformanceRoute
  '/search-console/property-details': typeof AppSearchConsolePropertyDetailsRoute
  '/search-console/queries': typeof AppSearchConsoleQueriesRoute
  '/search-console/sitemaps': typeof AppSearchConsoleSitemapsRoute
  '/search-console/url-inspection': typeof AppSearchConsoleUrlInspectionRoute
  '/search-console/verification': typeof AppSearchConsoleVerificationRoute
  '/search-knowledge/algorithm-updates': typeof AppSearchKnowledgeAlgorithmUpdatesRoute
  '/search-knowledge/documentation': typeof AppSearchKnowledgeDocumentationRoute
  '/search-knowledge/knowledge-base': typeof AppSearchKnowledgeKnowledgeBaseRoute
  '/search-knowledge/search-operators': typeof AppSearchKnowledgeSearchOperatorsRoute
  '/search-knowledge/serp-features': typeof AppSearchKnowledgeSerpFeaturesRoute
  '/search-knowledge/sync-logs': typeof AppSearchKnowledgeSyncLogsRoute
  '/search-knowledge/versions': typeof AppSearchKnowledgeVersionsRoute
  '/tracking-foundation/audit': typeof AppTrackingFoundationAuditRoute
  '/tracking-foundation/consent': typeof AppTrackingFoundationConsentRoute
  '/tracking-foundation/events': typeof AppTrackingFoundationEventsRoute
  '/tracking-foundation/forms': typeof AppTrackingFoundationFormsRoute
  '/tracking-foundation/measurement-plan': typeof AppTrackingFoundationMeasurementPlanRoute
  '/tracking-foundation/routing': typeof AppTrackingFoundationRoutingRoute
  '/tracking-foundation/submissions': typeof AppTrackingFoundationSubmissionsRoute
  '/tracking-foundation/tracking': typeof AppTrackingFoundationTrackingRoute
  '/tracking-foundation/validation': typeof AppTrackingFoundationValidationRoute
  '/tracking-foundation/verification': typeof AppTrackingFoundationVerificationRoute
  '/tracking/activity-logs': typeof AppTrackingActivityLogsRoute
  '/tracking/approvals': typeof AppTrackingApprovalsRoute
  '/tracking/audit-logs': typeof AppTrackingAuditLogsRoute
  '/tracking/business-goals': typeof AppTrackingBusinessGoalsRoute
  '/tracking/configuration': typeof AppTrackingConfigurationRoute
  '/tracking/consent': typeof AppTrackingConsentRoute
  '/tracking/contact-forms': typeof AppTrackingContactFormsRoute
  '/tracking/conversion-strategy': typeof AppTrackingConversionStrategyRoute
  '/tracking/delivery-logs': typeof AppTrackingDeliveryLogsRoute
  '/tracking/events': typeof AppTrackingEventsRoute
  '/tracking/form-builder': typeof AppTrackingFormBuilderRoute
  '/tracking/kpi-management': typeof AppTrackingKpiManagementRoute
  '/tracking/measurement-plan': typeof AppTrackingMeasurementPlanRoute
  '/tracking/operations': typeof AppTrackingOperationsRoute
  '/tracking/providers': typeof AppTrackingProvidersRoute
  '/tracking/retry-logs': typeof AppTrackingRetryLogsRoute
  '/tracking/routing': typeof AppTrackingRoutingRoute
  '/tracking/settings': typeof AppTrackingSettingsRoute
  '/tracking/spam-protection': typeof AppTrackingSpamProtectionRoute
  '/tracking/submissions': typeof AppTrackingSubmissionsRoute
  '/tracking/testing': typeof AppTrackingTestingRoute
  '/tracking/verification': typeof AppTrackingVerificationRoute
  '/website-foundation/brand': typeof AppWebsiteFoundationBrandRoute
  '/website-foundation/forms': typeof AppWebsiteFoundationFormsRoute
  '/website-foundation/inventory': typeof AppWebsiteFoundationInventoryRoute
  '/website-foundation/overview': typeof AppWebsiteFoundationOverviewRoute
  '/website-foundation/performance': typeof AppWebsiteFoundationPerformanceRoute
  '/website-foundation/plugins': typeof AppWebsiteFoundationPluginsRoute
  '/website-foundation/responsive': typeof AppWebsiteFoundationResponsiveRoute
  '/website-foundation/ssl': typeof AppWebsiteFoundationSslRoute
  '/website-foundation/themes': typeof AppWebsiteFoundationThemesRoute
  '/website-foundation/wizard': typeof AppWebsiteFoundationWizardRoute
  '/website-foundation/wordpress': typeof AppWebsiteFoundationWordpressRoute
  '/audit': typeof AppAuditIndexRoute
  '/business-keyword-competitor': typeof AppBusinessKeywordCompetitorIndexRoute
  '/business-profile': typeof AppBusinessProfileIndexRoute
  '/business': typeof AppBusinessIndexRoute
  '/competitors': typeof AppCompetitorsIndexRoute
  '/foundation': typeof AppFoundationIndexRoute
  '/google-products': typeof AppGoogleProductsIndexRoute
  '/keywords': typeof AppKeywordsIndexRoute
  '/mobile': typeof AppMobileIndexRoute
  '/onpage-seo': typeof AppOnpageSeoIndexRoute
  '/performance': typeof AppPerformanceIndexRoute
  '/reports': typeof AppReportsIndexRoute
  '/search-console': typeof AppSearchConsoleIndexRoute
  '/search-knowledge': typeof AppSearchKnowledgeIndexRoute
  '/seo-analyzer': typeof AppSeoAnalyzerIndexRoute
  '/seo': typeof AppSeoIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/tracking-foundation': typeof AppTrackingFoundationIndexRoute
  '/tracking': typeof AppTrackingIndexRoute
  '/website-foundation': typeof AppWebsiteFoundationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/search-console': typeof AppSearchConsoleRouteWithChildren
  '/_app/search-knowledge': typeof AppSearchKnowledgeRouteWithChildren
  '/_app/website-foundation': typeof AppWebsiteFoundationRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/search-console/amp': typeof AppSearchConsoleAmpRoute
  '/_app/search-console/countries': typeof AppSearchConsoleCountriesRoute
  '/_app/search-console/coverage': typeof AppSearchConsoleCoverageRoute
  '/_app/search-console/cwv': typeof AppSearchConsoleCwvRoute
  '/_app/search-console/devices': typeof AppSearchConsoleDevicesRoute
  '/_app/search-console/links': typeof AppSearchConsoleLinksRoute
  '/_app/search-console/manual-actions': typeof AppSearchConsoleManualActionsRoute
  '/_app/search-console/mobile-usability': typeof AppSearchConsoleMobileUsabilityRoute
  '/_app/search-console/pages': typeof AppSearchConsolePagesRoute
  '/_app/search-console/performance': typeof AppSearchConsolePerformanceRoute
  '/_app/search-console/property-details': typeof AppSearchConsolePropertyDetailsRoute
  '/_app/search-console/queries': typeof AppSearchConsoleQueriesRoute
  '/_app/search-console/sitemaps': typeof AppSearchConsoleSitemapsRoute
  '/_app/search-console/url-inspection': typeof AppSearchConsoleUrlInspectionRoute
  '/_app/search-console/verification': typeof AppSearchConsoleVerificationRoute
  '/_app/search-knowledge/algorithm-updates': typeof AppSearchKnowledgeAlgorithmUpdatesRoute
  '/_app/search-knowledge/documentation': typeof AppSearchKnowledgeDocumentationRoute
  '/_app/search-knowledge/knowledge-base': typeof AppSearchKnowledgeKnowledgeBaseRoute
  '/_app/search-knowledge/search-operators': typeof AppSearchKnowledgeSearchOperatorsRoute
  '/_app/search-knowledge/serp-features': typeof AppSearchKnowledgeSerpFeaturesRoute
  '/_app/search-knowledge/sync-logs': typeof AppSearchKnowledgeSyncLogsRoute
  '/_app/search-knowledge/versions': typeof AppSearchKnowledgeVersionsRoute
  '/_app/tracking-foundation/audit': typeof AppTrackingFoundationAuditRoute
  '/_app/tracking-foundation/consent': typeof AppTrackingFoundationConsentRoute
  '/_app/tracking-foundation/events': typeof AppTrackingFoundationEventsRoute
  '/_app/tracking-foundation/forms': typeof AppTrackingFoundationFormsRoute
  '/_app/tracking-foundation/measurement-plan': typeof AppTrackingFoundationMeasurementPlanRoute
  '/_app/tracking-foundation/routing': typeof AppTrackingFoundationRoutingRoute
  '/_app/tracking-foundation/submissions': typeof AppTrackingFoundationSubmissionsRoute
  '/_app/tracking-foundation/tracking': typeof AppTrackingFoundationTrackingRoute
  '/_app/tracking-foundation/validation': typeof AppTrackingFoundationValidationRoute
  '/_app/tracking-foundation/verification': typeof AppTrackingFoundationVerificationRoute
  '/_app/tracking/activity-logs': typeof AppTrackingActivityLogsRoute
  '/_app/tracking/approvals': typeof AppTrackingApprovalsRoute
  '/_app/tracking/audit-logs': typeof AppTrackingAuditLogsRoute
  '/_app/tracking/business-goals': typeof AppTrackingBusinessGoalsRoute
  '/_app/tracking/configuration': typeof AppTrackingConfigurationRoute
  '/_app/tracking/consent': typeof AppTrackingConsentRoute
  '/_app/tracking/contact-forms': typeof AppTrackingContactFormsRoute
  '/_app/tracking/conversion-strategy': typeof AppTrackingConversionStrategyRoute
  '/_app/tracking/delivery-logs': typeof AppTrackingDeliveryLogsRoute
  '/_app/tracking/events': typeof AppTrackingEventsRoute
  '/_app/tracking/form-builder': typeof AppTrackingFormBuilderRoute
  '/_app/tracking/kpi-management': typeof AppTrackingKpiManagementRoute
  '/_app/tracking/measurement-plan': typeof AppTrackingMeasurementPlanRoute
  '/_app/tracking/operations': typeof AppTrackingOperationsRoute
  '/_app/tracking/providers': typeof AppTrackingProvidersRoute
  '/_app/tracking/retry-logs': typeof AppTrackingRetryLogsRoute
  '/_app/tracking/routing': typeof AppTrackingRoutingRoute
  '/_app/tracking/settings': typeof AppTrackingSettingsRoute
  '/_app/tracking/spam-protection': typeof AppTrackingSpamProtectionRoute
  '/_app/tracking/submissions': typeof AppTrackingSubmissionsRoute
  '/_app/tracking/testing': typeof AppTrackingTestingRoute
  '/_app/tracking/verification': typeof AppTrackingVerificationRoute
  '/_app/website-foundation/brand': typeof AppWebsiteFoundationBrandRoute
  '/_app/website-foundation/forms': typeof AppWebsiteFoundationFormsRoute
  '/_app/website-foundation/inventory': typeof AppWebsiteFoundationInventoryRoute
  '/_app/website-foundation/overview': typeof AppWebsiteFoundationOverviewRoute
  '/_app/website-foundation/performance': typeof AppWebsiteFoundationPerformanceRoute
  '/_app/website-foundation/plugins': typeof AppWebsiteFoundationPluginsRoute
  '/_app/website-foundation/responsive': typeof AppWebsiteFoundationResponsiveRoute
  '/_app/website-foundation/ssl': typeof AppWebsiteFoundationSslRoute
  '/_app/website-foundation/themes': typeof AppWebsiteFoundationThemesRoute
  '/_app/website-foundation/wizard': typeof AppWebsiteFoundationWizardRoute
  '/_app/website-foundation/wordpress': typeof AppWebsiteFoundationWordpressRoute
  '/_app/audit/': typeof AppAuditIndexRoute
  '/_app/business-keyword-competitor/': typeof AppBusinessKeywordCompetitorIndexRoute
  '/_app/business-profile/': typeof AppBusinessProfileIndexRoute
  '/_app/business/': typeof AppBusinessIndexRoute
  '/_app/competitors/': typeof AppCompetitorsIndexRoute
  '/_app/foundation/': typeof AppFoundationIndexRoute
  '/_app/google-products/': typeof AppGoogleProductsIndexRoute
  '/_app/keywords/': typeof AppKeywordsIndexRoute
  '/_app/mobile/': typeof AppMobileIndexRoute
  '/_app/onpage-seo/': typeof AppOnpageSeoIndexRoute
  '/_app/performance/': typeof AppPerformanceIndexRoute
  '/_app/reports/': typeof AppReportsIndexRoute
  '/_app/search-console/': typeof AppSearchConsoleIndexRoute
  '/_app/search-knowledge/': typeof AppSearchKnowledgeIndexRoute
  '/_app/seo-analyzer/': typeof AppSeoAnalyzerIndexRoute
  '/_app/seo/': typeof AppSeoIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/tracking-foundation/': typeof AppTrackingFoundationIndexRoute
  '/_app/tracking/': typeof AppTrackingIndexRoute
  '/_app/website-foundation/': typeof AppWebsiteFoundationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/search-console'
    | '/search-knowledge'
    | '/website-foundation'
    | '/search-console/amp'
    | '/search-console/countries'
    | '/search-console/coverage'
    | '/search-console/cwv'
    | '/search-console/devices'
    | '/search-console/links'
    | '/search-console/manual-actions'
    | '/search-console/mobile-usability'
    | '/search-console/pages'
    | '/search-console/performance'
    | '/search-console/property-details'
    | '/search-console/queries'
    | '/search-console/sitemaps'
    | '/search-console/url-inspection'
    | '/search-console/verification'
    | '/search-knowledge/algorithm-updates'
    | '/search-knowledge/documentation'
    | '/search-knowledge/knowledge-base'
    | '/search-knowledge/search-operators'
    | '/search-knowledge/serp-features'
    | '/search-knowledge/sync-logs'
    | '/search-knowledge/versions'
    | '/tracking-foundation/audit'
    | '/tracking-foundation/consent'
    | '/tracking-foundation/events'
    | '/tracking-foundation/forms'
    | '/tracking-foundation/measurement-plan'
    | '/tracking-foundation/routing'
    | '/tracking-foundation/submissions'
    | '/tracking-foundation/tracking'
    | '/tracking-foundation/validation'
    | '/tracking-foundation/verification'
    | '/tracking/activity-logs'
    | '/tracking/approvals'
    | '/tracking/audit-logs'
    | '/tracking/business-goals'
    | '/tracking/configuration'
    | '/tracking/consent'
    | '/tracking/contact-forms'
    | '/tracking/conversion-strategy'
    | '/tracking/delivery-logs'
    | '/tracking/events'
    | '/tracking/form-builder'
    | '/tracking/kpi-management'
    | '/tracking/measurement-plan'
    | '/tracking/operations'
    | '/tracking/providers'
    | '/tracking/retry-logs'
    | '/tracking/routing'
    | '/tracking/settings'
    | '/tracking/spam-protection'
    | '/tracking/submissions'
    | '/tracking/testing'
    | '/tracking/verification'
    | '/website-foundation/brand'
    | '/website-foundation/forms'
    | '/website-foundation/inventory'
    | '/website-foundation/overview'
    | '/website-foundation/performance'
    | '/website-foundation/plugins'
    | '/website-foundation/responsive'
    | '/website-foundation/ssl'
    | '/website-foundation/themes'
    | '/website-foundation/wizard'
    | '/website-foundation/wordpress'
    | '/audit/'
    | '/business-keyword-competitor/'
    | '/business-profile/'
    | '/business/'
    | '/competitors/'
    | '/foundation/'
    | '/google-products/'
    | '/keywords/'
    | '/mobile/'
    | '/onpage-seo/'
    | '/performance/'
    | '/reports/'
    | '/search-console/'
    | '/search-knowledge/'
    | '/seo-analyzer/'
    | '/seo/'
    | '/settings/'
    | '/tracking-foundation/'
    | '/tracking/'
    | '/website-foundation/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search-console/amp'
    | '/search-console/countries'
    | '/search-console/coverage'
    | '/search-console/cwv'
    | '/search-console/devices'
    | '/search-console/links'
    | '/search-console/manual-actions'
    | '/search-console/mobile-usability'
    | '/search-console/pages'
    | '/search-console/performance'
    | '/search-console/property-details'
    | '/search-console/queries'
    | '/search-console/sitemaps'
    | '/search-console/url-inspection'
    | '/search-console/verification'
    | '/search-knowledge/algorithm-updates'
    | '/search-knowledge/documentation'
    | '/search-knowledge/knowledge-base'
    | '/search-knowledge/search-operators'
    | '/search-knowledge/serp-features'
    | '/search-knowledge/sync-logs'
    | '/search-knowledge/versions'
    | '/tracking-foundation/audit'
    | '/tracking-foundation/consent'
    | '/tracking-foundation/events'
    | '/tracking-foundation/forms'
    | '/tracking-foundation/measurement-plan'
    | '/tracking-foundation/routing'
    | '/tracking-foundation/submissions'
    | '/tracking-foundation/tracking'
    | '/tracking-foundation/validation'
    | '/tracking-foundation/verification'
    | '/tracking/activity-logs'
    | '/tracking/approvals'
    | '/tracking/audit-logs'
    | '/tracking/business-goals'
    | '/tracking/configuration'
    | '/tracking/consent'
    | '/tracking/contact-forms'
    | '/tracking/conversion-strategy'
    | '/tracking/delivery-logs'
    | '/tracking/events'
    | '/tracking/form-builder'
    | '/tracking/kpi-management'
    | '/tracking/measurement-plan'
    | '/tracking/operations'
    | '/tracking/providers'
    | '/tracking/retry-logs'
    | '/tracking/routing'
    | '/tracking/settings'
    | '/tracking/spam-protection'
    | '/tracking/submissions'
    | '/tracking/testing'
    | '/tracking/verification'
    | '/website-foundation/brand'
    | '/website-foundation/forms'
    | '/website-foundation/inventory'
    | '/website-foundation/overview'
    | '/website-foundation/performance'
    | '/website-foundation/plugins'
    | '/website-foundation/responsive'
    | '/website-foundation/ssl'
    | '/website-foundation/themes'
    | '/website-foundation/wizard'
    | '/website-foundation/wordpress'
    | '/audit'
    | '/business-keyword-competitor'
    | '/business-profile'
    | '/business'
    | '/competitors'
    | '/foundation'
    | '/google-products'
    | '/keywords'
    | '/mobile'
    | '/onpage-seo'
    | '/performance'
    | '/reports'
    | '/search-console'
    | '/search-knowledge'
    | '/seo-analyzer'
    | '/seo'
    | '/settings'
    | '/tracking-foundation'
    | '/tracking'
    | '/website-foundation'
  id:
    | '__root__'
    | '/_app'
    | '/_app/search-console'
    | '/_app/search-knowledge'
    | '/_app/website-foundation'
    | '/_app/'
    | '/_app/search-console/amp'
    | '/_app/search-console/countries'
    | '/_app/search-console/coverage'
    | '/_app/search-console/cwv'
    | '/_app/search-console/devices'
    | '/_app/search-console/links'
    | '/_app/search-console/manual-actions'
    | '/_app/search-console/mobile-usability'
    | '/_app/search-console/pages'
    | '/_app/search-console/performance'
    | '/_app/search-console/property-details'
    | '/_app/search-console/queries'
    | '/_app/search-console/sitemaps'
    | '/_app/search-console/url-inspection'
    | '/_app/search-console/verification'
    | '/_app/search-knowledge/algorithm-updates'
    | '/_app/search-knowledge/documentation'
    | '/_app/search-knowledge/knowledge-base'
    | '/_app/search-knowledge/search-operators'
    | '/_app/search-knowledge/serp-features'
    | '/_app/search-knowledge/sync-logs'
    | '/_app/search-knowledge/versions'
    | '/_app/tracking-foundation/audit'
    | '/_app/tracking-foundation/consent'
    | '/_app/tracking-foundation/events'
    | '/_app/tracking-foundation/forms'
    | '/_app/tracking-foundation/measurement-plan'
    | '/_app/tracking-foundation/routing'
    | '/_app/tracking-foundation/submissions'
    | '/_app/tracking-foundation/tracking'
    | '/_app/tracking-foundation/validation'
    | '/_app/tracking-foundation/verification'
    | '/_app/tracking/activity-logs'
    | '/_app/tracking/approvals'
    | '/_app/tracking/audit-logs'
    | '/_app/tracking/business-goals'
    | '/_app/tracking/configuration'
    | '/_app/tracking/consent'
    | '/_app/tracking/contact-forms'
    | '/_app/tracking/conversion-strategy'
    | '/_app/tracking/delivery-logs'
    | '/_app/tracking/events'
    | '/_app/tracking/form-builder'
    | '/_app/tracking/kpi-management'
    | '/_app/tracking/measurement-plan'
    | '/_app/tracking/operations'
    | '/_app/tracking/providers'
    | '/_app/tracking/retry-logs'
    | '/_app/tracking/routing'
    | '/_app/tracking/settings'
    | '/_app/tracking/spam-protection'
    | '/_app/tracking/submissions'
    | '/_app/tracking/testing'
    | '/_app/tracking/verification'
    | '/_app/website-foundation/brand'
    | '/_app/website-foundation/forms'
    | '/_app/website-foundation/inventory'
    | '/_app/website-foundation/overview'
    | '/_app/website-foundation/performance'
    | '/_app/website-foundation/plugins'
    | '/_app/website-foundation/responsive'
    | '/_app/website-foundation/ssl'
    | '/_app/website-foundation/themes'
    | '/_app/website-foundation/wizard'
    | '/_app/website-foundation/wordpress'
    | '/_app/audit/'
    | '/_app/business-keyword-competitor/'
    | '/_app/business-profile/'
    | '/_app/business/'
    | '/_app/competitors/'
    | '/_app/foundation/'
    | '/_app/google-products/'
    | '/_app/keywords/'
    | '/_app/mobile/'
    | '/_app/onpage-seo/'
    | '/_app/performance/'
    | '/_app/reports/'
    | '/_app/search-console/'
    | '/_app/search-knowledge/'
    | '/_app/seo-analyzer/'
    | '/_app/seo/'
    | '/_app/settings/'
    | '/_app/tracking-foundation/'
    | '/_app/tracking/'
    | '/_app/website-foundation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search-console': {
      id: '/_app/search-console'
      path: '/search-console'
      fullPath: '/search-console'
      preLoaderRoute: typeof AppSearchConsoleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search-knowledge': {
      id: '/_app/search-knowledge'
      path: '/search-knowledge'
      fullPath: '/search-knowledge'
      preLoaderRoute: typeof AppSearchKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/website-foundation': {
      id: '/_app/website-foundation'
      path: '/website-foundation'
      fullPath: '/website-foundation'
      preLoaderRoute: typeof AppWebsiteFoundationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit/': {
      id: '/_app/audit/'
      path: '/audit'
      fullPath: '/audit/'
      preLoaderRoute: typeof AppAuditIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/business-keyword-competitor/': {
      id: '/_app/business-keyword-competitor/'
      path: '/business-keyword-competitor'
      fullPath: '/business-keyword-competitor/'
      preLoaderRoute: typeof AppBusinessKeywordCompetitorIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/business-profile/': {
      id: '/_app/business-profile/'
      path: '/business-profile'
      fullPath: '/business-profile/'
      preLoaderRoute: typeof AppBusinessProfileIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/business/': {
      id: '/_app/business/'
      path: '/business'
      fullPath: '/business/'
      preLoaderRoute: typeof AppBusinessIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/competitors/': {
      id: '/_app/competitors/'
      path: '/competitors'
      fullPath: '/competitors/'
      preLoaderRoute: typeof AppCompetitorsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/foundation/': {
      id: '/_app/foundation/'
      path: '/foundation'
      fullPath: '/foundation/'
      preLoaderRoute: typeof AppFoundationIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/google-products/': {
      id: '/_app/google-products/'
      path: '/google-products'
      fullPath: '/google-products/'
      preLoaderRoute: typeof AppGoogleProductsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/keywords/': {
      id: '/_app/keywords/'
      path: '/keywords'
      fullPath: '/keywords/'
      preLoaderRoute: typeof AppKeywordsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mobile/': {
      id: '/_app/mobile/'
      path: '/mobile'
      fullPath: '/mobile/'
      preLoaderRoute: typeof AppMobileIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onpage-seo/': {
      id: '/_app/onpage-seo/'
      path: '/onpage-seo'
      fullPath: '/onpage-seo/'
      preLoaderRoute: typeof AppOnpageSeoIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/performance/': {
      id: '/_app/performance/'
      path: '/performance'
      fullPath: '/performance/'
      preLoaderRoute: typeof AppPerformanceIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/': {
      id: '/_app/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search-console/': {
      id: '/_app/search-console/'
      path: '/'
      fullPath: '/search-console/'
      preLoaderRoute: typeof AppSearchConsoleIndexRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-console/amp': {
      id: '/_app/search-console/amp'
      path: '/amp'
      fullPath: '/search-console/amp'
      preLoaderRoute: typeof AppSearchConsoleAmpRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-console/countries': {
      id: '/_app/search-console/countries'
      path: '/countries'
      fullPath: '/search-console/countries'
      preLoaderRoute: typeof AppSearchConsoleCountriesRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-console/coverage': {
      id: '/_app/search-console/coverage'
      path: '/coverage'
      fullPath: '/search-console/coverage'
      preLoaderRoute: typeof AppSearchConsoleCoverageRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-console/cwv': {
      id: '/_app/search-console/cwv'
      path: '/cwv'
      fullPath: '/search-console/cwv'
      preLoaderRoute: typeof AppSearchConsoleCwvRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-console/devices': {
      id: '/_app/search-console/devices'
      path: '/devices'
      fullPath: '/search-console/devices'
      preLoaderRoute: typeof AppSearchConsoleDevicesRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-console/links': {
      id: '/_app/search-console/links'
      path: '/links'
      fullPath: '/search-console/links'
      preLoaderRoute: typeof AppSearchConsoleLinksRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-console/manual-actions': {
      id: '/_app/search-console/manual-actions'
      path: '/manual-actions'
      fullPath: '/search-console/manual-actions'
      preLoaderRoute: typeof AppSearchConsoleManualActionsRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-console/mobile-usability': {
      id: '/_app/search-console/mobile-usability'
      path: '/mobile-usability'
      fullPath: '/search-console/mobile-usability'
      preLoaderRoute: typeof AppSearchConsoleMobileUsabilityRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-console/pages': {
      id: '/_app/search-console/pages'
      path: '/pages'
      fullPath: '/search-console/pages'
      preLoaderRoute: typeof AppSearchConsolePagesRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-console/performance': {
      id: '/_app/search-console/performance'
      path: '/performance'
      fullPath: '/search-console/performance'
      preLoaderRoute: typeof AppSearchConsolePerformanceRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-console/property-details': {
      id: '/_app/search-console/property-details'
      path: '/property-details'
      fullPath: '/search-console/property-details'
      preLoaderRoute: typeof AppSearchConsolePropertyDetailsRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-console/queries': {
      id: '/_app/search-console/queries'
      path: '/queries'
      fullPath: '/search-console/queries'
      preLoaderRoute: typeof AppSearchConsoleQueriesRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-console/sitemaps': {
      id: '/_app/search-console/sitemaps'
      path: '/sitemaps'
      fullPath: '/search-console/sitemaps'
      preLoaderRoute: typeof AppSearchConsoleSitemapsRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-console/url-inspection': {
      id: '/_app/search-console/url-inspection'
      path: '/url-inspection'
      fullPath: '/search-console/url-inspection'
      preLoaderRoute: typeof AppSearchConsoleUrlInspectionRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-console/verification': {
      id: '/_app/search-console/verification'
      path: '/verification'
      fullPath: '/search-console/verification'
      preLoaderRoute: typeof AppSearchConsoleVerificationRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-knowledge/': {
      id: '/_app/search-knowledge/'
      path: '/'
      fullPath: '/search-knowledge/'
      preLoaderRoute: typeof AppSearchKnowledgeIndexRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/algorithm-updates': {
      id: '/_app/search-knowledge/algorithm-updates'
      path: '/algorithm-updates'
      fullPath: '/search-knowledge/algorithm-updates'
      preLoaderRoute: typeof AppSearchKnowledgeAlgorithmUpdatesRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/documentation': {
      id: '/_app/search-knowledge/documentation'
      path: '/documentation'
      fullPath: '/search-knowledge/documentation'
      preLoaderRoute: typeof AppSearchKnowledgeDocumentationRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/knowledge-base': {
      id: '/_app/search-knowledge/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/search-knowledge/knowledge-base'
      preLoaderRoute: typeof AppSearchKnowledgeKnowledgeBaseRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/search-operators': {
      id: '/_app/search-knowledge/search-operators'
      path: '/search-operators'
      fullPath: '/search-knowledge/search-operators'
      preLoaderRoute: typeof AppSearchKnowledgeSearchOperatorsRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/serp-features': {
      id: '/_app/search-knowledge/serp-features'
      path: '/serp-features'
      fullPath: '/search-knowledge/serp-features'
      preLoaderRoute: typeof AppSearchKnowledgeSerpFeaturesRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/sync-logs': {
      id: '/_app/search-knowledge/sync-logs'
      path: '/sync-logs'
      fullPath: '/search-knowledge/sync-logs'
      preLoaderRoute: typeof AppSearchKnowledgeSyncLogsRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/versions': {
      id: '/_app/search-knowledge/versions'
      path: '/versions'
      fullPath: '/search-knowledge/versions'
      preLoaderRoute: typeof AppSearchKnowledgeVersionsRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/seo-analyzer/': {
      id: '/_app/seo-analyzer/'
      path: '/seo-analyzer'
      fullPath: '/seo-analyzer/'
      preLoaderRoute: typeof AppSeoAnalyzerIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/seo/': {
      id: '/_app/seo/'
      path: '/seo'
      fullPath: '/seo/'
      preLoaderRoute: typeof AppSeoIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking-foundation/': {
      id: '/_app/tracking-foundation/'
      path: '/tracking-foundation'
      fullPath: '/tracking-foundation/'
      preLoaderRoute: typeof AppTrackingFoundationIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking-foundation/audit': {
      id: '/_app/tracking-foundation/audit'
      path: '/tracking-foundation/audit'
      fullPath: '/tracking-foundation/audit'
      preLoaderRoute: typeof AppTrackingFoundationAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking-foundation/consent': {
      id: '/_app/tracking-foundation/consent'
      path: '/tracking-foundation/consent'
      fullPath: '/tracking-foundation/consent'
      preLoaderRoute: typeof AppTrackingFoundationConsentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking-foundation/events': {
      id: '/_app/tracking-foundation/events'
      path: '/tracking-foundation/events'
      fullPath: '/tracking-foundation/events'
      preLoaderRoute: typeof AppTrackingFoundationEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking-foundation/forms': {
      id: '/_app/tracking-foundation/forms'
      path: '/tracking-foundation/forms'
      fullPath: '/tracking-foundation/forms'
      preLoaderRoute: typeof AppTrackingFoundationFormsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking-foundation/measurement-plan': {
      id: '/_app/tracking-foundation/measurement-plan'
      path: '/tracking-foundation/measurement-plan'
      fullPath: '/tracking-foundation/measurement-plan'
      preLoaderRoute: typeof AppTrackingFoundationMeasurementPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking-foundation/routing': {
      id: '/_app/tracking-foundation/routing'
      path: '/tracking-foundation/routing'
      fullPath: '/tracking-foundation/routing'
      preLoaderRoute: typeof AppTrackingFoundationRoutingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking-foundation/submissions': {
      id: '/_app/tracking-foundation/submissions'
      path: '/tracking-foundation/submissions'
      fullPath: '/tracking-foundation/submissions'
      preLoaderRoute: typeof AppTrackingFoundationSubmissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking-foundation/tracking': {
      id: '/_app/tracking-foundation/tracking'
      path: '/tracking-foundation/tracking'
      fullPath: '/tracking-foundation/tracking'
      preLoaderRoute: typeof AppTrackingFoundationTrackingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking-foundation/validation': {
      id: '/_app/tracking-foundation/validation'
      path: '/tracking-foundation/validation'
      fullPath: '/tracking-foundation/validation'
      preLoaderRoute: typeof AppTrackingFoundationValidationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking-foundation/verification': {
      id: '/_app/tracking-foundation/verification'
      path: '/tracking-foundation/verification'
      fullPath: '/tracking-foundation/verification'
      preLoaderRoute: typeof AppTrackingFoundationVerificationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking/': {
      id: '/_app/tracking/'
      path: '/tracking'
      fullPath: '/tracking/'
      preLoaderRoute: typeof AppTrackingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking/activity-logs': {
      id: '/_app/tracking/activity-logs'
      path: '/tracking/activity-logs'
      fullPath: '/tracking/activity-logs'
      preLoaderRoute: typeof AppTrackingActivityLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking/approvals': {
      id: '/_app/tracking/approvals'
      path: '/tracking/approvals'
      fullPath: '/tracking/approvals'
      preLoaderRoute: typeof AppTrackingApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking/audit-logs': {
      id: '/_app/tracking/audit-logs'
      path: '/tracking/audit-logs'
      fullPath: '/tracking/audit-logs'
      preLoaderRoute: typeof AppTrackingAuditLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking/business-goals': {
      id: '/_app/tracking/business-goals'
      path: '/tracking/business-goals'
      fullPath: '/tracking/business-goals'
      preLoaderRoute: typeof AppTrackingBusinessGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking/configuration': {
      id: '/_app/tracking/configuration'
      path: '/tracking/configuration'
      fullPath: '/tracking/configuration'
      preLoaderRoute: typeof AppTrackingConfigurationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking/consent': {
      id: '/_app/tracking/consent'
      path: '/tracking/consent'
      fullPath: '/tracking/consent'
      preLoaderRoute: typeof AppTrackingConsentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking/contact-forms': {
      id: '/_app/tracking/contact-forms'
      path: '/tracking/contact-forms'
      fullPath: '/tracking/contact-forms'
      preLoaderRoute: typeof AppTrackingContactFormsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking/conversion-strategy': {
      id: '/_app/tracking/conversion-strategy'
      path: '/tracking/conversion-strategy'
      fullPath: '/tracking/conversion-strategy'
      preLoaderRoute: typeof AppTrackingConversionStrategyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking/delivery-logs': {
      id: '/_app/tracking/delivery-logs'
      path: '/tracking/delivery-logs'
      fullPath: '/tracking/delivery-logs'
      preLoaderRoute: typeof AppTrackingDeliveryLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking/events': {
      id: '/_app/tracking/events'
      path: '/tracking/events'
      fullPath: '/tracking/events'
      preLoaderRoute: typeof AppTrackingEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking/form-builder': {
      id: '/_app/tracking/form-builder'
      path: '/tracking/form-builder'
      fullPath: '/tracking/form-builder'
      preLoaderRoute: typeof AppTrackingFormBuilderRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking/kpi-management': {
      id: '/_app/tracking/kpi-management'
      path: '/tracking/kpi-management'
      fullPath: '/tracking/kpi-management'
      preLoaderRoute: typeof AppTrackingKpiManagementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking/measurement-plan': {
      id: '/_app/tracking/measurement-plan'
      path: '/tracking/measurement-plan'
      fullPath: '/tracking/measurement-plan'
      preLoaderRoute: typeof AppTrackingMeasurementPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking/operations': {
      id: '/_app/tracking/operations'
      path: '/tracking/operations'
      fullPath: '/tracking/operations'
      preLoaderRoute: typeof AppTrackingOperationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking/providers': {
      id: '/_app/tracking/providers'
      path: '/tracking/providers'
      fullPath: '/tracking/providers'
      preLoaderRoute: typeof AppTrackingProvidersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking/retry-logs': {
      id: '/_app/tracking/retry-logs'
      path: '/tracking/retry-logs'
      fullPath: '/tracking/retry-logs'
      preLoaderRoute: typeof AppTrackingRetryLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking/routing': {
      id: '/_app/tracking/routing'
      path: '/tracking/routing'
      fullPath: '/tracking/routing'
      preLoaderRoute: typeof AppTrackingRoutingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking/settings': {
      id: '/_app/tracking/settings'
      path: '/tracking/settings'
      fullPath: '/tracking/settings'
      preLoaderRoute: typeof AppTrackingSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking/spam-protection': {
      id: '/_app/tracking/spam-protection'
      path: '/tracking/spam-protection'
      fullPath: '/tracking/spam-protection'
      preLoaderRoute: typeof AppTrackingSpamProtectionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking/submissions': {
      id: '/_app/tracking/submissions'
      path: '/tracking/submissions'
      fullPath: '/tracking/submissions'
      preLoaderRoute: typeof AppTrackingSubmissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking/testing': {
      id: '/_app/tracking/testing'
      path: '/tracking/testing'
      fullPath: '/tracking/testing'
      preLoaderRoute: typeof AppTrackingTestingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking/verification': {
      id: '/_app/tracking/verification'
      path: '/tracking/verification'
      fullPath: '/tracking/verification'
      preLoaderRoute: typeof AppTrackingVerificationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/website-foundation/': {
      id: '/_app/website-foundation/'
      path: '/'
      fullPath: '/website-foundation/'
      preLoaderRoute: typeof AppWebsiteFoundationIndexRouteImport
      parentRoute: typeof AppWebsiteFoundationRoute
    }
    '/_app/website-foundation/brand': {
      id: '/_app/website-foundation/brand'
      path: '/brand'
      fullPath: '/website-foundation/brand'
      preLoaderRoute: typeof AppWebsiteFoundationBrandRouteImport
      parentRoute: typeof AppWebsiteFoundationRoute
    }
    '/_app/website-foundation/forms': {
      id: '/_app/website-foundation/forms'
      path: '/forms'
      fullPath: '/website-foundation/forms'
      preLoaderRoute: typeof AppWebsiteFoundationFormsRouteImport
      parentRoute: typeof AppWebsiteFoundationRoute
    }
    '/_app/website-foundation/inventory': {
      id: '/_app/website-foundation/inventory'
      path: '/inventory'
      fullPath: '/website-foundation/inventory'
      preLoaderRoute: typeof AppWebsiteFoundationInventoryRouteImport
      parentRoute: typeof AppWebsiteFoundationRoute
    }
    '/_app/website-foundation/overview': {
      id: '/_app/website-foundation/overview'
      path: '/overview'
      fullPath: '/website-foundation/overview'
      preLoaderRoute: typeof AppWebsiteFoundationOverviewRouteImport
      parentRoute: typeof AppWebsiteFoundationRoute
    }
    '/_app/website-foundation/performance': {
      id: '/_app/website-foundation/performance'
      path: '/performance'
      fullPath: '/website-foundation/performance'
      preLoaderRoute: typeof AppWebsiteFoundationPerformanceRouteImport
      parentRoute: typeof AppWebsiteFoundationRoute
    }
    '/_app/website-foundation/plugins': {
      id: '/_app/website-foundation/plugins'
      path: '/plugins'
      fullPath: '/website-foundation/plugins'
      preLoaderRoute: typeof AppWebsiteFoundationPluginsRouteImport
      parentRoute: typeof AppWebsiteFoundationRoute
    }
    '/_app/website-foundation/responsive': {
      id: '/_app/website-foundation/responsive'
      path: '/responsive'
      fullPath: '/website-foundation/responsive'
      preLoaderRoute: typeof AppWebsiteFoundationResponsiveRouteImport
      parentRoute: typeof AppWebsiteFoundationRoute
    }
    '/_app/website-foundation/ssl': {
      id: '/_app/website-foundation/ssl'
      path: '/ssl'
      fullPath: '/website-foundation/ssl'
      preLoaderRoute: typeof AppWebsiteFoundationSslRouteImport
      parentRoute: typeof AppWebsiteFoundationRoute
    }
    '/_app/website-foundation/themes': {
      id: '/_app/website-foundation/themes'
      path: '/themes'
      fullPath: '/website-foundation/themes'
      preLoaderRoute: typeof AppWebsiteFoundationThemesRouteImport
      parentRoute: typeof AppWebsiteFoundationRoute
    }
    '/_app/website-foundation/wizard': {
      id: '/_app/website-foundation/wizard'
      path: '/wizard'
      fullPath: '/website-foundation/wizard'
      preLoaderRoute: typeof AppWebsiteFoundationWizardRouteImport
      parentRoute: typeof AppWebsiteFoundationRoute
    }
    '/_app/website-foundation/wordpress': {
      id: '/_app/website-foundation/wordpress'
      path: '/wordpress'
      fullPath: '/website-foundation/wordpress'
      preLoaderRoute: typeof AppWebsiteFoundationWordpressRouteImport
      parentRoute: typeof AppWebsiteFoundationRoute
    }
  }
}

interface AppSearchConsoleRouteChildren {
  AppSearchConsoleAmpRoute: typeof AppSearchConsoleAmpRoute
  AppSearchConsoleCountriesRoute: typeof AppSearchConsoleCountriesRoute
  AppSearchConsoleCoverageRoute: typeof AppSearchConsoleCoverageRoute
  AppSearchConsoleCwvRoute: typeof AppSearchConsoleCwvRoute
  AppSearchConsoleDevicesRoute: typeof AppSearchConsoleDevicesRoute
  AppSearchConsoleLinksRoute: typeof AppSearchConsoleLinksRoute
  AppSearchConsoleManualActionsRoute: typeof AppSearchConsoleManualActionsRoute
  AppSearchConsoleMobileUsabilityRoute: typeof AppSearchConsoleMobileUsabilityRoute
  AppSearchConsolePagesRoute: typeof AppSearchConsolePagesRoute
  AppSearchConsolePerformanceRoute: typeof AppSearchConsolePerformanceRoute
  AppSearchConsolePropertyDetailsRoute: typeof AppSearchConsolePropertyDetailsRoute
  AppSearchConsoleQueriesRoute: typeof AppSearchConsoleQueriesRoute
  AppSearchConsoleSitemapsRoute: typeof AppSearchConsoleSitemapsRoute
  AppSearchConsoleUrlInspectionRoute: typeof AppSearchConsoleUrlInspectionRoute
  AppSearchConsoleVerificationRoute: typeof AppSearchConsoleVerificationRoute
  AppSearchConsoleIndexRoute: typeof AppSearchConsoleIndexRoute
}

const AppSearchConsoleRouteChildren: AppSearchConsoleRouteChildren = {
  AppSearchConsoleAmpRoute: AppSearchConsoleAmpRoute,
  AppSearchConsoleCountriesRoute: AppSearchConsoleCountriesRoute,
  AppSearchConsoleCoverageRoute: AppSearchConsoleCoverageRoute,
  AppSearchConsoleCwvRoute: AppSearchConsoleCwvRoute,
  AppSearchConsoleDevicesRoute: AppSearchConsoleDevicesRoute,
  AppSearchConsoleLinksRoute: AppSearchConsoleLinksRoute,
  AppSearchConsoleManualActionsRoute: AppSearchConsoleManualActionsRoute,
  AppSearchConsoleMobileUsabilityRoute: AppSearchConsoleMobileUsabilityRoute,
  AppSearchConsolePagesRoute: AppSearchConsolePagesRoute,
  AppSearchConsolePerformanceRoute: AppSearchConsolePerformanceRoute,
  AppSearchConsolePropertyDetailsRoute: AppSearchConsolePropertyDetailsRoute,
  AppSearchConsoleQueriesRoute: AppSearchConsoleQueriesRoute,
  AppSearchConsoleSitemapsRoute: AppSearchConsoleSitemapsRoute,
  AppSearchConsoleUrlInspectionRoute: AppSearchConsoleUrlInspectionRoute,
  AppSearchConsoleVerificationRoute: AppSearchConsoleVerificationRoute,
  AppSearchConsoleIndexRoute: AppSearchConsoleIndexRoute,
}

const AppSearchConsoleRouteWithChildren =
  AppSearchConsoleRoute._addFileChildren(AppSearchConsoleRouteChildren)

interface AppSearchKnowledgeRouteChildren {
  AppSearchKnowledgeAlgorithmUpdatesRoute: typeof AppSearchKnowledgeAlgorithmUpdatesRoute
  AppSearchKnowledgeDocumentationRoute: typeof AppSearchKnowledgeDocumentationRoute
  AppSearchKnowledgeKnowledgeBaseRoute: typeof AppSearchKnowledgeKnowledgeBaseRoute
  AppSearchKnowledgeSearchOperatorsRoute: typeof AppSearchKnowledgeSearchOperatorsRoute
  AppSearchKnowledgeSerpFeaturesRoute: typeof AppSearchKnowledgeSerpFeaturesRoute
  AppSearchKnowledgeSyncLogsRoute: typeof AppSearchKnowledgeSyncLogsRoute
  AppSearchKnowledgeVersionsRoute: typeof AppSearchKnowledgeVersionsRoute
  AppSearchKnowledgeIndexRoute: typeof AppSearchKnowledgeIndexRoute
}

const AppSearchKnowledgeRouteChildren: AppSearchKnowledgeRouteChildren = {
  AppSearchKnowledgeAlgorithmUpdatesRoute:
    AppSearchKnowledgeAlgorithmUpdatesRoute,
  AppSearchKnowledgeDocumentationRoute: AppSearchKnowledgeDocumentationRoute,
  AppSearchKnowledgeKnowledgeBaseRoute: AppSearchKnowledgeKnowledgeBaseRoute,
  AppSearchKnowledgeSearchOperatorsRoute:
    AppSearchKnowledgeSearchOperatorsRoute,
  AppSearchKnowledgeSerpFeaturesRoute: AppSearchKnowledgeSerpFeaturesRoute,
  AppSearchKnowledgeSyncLogsRoute: AppSearchKnowledgeSyncLogsRoute,
  AppSearchKnowledgeVersionsRoute: AppSearchKnowledgeVersionsRoute,
  AppSearchKnowledgeIndexRoute: AppSearchKnowledgeIndexRoute,
}

const AppSearchKnowledgeRouteWithChildren =
  AppSearchKnowledgeRoute._addFileChildren(AppSearchKnowledgeRouteChildren)

interface AppWebsiteFoundationRouteChildren {
  AppWebsiteFoundationBrandRoute: typeof AppWebsiteFoundationBrandRoute
  AppWebsiteFoundationFormsRoute: typeof AppWebsiteFoundationFormsRoute
  AppWebsiteFoundationInventoryRoute: typeof AppWebsiteFoundationInventoryRoute
  AppWebsiteFoundationOverviewRoute: typeof AppWebsiteFoundationOverviewRoute
  AppWebsiteFoundationPerformanceRoute: typeof AppWebsiteFoundationPerformanceRoute
  AppWebsiteFoundationPluginsRoute: typeof AppWebsiteFoundationPluginsRoute
  AppWebsiteFoundationResponsiveRoute: typeof AppWebsiteFoundationResponsiveRoute
  AppWebsiteFoundationSslRoute: typeof AppWebsiteFoundationSslRoute
  AppWebsiteFoundationThemesRoute: typeof AppWebsiteFoundationThemesRoute
  AppWebsiteFoundationWizardRoute: typeof AppWebsiteFoundationWizardRoute
  AppWebsiteFoundationWordpressRoute: typeof AppWebsiteFoundationWordpressRoute
  AppWebsiteFoundationIndexRoute: typeof AppWebsiteFoundationIndexRoute
}

const AppWebsiteFoundationRouteChildren: AppWebsiteFoundationRouteChildren = {
  AppWebsiteFoundationBrandRoute: AppWebsiteFoundationBrandRoute,
  AppWebsiteFoundationFormsRoute: AppWebsiteFoundationFormsRoute,
  AppWebsiteFoundationInventoryRoute: AppWebsiteFoundationInventoryRoute,
  AppWebsiteFoundationOverviewRoute: AppWebsiteFoundationOverviewRoute,
  AppWebsiteFoundationPerformanceRoute: AppWebsiteFoundationPerformanceRoute,
  AppWebsiteFoundationPluginsRoute: AppWebsiteFoundationPluginsRoute,
  AppWebsiteFoundationResponsiveRoute: AppWebsiteFoundationResponsiveRoute,
  AppWebsiteFoundationSslRoute: AppWebsiteFoundationSslRoute,
  AppWebsiteFoundationThemesRoute: AppWebsiteFoundationThemesRoute,
  AppWebsiteFoundationWizardRoute: AppWebsiteFoundationWizardRoute,
  AppWebsiteFoundationWordpressRoute: AppWebsiteFoundationWordpressRoute,
  AppWebsiteFoundationIndexRoute: AppWebsiteFoundationIndexRoute,
}

const AppWebsiteFoundationRouteWithChildren =
  AppWebsiteFoundationRoute._addFileChildren(AppWebsiteFoundationRouteChildren)

interface AppRouteChildren {
  AppSearchConsoleRoute: typeof AppSearchConsoleRouteWithChildren
  AppSearchKnowledgeRoute: typeof AppSearchKnowledgeRouteWithChildren
  AppWebsiteFoundationRoute: typeof AppWebsiteFoundationRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppTrackingFoundationAuditRoute: typeof AppTrackingFoundationAuditRoute
  AppTrackingFoundationConsentRoute: typeof AppTrackingFoundationConsentRoute
  AppTrackingFoundationEventsRoute: typeof AppTrackingFoundationEventsRoute
  AppTrackingFoundationFormsRoute: typeof AppTrackingFoundationFormsRoute
  AppTrackingFoundationMeasurementPlanRoute: typeof AppTrackingFoundationMeasurementPlanRoute
  AppTrackingFoundationRoutingRoute: typeof AppTrackingFoundationRoutingRoute
  AppTrackingFoundationSubmissionsRoute: typeof AppTrackingFoundationSubmissionsRoute
  AppTrackingFoundationTrackingRoute: typeof AppTrackingFoundationTrackingRoute
  AppTrackingFoundationValidationRoute: typeof AppTrackingFoundationValidationRoute
  AppTrackingFoundationVerificationRoute: typeof AppTrackingFoundationVerificationRoute
  AppTrackingActivityLogsRoute: typeof AppTrackingActivityLogsRoute
  AppTrackingApprovalsRoute: typeof AppTrackingApprovalsRoute
  AppTrackingAuditLogsRoute: typeof AppTrackingAuditLogsRoute
  AppTrackingBusinessGoalsRoute: typeof AppTrackingBusinessGoalsRoute
  AppTrackingConfigurationRoute: typeof AppTrackingConfigurationRoute
  AppTrackingConsentRoute: typeof AppTrackingConsentRoute
  AppTrackingContactFormsRoute: typeof AppTrackingContactFormsRoute
  AppTrackingConversionStrategyRoute: typeof AppTrackingConversionStrategyRoute
  AppTrackingDeliveryLogsRoute: typeof AppTrackingDeliveryLogsRoute
  AppTrackingEventsRoute: typeof AppTrackingEventsRoute
  AppTrackingFormBuilderRoute: typeof AppTrackingFormBuilderRoute
  AppTrackingKpiManagementRoute: typeof AppTrackingKpiManagementRoute
  AppTrackingMeasurementPlanRoute: typeof AppTrackingMeasurementPlanRoute
  AppTrackingOperationsRoute: typeof AppTrackingOperationsRoute
  AppTrackingProvidersRoute: typeof AppTrackingProvidersRoute
  AppTrackingRetryLogsRoute: typeof AppTrackingRetryLogsRoute
  AppTrackingRoutingRoute: typeof AppTrackingRoutingRoute
  AppTrackingSettingsRoute: typeof AppTrackingSettingsRoute
  AppTrackingSpamProtectionRoute: typeof AppTrackingSpamProtectionRoute
  AppTrackingSubmissionsRoute: typeof AppTrackingSubmissionsRoute
  AppTrackingTestingRoute: typeof AppTrackingTestingRoute
  AppTrackingVerificationRoute: typeof AppTrackingVerificationRoute
  AppAuditIndexRoute: typeof AppAuditIndexRoute
  AppBusinessKeywordCompetitorIndexRoute: typeof AppBusinessKeywordCompetitorIndexRoute
  AppBusinessProfileIndexRoute: typeof AppBusinessProfileIndexRoute
  AppBusinessIndexRoute: typeof AppBusinessIndexRoute
  AppCompetitorsIndexRoute: typeof AppCompetitorsIndexRoute
  AppFoundationIndexRoute: typeof AppFoundationIndexRoute
  AppGoogleProductsIndexRoute: typeof AppGoogleProductsIndexRoute
  AppKeywordsIndexRoute: typeof AppKeywordsIndexRoute
  AppMobileIndexRoute: typeof AppMobileIndexRoute
  AppOnpageSeoIndexRoute: typeof AppOnpageSeoIndexRoute
  AppPerformanceIndexRoute: typeof AppPerformanceIndexRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
  AppSeoAnalyzerIndexRoute: typeof AppSeoAnalyzerIndexRoute
  AppSeoIndexRoute: typeof AppSeoIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppTrackingFoundationIndexRoute: typeof AppTrackingFoundationIndexRoute
  AppTrackingIndexRoute: typeof AppTrackingIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSearchConsoleRoute: AppSearchConsoleRouteWithChildren,
  AppSearchKnowledgeRoute: AppSearchKnowledgeRouteWithChildren,
  AppWebsiteFoundationRoute: AppWebsiteFoundationRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppTrackingFoundationAuditRoute: AppTrackingFoundationAuditRoute,
  AppTrackingFoundationConsentRoute: AppTrackingFoundationConsentRoute,
  AppTrackingFoundationEventsRoute: AppTrackingFoundationEventsRoute,
  AppTrackingFoundationFormsRoute: AppTrackingFoundationFormsRoute,
  AppTrackingFoundationMeasurementPlanRoute:
    AppTrackingFoundationMeasurementPlanRoute,
  AppTrackingFoundationRoutingRoute: AppTrackingFoundationRoutingRoute,
  AppTrackingFoundationSubmissionsRoute: AppTrackingFoundationSubmissionsRoute,
  AppTrackingFoundationTrackingRoute: AppTrackingFoundationTrackingRoute,
  AppTrackingFoundationValidationRoute: AppTrackingFoundationValidationRoute,
  AppTrackingFoundationVerificationRoute:
    AppTrackingFoundationVerificationRoute,
  AppTrackingActivityLogsRoute: AppTrackingActivityLogsRoute,
  AppTrackingApprovalsRoute: AppTrackingApprovalsRoute,
  AppTrackingAuditLogsRoute: AppTrackingAuditLogsRoute,
  AppTrackingBusinessGoalsRoute: AppTrackingBusinessGoalsRoute,
  AppTrackingConfigurationRoute: AppTrackingConfigurationRoute,
  AppTrackingConsentRoute: AppTrackingConsentRoute,
  AppTrackingContactFormsRoute: AppTrackingContactFormsRoute,
  AppTrackingConversionStrategyRoute: AppTrackingConversionStrategyRoute,
  AppTrackingDeliveryLogsRoute: AppTrackingDeliveryLogsRoute,
  AppTrackingEventsRoute: AppTrackingEventsRoute,
  AppTrackingFormBuilderRoute: AppTrackingFormBuilderRoute,
  AppTrackingKpiManagementRoute: AppTrackingKpiManagementRoute,
  AppTrackingMeasurementPlanRoute: AppTrackingMeasurementPlanRoute,
  AppTrackingOperationsRoute: AppTrackingOperationsRoute,
  AppTrackingProvidersRoute: AppTrackingProvidersRoute,
  AppTrackingRetryLogsRoute: AppTrackingRetryLogsRoute,
  AppTrackingRoutingRoute: AppTrackingRoutingRoute,
  AppTrackingSettingsRoute: AppTrackingSettingsRoute,
  AppTrackingSpamProtectionRoute: AppTrackingSpamProtectionRoute,
  AppTrackingSubmissionsRoute: AppTrackingSubmissionsRoute,
  AppTrackingTestingRoute: AppTrackingTestingRoute,
  AppTrackingVerificationRoute: AppTrackingVerificationRoute,
  AppAuditIndexRoute: AppAuditIndexRoute,
  AppBusinessKeywordCompetitorIndexRoute:
    AppBusinessKeywordCompetitorIndexRoute,
  AppBusinessProfileIndexRoute: AppBusinessProfileIndexRoute,
  AppBusinessIndexRoute: AppBusinessIndexRoute,
  AppCompetitorsIndexRoute: AppCompetitorsIndexRoute,
  AppFoundationIndexRoute: AppFoundationIndexRoute,
  AppGoogleProductsIndexRoute: AppGoogleProductsIndexRoute,
  AppKeywordsIndexRoute: AppKeywordsIndexRoute,
  AppMobileIndexRoute: AppMobileIndexRoute,
  AppOnpageSeoIndexRoute: AppOnpageSeoIndexRoute,
  AppPerformanceIndexRoute: AppPerformanceIndexRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
  AppSeoAnalyzerIndexRoute: AppSeoAnalyzerIndexRoute,
  AppSeoIndexRoute: AppSeoIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppTrackingFoundationIndexRoute: AppTrackingFoundationIndexRoute,
  AppTrackingIndexRoute: AppTrackingIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
