import type { LucideIcon } from "lucide-react";
import {
  Brain,
  TrendingUp,
  Eye,
  Target,
  Award,
  Search,
  Compass,
  Users,
  BarChart3,
  Sparkles,
  ShieldCheck,
  Zap,
  MapPin,
  AlertTriangle,
  Activity,
  Clock,
  FileText,
  Download,
  RefreshCw,
  Plus,
  Trash2,
  Settings,
  ChevronDown,
  ChevronUp,
  ArrowUpRight,
  ArrowDownRight,
  Minus,
  Filter,
  X,
  CheckCircle2,
  XCircle,
  AlertCircle,
  Info,
  Star,
  Flame,
  DollarSign,
  TrendingDown,
  TrendingUp as TrendingUpIcon,
  Minimize2,
  Maximize2,
  Table2,
  ChartBar,
  PieChart,
  LineChart,
  Layers,
  FolderOpen,
  Tag,
  Hash,
  Globe,
  Server,
  Database,
  GitBranch,
  Split,
  Merge,
  Filter as FilterIcon,
  SortAsc,
  SortDesc,
  Columns,
  Copy,
  Share2,
  Printer,
  Mail,
  Bell,
  Bookmark,
  Flag,
  Rocket,
  Lightbulb,
  Wand2,
  Bot,
  Cpu,
  Gauge,
  Ruler,
  Scale,
  TrendingUp as TrendUp,
  TrendingDown as TrendDown,
  Minimize as MinimizeIcon,
  Maximize as MaximizeIcon,
  ZoomIn,
  ZoomOut,
  Move,
  GripVertical,
  GripHorizontal,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  Home,
  Menu,
  Settings2,
  HelpCircle,
  InfoIcon,
  Check,
  AlertTriangle as AlertTriangleIcon,
  Circle,
  Square,
  Triangle,
  Diamond,
  Hexagon,
  Pentagon,
  Octagon,
  Star as StarIcon,
  Circle as CircleIcon,
  Square as SquareIcon,
  Triangle as TriangleIcon,
} from "lucide-react";

export const API_BASE = import.meta.env.VITE_API_URL || "http://localhost:8000/api/v1";

export const F05_NAV = [
  { label: "Overview", value: "overview", icon: Activity },
  { label: "Business Profile", value: "business-profile", icon: Globe },
  { label: "Keyword Universe", value: "keyword-universe", icon: Database },
  { label: "Keyword Clusters", value: "keyword-clusters", icon: Layers },
  { label: "Keyword Opportunities", value: "keyword-opportunities", icon: Sparkles },
  { label: "Search Intent", value: "search-intent", icon: Compass },
  { label: "Competitors", value: "competitors", icon: Users },
  { label: "Ranking Analysis", value: "ranking-analysis", icon: ChartBar },
  { label: "SERP Analysis", value: "serp-analysis", icon: Eye },
  { label: "Topic Clusters", value: "topic-clusters", icon: GitBranch },
  { label: "Content Gaps", value: "content-gaps", icon: AlertTriangle },
  { label: "Search Trends", value: "search-trends", icon: TrendingUp },
  { label: "AI Recommendations", value: "ai-recommendations", icon: Brain },
  { label: "Reports", value: "reports", icon: FileText },
  { label: "History", value: "history", icon: Clock },
  { label: "Logs", value: "logs", icon: AlertCircle },
  { label: "Settings", value: "settings", icon: Settings2 },
] as const;

export const INTENT_COLORS = {
  informational: "bg-blue-500/10 text-blue-500 border-blue-500/20",
  navigational: "bg-green-500/10 text-green-500 border-green-500/20",
  commercial: "bg-amber-500/10 text-amber-500 border-amber-500/20",
  transactional: "bg-purple-500/10 text-purple-500 border-purple-500/20",
  local: "bg-emerald-500/10 text-emerald-500 border-emerald-500/20",
  branded: "bg-indigo-500/10 text-indigo-500 border-indigo-500/20",
  question: "bg-cyan-500/10 text-cyan-500 border-cyan-500/20",
};

export const STATUS_COLORS = {
  active: "bg-success/10 text-success border-success/20",
  inactive: "bg-muted text-muted-foreground border-border",
  pending: "bg-warning/15 text-warning-foreground border-warning/30",
  error: "bg-destructive/10 text-destructive border-destructive/20",
  tracking: "bg-success/10 text-success border-success/20",
  lost: "bg-destructive/10 text-destructive border-destructive/20",
  new: "bg-info/10 text-info border-info/20",
  improved: "bg-success/10 text-success border-success/20",
  declined: "bg-destructive/10 text-destructive border-destructive/20",
  completed: "bg-success/10 text-success border-success/20",
  failed: "bg-destructive/10 text-destructive border-destructive/20",
  running: "bg-info/10 text-info border-info/20",
  critical: "bg-destructive/10 text-destructive border-destructive/20",
  high: "bg-warning/15 text-warning-foreground border-warning/30",
  medium: "bg-muted text-muted-foreground border-border",
  low: "bg-muted text-muted-foreground border-border",
  easy: "bg-success/10 text-success border-success/20",
  moderate: "bg-warning/15 text-warning-foreground border-warning/30",
  hard: "bg-destructive/10 text-destructive border-destructive/20",
  good: "bg-success/10 text-success border-success/20",
  warning: "bg-warning/15 text-warning-foreground border-warning/30",
  poor: "bg-destructive/10 text-destructive border-destructive/20",
};

export const DIFFICULTY_COLORS = {
  easy: "bg-success/10 text-success",
  medium: "bg-warning/15 text-warning-foreground",
  hard: "bg-destructive/10 text-destructive",
};

export const PRIORITY_ORDER = { critical: 0, high: 1, medium: 2, low: 3 } as const;

export const SEARCH_INTENTS = [
  "informational",
  "navigational",
  "commercial",
  "transactional",
  "local",
  "branded",
  "question",
] as const;

export const KEYWORD_TYPES = ["seed", "long-tail", "competitor", "opportunity", "trending"] as const;

export const EXPORT_FORMATS = ["csv", "xlsx", "pdf"] as const;

export const ARROW_UP = ArrowUpRight;
export const ARROW_DOWN = ArrowDownRight;
export const ARROW_FLAT = Minus;