/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppBusinessProfileRouteImport } from './routes/_app.business-profile'
import { Route as AppCompetitorsRouteImport } from './routes/_app.competitors'
import { Route as AppGoogleProductsRouteImport } from './routes/_app.google-products'
import { Route as AppKeywordsRouteImport } from './routes/_app.keywords'
import { Route as AppMobileRouteImport } from './routes/_app.mobile'
import { Route as AppPerformanceRouteImport } from './routes/_app.performance'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppSearchConsoleRouteImport } from './routes/_app.search-console'
import { Route as AppSearchKnowledgeRouteImport } from './routes/_app.search-knowledge'
import { Route as AppSeoAnalyzerRouteImport } from './routes/_app.seo-analyzer'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppTrackingRouteImport } from './routes/_app.tracking'
import { Route as AppWebsiteFoundationRouteImport } from './routes/_app.website-foundation'
import { Route as AppSearchConsoleIndexRouteImport } from './routes/_app.search-console._index'
import { Route as AppSearchConsoleAmpRouteImport } from './routes/_app.search-console.amp'
import { Route as AppSearchConsoleCountriesRouteImport } from './routes/_app.search-console.countries'
import { Route as AppSearchConsoleCoverageRouteImport } from './routes/_app.search-console.coverage'
import { Route as AppSearchConsoleCwvRouteImport } from './routes/_app.search-console.cwv'
import { Route as AppSearchConsoleDevicesRouteImport } from './routes/_app.search-console.devices'
import { Route as AppSearchConsoleLinksRouteImport } from './routes/_app.search-console.links'
import { Route as AppSearchConsoleManualActionsRouteImport } from './routes/_app.search-console.manual-actions'
import { Route as AppSearchConsoleMobileUsabilityRouteImport } from './routes/_app.search-console.mobile-usability'
import { Route as AppSearchConsolePagesRouteImport } from './routes/_app.search-console.pages'
import { Route as AppSearchConsolePerformanceRouteImport } from './routes/_app.search-console.performance'
import { Route as AppSearchConsolePropertyDetailsRouteImport } from './routes/_app.search-console.property-details'
import { Route as AppSearchConsoleQueriesRouteImport } from './routes/_app.search-console.queries'
import { Route as AppSearchConsoleSitemapsRouteImport } from './routes/_app.search-console.sitemaps'
import { Route as AppSearchConsoleUrlInspectionRouteImport } from './routes/_app.search-console.url-inspection'
import { Route as AppSearchConsoleVerificationRouteImport } from './routes/_app.search-console.verification'
import { Route as AppSearchKnowledgeIndexRouteImport } from './routes/_app.search-knowledge._index'
import { Route as AppSearchKnowledgeAiSearchOverviewRouteImport } from './routes/_app.search-knowledge.ai-search-overview'
import { Route as AppSearchKnowledgeFeaturedSnippetsRouteImport } from './routes/_app.search-knowledge.featured-snippets'
import { Route as AppSearchKnowledgeFutureTrendsRouteImport } from './routes/_app.search-knowledge.future-trends'
import { Route as AppSearchKnowledgeGoogleAlgorithmUpdatesRouteImport } from './routes/_app.search-knowledge.google-algorithm-updates'
import { Route as AppSearchKnowledgeGoogleRankingFactorsRouteImport } from './routes/_app.search-knowledge.google-ranking-factors'
import { Route as AppSearchKnowledgeGoogleSearchArchitectureRouteImport } from './routes/_app.search-knowledge.google-search-architecture'
import { Route as AppSearchKnowledgeImageSearchRouteImport } from './routes/_app.search-knowledge.image-search'
import { Route as AppSearchKnowledgeKnowledgeGraphRouteImport } from './routes/_app.search-knowledge.knowledge-graph'
import { Route as AppSearchKnowledgeLocalSearchRouteImport } from './routes/_app.search-knowledge.local-search'
import { Route as AppSearchKnowledgeNewsSearchRouteImport } from './routes/_app.search-knowledge.news-search'
import { Route as AppSearchKnowledgePeopleAlsoAskRouteImport } from './routes/_app.search-knowledge.people-also-ask'
import { Route as AppSearchKnowledgeRichResultsRouteImport } from './routes/_app.search-knowledge.rich-results'
import { Route as AppSearchKnowledgeSearchIntentRouteImport } from './routes/_app.search-knowledge.search-intent'
import { Route as AppSearchKnowledgeSearchOperatorsRouteImport } from './routes/_app.search-knowledge.search-operators'
import { Route as AppSearchKnowledgeSerpLayoutRouteImport } from './routes/_app.search-knowledge.serp-layout'
import { Route as AppSearchKnowledgeShoppingSearchRouteImport } from './routes/_app.search-knowledge.shopping-search'
import { Route as AppSearchKnowledgeVideoSearchRouteImport } from './routes/_app.search-knowledge.video-search'
import { Route as AppSearchKnowledgeVoiceSearchRouteImport } from './routes/_app.search-knowledge.voice-search'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBusinessProfileRoute = AppBusinessProfileRouteImport.update({
  id: '/business-profile',
  path: '/business-profile',
  getParentRoute: () => AppRoute,
} as any)
const AppCompetitorsRoute = AppCompetitorsRouteImport.update({
  id: '/competitors',
  path: '/competitors',
  getParentRoute: () => AppRoute,
} as any)
const AppGoogleProductsRoute = AppGoogleProductsRouteImport.update({
  id: '/google-products',
  path: '/google-products',
  getParentRoute: () => AppRoute,
} as any)
const AppKeywordsRoute = AppKeywordsRouteImport.update({
  id: '/keywords',
  path: '/keywords',
  getParentRoute: () => AppRoute,
} as any)
const AppMobileRoute = AppMobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceRoute = AppPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchConsoleRoute = AppSearchConsoleRouteImport.update({
  id: '/search-console',
  path: '/search-console',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchKnowledgeRoute = AppSearchKnowledgeRouteImport.update({
  id: '/search-knowledge',
  path: '/search-knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppSeoAnalyzerRoute = AppSeoAnalyzerRouteImport.update({
  id: '/seo-analyzer',
  path: '/seo-analyzer',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackingRoute = AppTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => AppRoute,
} as any)
const AppWebsiteFoundationRoute = AppWebsiteFoundationRouteImport.update({
  id: '/website-foundation',
  path: '/website-foundation',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchConsoleIndexRoute = AppSearchConsoleIndexRouteImport.update({
  id: '/_index',
  getParentRoute: () => AppSearchConsoleRoute,
} as any)
const AppSearchConsoleAmpRoute = AppSearchConsoleAmpRouteImport.update({
  id: '/amp',
  path: '/amp',
  getParentRoute: () => AppSearchConsoleRoute,
} as any)
const AppSearchConsoleCountriesRoute =
  AppSearchConsoleCountriesRouteImport.update({
    id: '/countries',
    path: '/countries',
    getParentRoute: () => AppSearchConsoleRoute,
  } as any)
const AppSearchConsoleCoverageRoute =
  AppSearchConsoleCoverageRouteImport.update({
    id: '/coverage',
    path: '/coverage',
    getParentRoute: () => AppSearchConsoleRoute,
  } as any)
const AppSearchConsoleCwvRoute = AppSearchConsoleCwvRouteImport.update({
  id: '/cwv',
  path: '/cwv',
  getParentRoute: () => AppSearchConsoleRoute,
} as any)
const AppSearchConsoleDevicesRoute = AppSearchConsoleDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AppSearchConsoleRoute,
} as any)
const AppSearchConsoleLinksRoute = AppSearchConsoleLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AppSearchConsoleRoute,
} as any)
const AppSearchConsoleManualActionsRoute =
  AppSearchConsoleManualActionsRouteImport.update({
    id: '/manual-actions',
    path: '/manual-actions',
    getParentRoute: () => AppSearchConsoleRoute,
  } as any)
const AppSearchConsoleMobileUsabilityRoute =
  AppSearchConsoleMobileUsabilityRouteImport.update({
    id: '/mobile-usability',
    path: '/mobile-usability',
    getParentRoute: () => AppSearchConsoleRoute,
  } as any)
const AppSearchConsolePagesRoute = AppSearchConsolePagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AppSearchConsoleRoute,
} as any)
const AppSearchConsolePerformanceRoute =
  AppSearchConsolePerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AppSearchConsoleRoute,
  } as any)
const AppSearchConsolePropertyDetailsRoute =
  AppSearchConsolePropertyDetailsRouteImport.update({
    id: '/property-details',
    path: '/property-details',
    getParentRoute: () => AppSearchConsoleRoute,
  } as any)
const AppSearchConsoleQueriesRoute = AppSearchConsoleQueriesRouteImport.update({
  id: '/queries',
  path: '/queries',
  getParentRoute: () => AppSearchConsoleRoute,
} as any)
const AppSearchConsoleSitemapsRoute =
  AppSearchConsoleSitemapsRouteImport.update({
    id: '/sitemaps',
    path: '/sitemaps',
    getParentRoute: () => AppSearchConsoleRoute,
  } as any)
const AppSearchConsoleUrlInspectionRoute =
  AppSearchConsoleUrlInspectionRouteImport.update({
    id: '/url-inspection',
    path: '/url-inspection',
    getParentRoute: () => AppSearchConsoleRoute,
  } as any)
const AppSearchConsoleVerificationRoute =
  AppSearchConsoleVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => AppSearchConsoleRoute,
  } as any)
const AppSearchKnowledgeIndexRoute = AppSearchKnowledgeIndexRouteImport.update({
  id: '/_index',
  getParentRoute: () => AppSearchKnowledgeRoute,
} as any)
const AppSearchKnowledgeAiSearchOverviewRoute =
  AppSearchKnowledgeAiSearchOverviewRouteImport.update({
    id: '/ai-search-overview',
    path: '/ai-search-overview',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgeFeaturedSnippetsRoute =
  AppSearchKnowledgeFeaturedSnippetsRouteImport.update({
    id: '/featured-snippets',
    path: '/featured-snippets',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgeFutureTrendsRoute =
  AppSearchKnowledgeFutureTrendsRouteImport.update({
    id: '/future-trends',
    path: '/future-trends',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgeGoogleAlgorithmUpdatesRoute =
  AppSearchKnowledgeGoogleAlgorithmUpdatesRouteImport.update({
    id: '/google-algorithm-updates',
    path: '/google-algorithm-updates',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgeGoogleRankingFactorsRoute =
  AppSearchKnowledgeGoogleRankingFactorsRouteImport.update({
    id: '/google-ranking-factors',
    path: '/google-ranking-factors',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgeGoogleSearchArchitectureRoute =
  AppSearchKnowledgeGoogleSearchArchitectureRouteImport.update({
    id: '/google-search-architecture',
    path: '/google-search-architecture',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgeImageSearchRoute =
  AppSearchKnowledgeImageSearchRouteImport.update({
    id: '/image-search',
    path: '/image-search',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgeKnowledgeGraphRoute =
  AppSearchKnowledgeKnowledgeGraphRouteImport.update({
    id: '/knowledge-graph',
    path: '/knowledge-graph',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgeLocalSearchRoute =
  AppSearchKnowledgeLocalSearchRouteImport.update({
    id: '/local-search',
    path: '/local-search',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgeNewsSearchRoute =
  AppSearchKnowledgeNewsSearchRouteImport.update({
    id: '/news-search',
    path: '/news-search',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgePeopleAlsoAskRoute =
  AppSearchKnowledgePeopleAlsoAskRouteImport.update({
    id: '/people-also-ask',
    path: '/people-also-ask',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgeRichResultsRoute =
  AppSearchKnowledgeRichResultsRouteImport.update({
    id: '/rich-results',
    path: '/rich-results',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgeSearchIntentRoute =
  AppSearchKnowledgeSearchIntentRouteImport.update({
    id: '/search-intent',
    path: '/search-intent',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgeSearchOperatorsRoute =
  AppSearchKnowledgeSearchOperatorsRouteImport.update({
    id: '/search-operators',
    path: '/search-operators',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgeSerpLayoutRoute =
  AppSearchKnowledgeSerpLayoutRouteImport.update({
    id: '/serp-layout',
    path: '/serp-layout',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgeShoppingSearchRoute =
  AppSearchKnowledgeShoppingSearchRouteImport.update({
    id: '/shopping-search',
    path: '/shopping-search',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgeVideoSearchRoute =
  AppSearchKnowledgeVideoSearchRouteImport.update({
    id: '/video-search',
    path: '/video-search',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)
const AppSearchKnowledgeVoiceSearchRoute =
  AppSearchKnowledgeVoiceSearchRouteImport.update({
    id: '/voice-search',
    path: '/voice-search',
    getParentRoute: () => AppSearchKnowledgeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/business-profile': typeof AppBusinessProfileRoute
  '/competitors': typeof AppCompetitorsRoute
  '/google-products': typeof AppGoogleProductsRoute
  '/keywords': typeof AppKeywordsRoute
  '/mobile': typeof AppMobileRoute
  '/performance': typeof AppPerformanceRoute
  '/reports': typeof AppReportsRoute
  '/search-console': typeof AppSearchConsoleRouteWithChildren
  '/search-knowledge': typeof AppSearchKnowledgeRouteWithChildren
  '/seo-analyzer': typeof AppSeoAnalyzerRoute
  '/settings': typeof AppSettingsRoute
  '/tracking': typeof AppTrackingRoute
  '/website-foundation': typeof AppWebsiteFoundationRoute
  '/search-console/amp': typeof AppSearchConsoleAmpRoute
  '/search-console/countries': typeof AppSearchConsoleCountriesRoute
  '/search-console/coverage': typeof AppSearchConsoleCoverageRoute
  '/search-console/cwv': typeof AppSearchConsoleCwvRoute
  '/search-console/devices': typeof AppSearchConsoleDevicesRoute
  '/search-console/links': typeof AppSearchConsoleLinksRoute
  '/search-console/manual-actions': typeof AppSearchConsoleManualActionsRoute
  '/search-console/mobile-usability': typeof AppSearchConsoleMobileUsabilityRoute
  '/search-console/pages': typeof AppSearchConsolePagesRoute
  '/search-console/performance': typeof AppSearchConsolePerformanceRoute
  '/search-console/property-details': typeof AppSearchConsolePropertyDetailsRoute
  '/search-console/queries': typeof AppSearchConsoleQueriesRoute
  '/search-console/sitemaps': typeof AppSearchConsoleSitemapsRoute
  '/search-console/url-inspection': typeof AppSearchConsoleUrlInspectionRoute
  '/search-console/verification': typeof AppSearchConsoleVerificationRoute
  '/search-knowledge/ai-search-overview': typeof AppSearchKnowledgeAiSearchOverviewRoute
  '/search-knowledge/featured-snippets': typeof AppSearchKnowledgeFeaturedSnippetsRoute
  '/search-knowledge/future-trends': typeof AppSearchKnowledgeFutureTrendsRoute
  '/search-knowledge/google-algorithm-updates': typeof AppSearchKnowledgeGoogleAlgorithmUpdatesRoute
  '/search-knowledge/google-ranking-factors': typeof AppSearchKnowledgeGoogleRankingFactorsRoute
  '/search-knowledge/google-search-architecture': typeof AppSearchKnowledgeGoogleSearchArchitectureRoute
  '/search-knowledge/image-search': typeof AppSearchKnowledgeImageSearchRoute
  '/search-knowledge/knowledge-graph': typeof AppSearchKnowledgeKnowledgeGraphRoute
  '/search-knowledge/local-search': typeof AppSearchKnowledgeLocalSearchRoute
  '/search-knowledge/news-search': typeof AppSearchKnowledgeNewsSearchRoute
  '/search-knowledge/people-also-ask': typeof AppSearchKnowledgePeopleAlsoAskRoute
  '/search-knowledge/rich-results': typeof AppSearchKnowledgeRichResultsRoute
  '/search-knowledge/search-intent': typeof AppSearchKnowledgeSearchIntentRoute
  '/search-knowledge/search-operators': typeof AppSearchKnowledgeSearchOperatorsRoute
  '/search-knowledge/serp-layout': typeof AppSearchKnowledgeSerpLayoutRoute
  '/search-knowledge/shopping-search': typeof AppSearchKnowledgeShoppingSearchRoute
  '/search-knowledge/video-search': typeof AppSearchKnowledgeVideoSearchRoute
  '/search-knowledge/voice-search': typeof AppSearchKnowledgeVoiceSearchRoute
}
export interface FileRoutesByTo {
  '/business-profile': typeof AppBusinessProfileRoute
  '/competitors': typeof AppCompetitorsRoute
  '/google-products': typeof AppGoogleProductsRoute
  '/keywords': typeof AppKeywordsRoute
  '/mobile': typeof AppMobileRoute
  '/performance': typeof AppPerformanceRoute
  '/reports': typeof AppReportsRoute
  '/search-console': typeof AppSearchConsoleRouteWithChildren
  '/search-knowledge': typeof AppSearchKnowledgeRouteWithChildren
  '/seo-analyzer': typeof AppSeoAnalyzerRoute
  '/settings': typeof AppSettingsRoute
  '/tracking': typeof AppTrackingRoute
  '/website-foundation': typeof AppWebsiteFoundationRoute
  '/': typeof AppIndexRoute
  '/search-console/amp': typeof AppSearchConsoleAmpRoute
  '/search-console/countries': typeof AppSearchConsoleCountriesRoute
  '/search-console/coverage': typeof AppSearchConsoleCoverageRoute
  '/search-console/cwv': typeof AppSearchConsoleCwvRoute
  '/search-console/devices': typeof AppSearchConsoleDevicesRoute
  '/search-console/links': typeof AppSearchConsoleLinksRoute
  '/search-console/manual-actions': typeof AppSearchConsoleManualActionsRoute
  '/search-console/mobile-usability': typeof AppSearchConsoleMobileUsabilityRoute
  '/search-console/pages': typeof AppSearchConsolePagesRoute
  '/search-console/performance': typeof AppSearchConsolePerformanceRoute
  '/search-console/property-details': typeof AppSearchConsolePropertyDetailsRoute
  '/search-console/queries': typeof AppSearchConsoleQueriesRoute
  '/search-console/sitemaps': typeof AppSearchConsoleSitemapsRoute
  '/search-console/url-inspection': typeof AppSearchConsoleUrlInspectionRoute
  '/search-console/verification': typeof AppSearchConsoleVerificationRoute
  '/search-knowledge/ai-search-overview': typeof AppSearchKnowledgeAiSearchOverviewRoute
  '/search-knowledge/featured-snippets': typeof AppSearchKnowledgeFeaturedSnippetsRoute
  '/search-knowledge/future-trends': typeof AppSearchKnowledgeFutureTrendsRoute
  '/search-knowledge/google-algorithm-updates': typeof AppSearchKnowledgeGoogleAlgorithmUpdatesRoute
  '/search-knowledge/google-ranking-factors': typeof AppSearchKnowledgeGoogleRankingFactorsRoute
  '/search-knowledge/google-search-architecture': typeof AppSearchKnowledgeGoogleSearchArchitectureRoute
  '/search-knowledge/image-search': typeof AppSearchKnowledgeImageSearchRoute
  '/search-knowledge/knowledge-graph': typeof AppSearchKnowledgeKnowledgeGraphRoute
  '/search-knowledge/local-search': typeof AppSearchKnowledgeLocalSearchRoute
  '/search-knowledge/news-search': typeof AppSearchKnowledgeNewsSearchRoute
  '/search-knowledge/people-also-ask': typeof AppSearchKnowledgePeopleAlsoAskRoute
  '/search-knowledge/rich-results': typeof AppSearchKnowledgeRichResultsRoute
  '/search-knowledge/search-intent': typeof AppSearchKnowledgeSearchIntentRoute
  '/search-knowledge/search-operators': typeof AppSearchKnowledgeSearchOperatorsRoute
  '/search-knowledge/serp-layout': typeof AppSearchKnowledgeSerpLayoutRoute
  '/search-knowledge/shopping-search': typeof AppSearchKnowledgeShoppingSearchRoute
  '/search-knowledge/video-search': typeof AppSearchKnowledgeVideoSearchRoute
  '/search-knowledge/voice-search': typeof AppSearchKnowledgeVoiceSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/business-profile': typeof AppBusinessProfileRoute
  '/_app/competitors': typeof AppCompetitorsRoute
  '/_app/google-products': typeof AppGoogleProductsRoute
  '/_app/keywords': typeof AppKeywordsRoute
  '/_app/mobile': typeof AppMobileRoute
  '/_app/performance': typeof AppPerformanceRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/search-console': typeof AppSearchConsoleRouteWithChildren
  '/_app/search-knowledge': typeof AppSearchKnowledgeRouteWithChildren
  '/_app/seo-analyzer': typeof AppSeoAnalyzerRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tracking': typeof AppTrackingRoute
  '/_app/website-foundation': typeof AppWebsiteFoundationRoute
  '/_app/': typeof AppIndexRoute
  '/_app/search-console/_index': typeof AppSearchConsoleIndexRoute
  '/_app/search-console/amp': typeof AppSearchConsoleAmpRoute
  '/_app/search-console/countries': typeof AppSearchConsoleCountriesRoute
  '/_app/search-console/coverage': typeof AppSearchConsoleCoverageRoute
  '/_app/search-console/cwv': typeof AppSearchConsoleCwvRoute
  '/_app/search-console/devices': typeof AppSearchConsoleDevicesRoute
  '/_app/search-console/links': typeof AppSearchConsoleLinksRoute
  '/_app/search-console/manual-actions': typeof AppSearchConsoleManualActionsRoute
  '/_app/search-console/mobile-usability': typeof AppSearchConsoleMobileUsabilityRoute
  '/_app/search-console/pages': typeof AppSearchConsolePagesRoute
  '/_app/search-console/performance': typeof AppSearchConsolePerformanceRoute
  '/_app/search-console/property-details': typeof AppSearchConsolePropertyDetailsRoute
  '/_app/search-console/queries': typeof AppSearchConsoleQueriesRoute
  '/_app/search-console/sitemaps': typeof AppSearchConsoleSitemapsRoute
  '/_app/search-console/url-inspection': typeof AppSearchConsoleUrlInspectionRoute
  '/_app/search-console/verification': typeof AppSearchConsoleVerificationRoute
  '/_app/search-knowledge/_index': typeof AppSearchKnowledgeIndexRoute
  '/_app/search-knowledge/ai-search-overview': typeof AppSearchKnowledgeAiSearchOverviewRoute
  '/_app/search-knowledge/featured-snippets': typeof AppSearchKnowledgeFeaturedSnippetsRoute
  '/_app/search-knowledge/future-trends': typeof AppSearchKnowledgeFutureTrendsRoute
  '/_app/search-knowledge/google-algorithm-updates': typeof AppSearchKnowledgeGoogleAlgorithmUpdatesRoute
  '/_app/search-knowledge/google-ranking-factors': typeof AppSearchKnowledgeGoogleRankingFactorsRoute
  '/_app/search-knowledge/google-search-architecture': typeof AppSearchKnowledgeGoogleSearchArchitectureRoute
  '/_app/search-knowledge/image-search': typeof AppSearchKnowledgeImageSearchRoute
  '/_app/search-knowledge/knowledge-graph': typeof AppSearchKnowledgeKnowledgeGraphRoute
  '/_app/search-knowledge/local-search': typeof AppSearchKnowledgeLocalSearchRoute
  '/_app/search-knowledge/news-search': typeof AppSearchKnowledgeNewsSearchRoute
  '/_app/search-knowledge/people-also-ask': typeof AppSearchKnowledgePeopleAlsoAskRoute
  '/_app/search-knowledge/rich-results': typeof AppSearchKnowledgeRichResultsRoute
  '/_app/search-knowledge/search-intent': typeof AppSearchKnowledgeSearchIntentRoute
  '/_app/search-knowledge/search-operators': typeof AppSearchKnowledgeSearchOperatorsRoute
  '/_app/search-knowledge/serp-layout': typeof AppSearchKnowledgeSerpLayoutRoute
  '/_app/search-knowledge/shopping-search': typeof AppSearchKnowledgeShoppingSearchRoute
  '/_app/search-knowledge/video-search': typeof AppSearchKnowledgeVideoSearchRoute
  '/_app/search-knowledge/voice-search': typeof AppSearchKnowledgeVoiceSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/business-profile'
    | '/competitors'
    | '/google-products'
    | '/keywords'
    | '/mobile'
    | '/performance'
    | '/reports'
    | '/search-console'
    | '/search-knowledge'
    | '/seo-analyzer'
    | '/settings'
    | '/tracking'
    | '/website-foundation'
    | '/search-console/amp'
    | '/search-console/countries'
    | '/search-console/coverage'
    | '/search-console/cwv'
    | '/search-console/devices'
    | '/search-console/links'
    | '/search-console/manual-actions'
    | '/search-console/mobile-usability'
    | '/search-console/pages'
    | '/search-console/performance'
    | '/search-console/property-details'
    | '/search-console/queries'
    | '/search-console/sitemaps'
    | '/search-console/url-inspection'
    | '/search-console/verification'
    | '/search-knowledge/ai-search-overview'
    | '/search-knowledge/featured-snippets'
    | '/search-knowledge/future-trends'
    | '/search-knowledge/google-algorithm-updates'
    | '/search-knowledge/google-ranking-factors'
    | '/search-knowledge/google-search-architecture'
    | '/search-knowledge/image-search'
    | '/search-knowledge/knowledge-graph'
    | '/search-knowledge/local-search'
    | '/search-knowledge/news-search'
    | '/search-knowledge/people-also-ask'
    | '/search-knowledge/rich-results'
    | '/search-knowledge/search-intent'
    | '/search-knowledge/search-operators'
    | '/search-knowledge/serp-layout'
    | '/search-knowledge/shopping-search'
    | '/search-knowledge/video-search'
    | '/search-knowledge/voice-search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/business-profile'
    | '/competitors'
    | '/google-products'
    | '/keywords'
    | '/mobile'
    | '/performance'
    | '/reports'
    | '/search-console'
    | '/search-knowledge'
    | '/seo-analyzer'
    | '/settings'
    | '/tracking'
    | '/website-foundation'
    | '/'
    | '/search-console/amp'
    | '/search-console/countries'
    | '/search-console/coverage'
    | '/search-console/cwv'
    | '/search-console/devices'
    | '/search-console/links'
    | '/search-console/manual-actions'
    | '/search-console/mobile-usability'
    | '/search-console/pages'
    | '/search-console/performance'
    | '/search-console/property-details'
    | '/search-console/queries'
    | '/search-console/sitemaps'
    | '/search-console/url-inspection'
    | '/search-console/verification'
    | '/search-knowledge/ai-search-overview'
    | '/search-knowledge/featured-snippets'
    | '/search-knowledge/future-trends'
    | '/search-knowledge/google-algorithm-updates'
    | '/search-knowledge/google-ranking-factors'
    | '/search-knowledge/google-search-architecture'
    | '/search-knowledge/image-search'
    | '/search-knowledge/knowledge-graph'
    | '/search-knowledge/local-search'
    | '/search-knowledge/news-search'
    | '/search-knowledge/people-also-ask'
    | '/search-knowledge/rich-results'
    | '/search-knowledge/search-intent'
    | '/search-knowledge/search-operators'
    | '/search-knowledge/serp-layout'
    | '/search-knowledge/shopping-search'
    | '/search-knowledge/video-search'
    | '/search-knowledge/voice-search'
  id:
    | '__root__'
    | '/_app'
    | '/_app/business-profile'
    | '/_app/competitors'
    | '/_app/google-products'
    | '/_app/keywords'
    | '/_app/mobile'
    | '/_app/performance'
    | '/_app/reports'
    | '/_app/search-console'
    | '/_app/search-knowledge'
    | '/_app/seo-analyzer'
    | '/_app/settings'
    | '/_app/tracking'
    | '/_app/website-foundation'
    | '/_app/'
    | '/_app/search-console/_index'
    | '/_app/search-console/amp'
    | '/_app/search-console/countries'
    | '/_app/search-console/coverage'
    | '/_app/search-console/cwv'
    | '/_app/search-console/devices'
    | '/_app/search-console/links'
    | '/_app/search-console/manual-actions'
    | '/_app/search-console/mobile-usability'
    | '/_app/search-console/pages'
    | '/_app/search-console/performance'
    | '/_app/search-console/property-details'
    | '/_app/search-console/queries'
    | '/_app/search-console/sitemaps'
    | '/_app/search-console/url-inspection'
    | '/_app/search-console/verification'
    | '/_app/search-knowledge/_index'
    | '/_app/search-knowledge/ai-search-overview'
    | '/_app/search-knowledge/featured-snippets'
    | '/_app/search-knowledge/future-trends'
    | '/_app/search-knowledge/google-algorithm-updates'
    | '/_app/search-knowledge/google-ranking-factors'
    | '/_app/search-knowledge/google-search-architecture'
    | '/_app/search-knowledge/image-search'
    | '/_app/search-knowledge/knowledge-graph'
    | '/_app/search-knowledge/local-search'
    | '/_app/search-knowledge/news-search'
    | '/_app/search-knowledge/people-also-ask'
    | '/_app/search-knowledge/rich-results'
    | '/_app/search-knowledge/search-intent'
    | '/_app/search-knowledge/search-operators'
    | '/_app/search-knowledge/serp-layout'
    | '/_app/search-knowledge/shopping-search'
    | '/_app/search-knowledge/video-search'
    | '/_app/search-knowledge/voice-search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/business-profile': {
      id: '/_app/business-profile'
      path: '/business-profile'
      fullPath: '/business-profile'
      preLoaderRoute: typeof AppBusinessProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/competitors': {
      id: '/_app/competitors'
      path: '/competitors'
      fullPath: '/competitors'
      preLoaderRoute: typeof AppCompetitorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/google-products': {
      id: '/_app/google-products'
      path: '/google-products'
      fullPath: '/google-products'
      preLoaderRoute: typeof AppGoogleProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/keywords': {
      id: '/_app/keywords'
      path: '/keywords'
      fullPath: '/keywords'
      preLoaderRoute: typeof AppKeywordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mobile': {
      id: '/_app/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof AppMobileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/performance': {
      id: '/_app/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AppPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search-console': {
      id: '/_app/search-console'
      path: '/search-console'
      fullPath: '/search-console'
      preLoaderRoute: typeof AppSearchConsoleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search-knowledge': {
      id: '/_app/search-knowledge'
      path: '/search-knowledge'
      fullPath: '/search-knowledge'
      preLoaderRoute: typeof AppSearchKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/seo-analyzer': {
      id: '/_app/seo-analyzer'
      path: '/seo-analyzer'
      fullPath: '/seo-analyzer'
      preLoaderRoute: typeof AppSeoAnalyzerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking': {
      id: '/_app/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof AppTrackingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/website-foundation': {
      id: '/_app/website-foundation'
      path: '/website-foundation'
      fullPath: '/website-foundation'
      preLoaderRoute: typeof AppWebsiteFoundationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search-console/_index': {
      id: '/_app/search-console/_index'
      path: ''
      fullPath: '/search-console'
      preLoaderRoute: typeof AppSearchConsoleIndexRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-console/amp': {
      id: '/_app/search-console/amp'
      path: '/amp'
      fullPath: '/search-console/amp'
      preLoaderRoute: typeof AppSearchConsoleAmpRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-console/countries': {
      id: '/_app/search-console/countries'
      path: '/countries'
      fullPath: '/search-console/countries'
      preLoaderRoute: typeof AppSearchConsoleCountriesRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-console/coverage': {
      id: '/_app/search-console/coverage'
      path: '/coverage'
      fullPath: '/search-console/coverage'
      preLoaderRoute: typeof AppSearchConsoleCoverageRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-console/cwv': {
      id: '/_app/search-console/cwv'
      path: '/cwv'
      fullPath: '/search-console/cwv'
      preLoaderRoute: typeof AppSearchConsoleCwvRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-console/devices': {
      id: '/_app/search-console/devices'
      path: '/devices'
      fullPath: '/search-console/devices'
      preLoaderRoute: typeof AppSearchConsoleDevicesRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-console/links': {
      id: '/_app/search-console/links'
      path: '/links'
      fullPath: '/search-console/links'
      preLoaderRoute: typeof AppSearchConsoleLinksRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-console/manual-actions': {
      id: '/_app/search-console/manual-actions'
      path: '/manual-actions'
      fullPath: '/search-console/manual-actions'
      preLoaderRoute: typeof AppSearchConsoleManualActionsRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-console/mobile-usability': {
      id: '/_app/search-console/mobile-usability'
      path: '/mobile-usability'
      fullPath: '/search-console/mobile-usability'
      preLoaderRoute: typeof AppSearchConsoleMobileUsabilityRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-console/pages': {
      id: '/_app/search-console/pages'
      path: '/pages'
      fullPath: '/search-console/pages'
      preLoaderRoute: typeof AppSearchConsolePagesRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-console/performance': {
      id: '/_app/search-console/performance'
      path: '/performance'
      fullPath: '/search-console/performance'
      preLoaderRoute: typeof AppSearchConsolePerformanceRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-console/property-details': {
      id: '/_app/search-console/property-details'
      path: '/property-details'
      fullPath: '/search-console/property-details'
      preLoaderRoute: typeof AppSearchConsolePropertyDetailsRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-console/queries': {
      id: '/_app/search-console/queries'
      path: '/queries'
      fullPath: '/search-console/queries'
      preLoaderRoute: typeof AppSearchConsoleQueriesRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-console/sitemaps': {
      id: '/_app/search-console/sitemaps'
      path: '/sitemaps'
      fullPath: '/search-console/sitemaps'
      preLoaderRoute: typeof AppSearchConsoleSitemapsRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-console/url-inspection': {
      id: '/_app/search-console/url-inspection'
      path: '/url-inspection'
      fullPath: '/search-console/url-inspection'
      preLoaderRoute: typeof AppSearchConsoleUrlInspectionRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-console/verification': {
      id: '/_app/search-console/verification'
      path: '/verification'
      fullPath: '/search-console/verification'
      preLoaderRoute: typeof AppSearchConsoleVerificationRouteImport
      parentRoute: typeof AppSearchConsoleRoute
    }
    '/_app/search-knowledge/_index': {
      id: '/_app/search-knowledge/_index'
      path: ''
      fullPath: '/search-knowledge'
      preLoaderRoute: typeof AppSearchKnowledgeIndexRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/ai-search-overview': {
      id: '/_app/search-knowledge/ai-search-overview'
      path: '/ai-search-overview'
      fullPath: '/search-knowledge/ai-search-overview'
      preLoaderRoute: typeof AppSearchKnowledgeAiSearchOverviewRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/featured-snippets': {
      id: '/_app/search-knowledge/featured-snippets'
      path: '/featured-snippets'
      fullPath: '/search-knowledge/featured-snippets'
      preLoaderRoute: typeof AppSearchKnowledgeFeaturedSnippetsRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/future-trends': {
      id: '/_app/search-knowledge/future-trends'
      path: '/future-trends'
      fullPath: '/search-knowledge/future-trends'
      preLoaderRoute: typeof AppSearchKnowledgeFutureTrendsRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/google-algorithm-updates': {
      id: '/_app/search-knowledge/google-algorithm-updates'
      path: '/google-algorithm-updates'
      fullPath: '/search-knowledge/google-algorithm-updates'
      preLoaderRoute: typeof AppSearchKnowledgeGoogleAlgorithmUpdatesRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/google-ranking-factors': {
      id: '/_app/search-knowledge/google-ranking-factors'
      path: '/google-ranking-factors'
      fullPath: '/search-knowledge/google-ranking-factors'
      preLoaderRoute: typeof AppSearchKnowledgeGoogleRankingFactorsRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/google-search-architecture': {
      id: '/_app/search-knowledge/google-search-architecture'
      path: '/google-search-architecture'
      fullPath: '/search-knowledge/google-search-architecture'
      preLoaderRoute: typeof AppSearchKnowledgeGoogleSearchArchitectureRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/image-search': {
      id: '/_app/search-knowledge/image-search'
      path: '/image-search'
      fullPath: '/search-knowledge/image-search'
      preLoaderRoute: typeof AppSearchKnowledgeImageSearchRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/knowledge-graph': {
      id: '/_app/search-knowledge/knowledge-graph'
      path: '/knowledge-graph'
      fullPath: '/search-knowledge/knowledge-graph'
      preLoaderRoute: typeof AppSearchKnowledgeKnowledgeGraphRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/local-search': {
      id: '/_app/search-knowledge/local-search'
      path: '/local-search'
      fullPath: '/search-knowledge/local-search'
      preLoaderRoute: typeof AppSearchKnowledgeLocalSearchRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/news-search': {
      id: '/_app/search-knowledge/news-search'
      path: '/news-search'
      fullPath: '/search-knowledge/news-search'
      preLoaderRoute: typeof AppSearchKnowledgeNewsSearchRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/people-also-ask': {
      id: '/_app/search-knowledge/people-also-ask'
      path: '/people-also-ask'
      fullPath: '/search-knowledge/people-also-ask'
      preLoaderRoute: typeof AppSearchKnowledgePeopleAlsoAskRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/rich-results': {
      id: '/_app/search-knowledge/rich-results'
      path: '/rich-results'
      fullPath: '/search-knowledge/rich-results'
      preLoaderRoute: typeof AppSearchKnowledgeRichResultsRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/search-intent': {
      id: '/_app/search-knowledge/search-intent'
      path: '/search-intent'
      fullPath: '/search-knowledge/search-intent'
      preLoaderRoute: typeof AppSearchKnowledgeSearchIntentRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/search-operators': {
      id: '/_app/search-knowledge/search-operators'
      path: '/search-operators'
      fullPath: '/search-knowledge/search-operators'
      preLoaderRoute: typeof AppSearchKnowledgeSearchOperatorsRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/serp-layout': {
      id: '/_app/search-knowledge/serp-layout'
      path: '/serp-layout'
      fullPath: '/search-knowledge/serp-layout'
      preLoaderRoute: typeof AppSearchKnowledgeSerpLayoutRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/shopping-search': {
      id: '/_app/search-knowledge/shopping-search'
      path: '/shopping-search'
      fullPath: '/search-knowledge/shopping-search'
      preLoaderRoute: typeof AppSearchKnowledgeShoppingSearchRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/video-search': {
      id: '/_app/search-knowledge/video-search'
      path: '/video-search'
      fullPath: '/search-knowledge/video-search'
      preLoaderRoute: typeof AppSearchKnowledgeVideoSearchRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
    '/_app/search-knowledge/voice-search': {
      id: '/_app/search-knowledge/voice-search'
      path: '/voice-search'
      fullPath: '/search-knowledge/voice-search'
      preLoaderRoute: typeof AppSearchKnowledgeVoiceSearchRouteImport
      parentRoute: typeof AppSearchKnowledgeRoute
    }
  }
}

interface AppSearchConsoleRouteChildren {
  AppSearchConsoleIndexRoute: typeof AppSearchConsoleIndexRoute
  AppSearchConsoleAmpRoute: typeof AppSearchConsoleAmpRoute
  AppSearchConsoleCountriesRoute: typeof AppSearchConsoleCountriesRoute
  AppSearchConsoleCoverageRoute: typeof AppSearchConsoleCoverageRoute
  AppSearchConsoleCwvRoute: typeof AppSearchConsoleCwvRoute
  AppSearchConsoleDevicesRoute: typeof AppSearchConsoleDevicesRoute
  AppSearchConsoleLinksRoute: typeof AppSearchConsoleLinksRoute
  AppSearchConsoleManualActionsRoute: typeof AppSearchConsoleManualActionsRoute
  AppSearchConsoleMobileUsabilityRoute: typeof AppSearchConsoleMobileUsabilityRoute
  AppSearchConsolePagesRoute: typeof AppSearchConsolePagesRoute
  AppSearchConsolePerformanceRoute: typeof AppSearchConsolePerformanceRoute
  AppSearchConsolePropertyDetailsRoute: typeof AppSearchConsolePropertyDetailsRoute
  AppSearchConsoleQueriesRoute: typeof AppSearchConsoleQueriesRoute
  AppSearchConsoleSitemapsRoute: typeof AppSearchConsoleSitemapsRoute
  AppSearchConsoleUrlInspectionRoute: typeof AppSearchConsoleUrlInspectionRoute
  AppSearchConsoleVerificationRoute: typeof AppSearchConsoleVerificationRoute
}

const AppSearchConsoleRouteChildren: AppSearchConsoleRouteChildren = {
  AppSearchConsoleIndexRoute: AppSearchConsoleIndexRoute,
  AppSearchConsoleAmpRoute: AppSearchConsoleAmpRoute,
  AppSearchConsoleCountriesRoute: AppSearchConsoleCountriesRoute,
  AppSearchConsoleCoverageRoute: AppSearchConsoleCoverageRoute,
  AppSearchConsoleCwvRoute: AppSearchConsoleCwvRoute,
  AppSearchConsoleDevicesRoute: AppSearchConsoleDevicesRoute,
  AppSearchConsoleLinksRoute: AppSearchConsoleLinksRoute,
  AppSearchConsoleManualActionsRoute: AppSearchConsoleManualActionsRoute,
  AppSearchConsoleMobileUsabilityRoute: AppSearchConsoleMobileUsabilityRoute,
  AppSearchConsolePagesRoute: AppSearchConsolePagesRoute,
  AppSearchConsolePerformanceRoute: AppSearchConsolePerformanceRoute,
  AppSearchConsolePropertyDetailsRoute: AppSearchConsolePropertyDetailsRoute,
  AppSearchConsoleQueriesRoute: AppSearchConsoleQueriesRoute,
  AppSearchConsoleSitemapsRoute: AppSearchConsoleSitemapsRoute,
  AppSearchConsoleUrlInspectionRoute: AppSearchConsoleUrlInspectionRoute,
  AppSearchConsoleVerificationRoute: AppSearchConsoleVerificationRoute,
}

const AppSearchConsoleRouteWithChildren =
  AppSearchConsoleRoute._addFileChildren(AppSearchConsoleRouteChildren)

interface AppSearchKnowledgeRouteChildren {
  AppSearchKnowledgeIndexRoute: typeof AppSearchKnowledgeIndexRoute
  AppSearchKnowledgeAiSearchOverviewRoute: typeof AppSearchKnowledgeAiSearchOverviewRoute
  AppSearchKnowledgeFeaturedSnippetsRoute: typeof AppSearchKnowledgeFeaturedSnippetsRoute
  AppSearchKnowledgeFutureTrendsRoute: typeof AppSearchKnowledgeFutureTrendsRoute
  AppSearchKnowledgeGoogleAlgorithmUpdatesRoute: typeof AppSearchKnowledgeGoogleAlgorithmUpdatesRoute
  AppSearchKnowledgeGoogleRankingFactorsRoute: typeof AppSearchKnowledgeGoogleRankingFactorsRoute
  AppSearchKnowledgeGoogleSearchArchitectureRoute: typeof AppSearchKnowledgeGoogleSearchArchitectureRoute
  AppSearchKnowledgeImageSearchRoute: typeof AppSearchKnowledgeImageSearchRoute
  AppSearchKnowledgeKnowledgeGraphRoute: typeof AppSearchKnowledgeKnowledgeGraphRoute
  AppSearchKnowledgeLocalSearchRoute: typeof AppSearchKnowledgeLocalSearchRoute
  AppSearchKnowledgeNewsSearchRoute: typeof AppSearchKnowledgeNewsSearchRoute
  AppSearchKnowledgePeopleAlsoAskRoute: typeof AppSearchKnowledgePeopleAlsoAskRoute
  AppSearchKnowledgeRichResultsRoute: typeof AppSearchKnowledgeRichResultsRoute
  AppSearchKnowledgeSearchIntentRoute: typeof AppSearchKnowledgeSearchIntentRoute
  AppSearchKnowledgeSearchOperatorsRoute: typeof AppSearchKnowledgeSearchOperatorsRoute
  AppSearchKnowledgeSerpLayoutRoute: typeof AppSearchKnowledgeSerpLayoutRoute
  AppSearchKnowledgeShoppingSearchRoute: typeof AppSearchKnowledgeShoppingSearchRoute
  AppSearchKnowledgeVideoSearchRoute: typeof AppSearchKnowledgeVideoSearchRoute
  AppSearchKnowledgeVoiceSearchRoute: typeof AppSearchKnowledgeVoiceSearchRoute
}

const AppSearchKnowledgeRouteChildren: AppSearchKnowledgeRouteChildren = {
  AppSearchKnowledgeIndexRoute: AppSearchKnowledgeIndexRoute,
  AppSearchKnowledgeAiSearchOverviewRoute:
    AppSearchKnowledgeAiSearchOverviewRoute,
  AppSearchKnowledgeFeaturedSnippetsRoute:
    AppSearchKnowledgeFeaturedSnippetsRoute,
  AppSearchKnowledgeFutureTrendsRoute: AppSearchKnowledgeFutureTrendsRoute,
  AppSearchKnowledgeGoogleAlgorithmUpdatesRoute:
    AppSearchKnowledgeGoogleAlgorithmUpdatesRoute,
  AppSearchKnowledgeGoogleRankingFactorsRoute:
    AppSearchKnowledgeGoogleRankingFactorsRoute,
  AppSearchKnowledgeGoogleSearchArchitectureRoute:
    AppSearchKnowledgeGoogleSearchArchitectureRoute,
  AppSearchKnowledgeImageSearchRoute: AppSearchKnowledgeImageSearchRoute,
  AppSearchKnowledgeKnowledgeGraphRoute: AppSearchKnowledgeKnowledgeGraphRoute,
  AppSearchKnowledgeLocalSearchRoute: AppSearchKnowledgeLocalSearchRoute,
  AppSearchKnowledgeNewsSearchRoute: AppSearchKnowledgeNewsSearchRoute,
  AppSearchKnowledgePeopleAlsoAskRoute: AppSearchKnowledgePeopleAlsoAskRoute,
  AppSearchKnowledgeRichResultsRoute: AppSearchKnowledgeRichResultsRoute,
  AppSearchKnowledgeSearchIntentRoute: AppSearchKnowledgeSearchIntentRoute,
  AppSearchKnowledgeSearchOperatorsRoute:
    AppSearchKnowledgeSearchOperatorsRoute,
  AppSearchKnowledgeSerpLayoutRoute: AppSearchKnowledgeSerpLayoutRoute,
  AppSearchKnowledgeShoppingSearchRoute: AppSearchKnowledgeShoppingSearchRoute,
  AppSearchKnowledgeVideoSearchRoute: AppSearchKnowledgeVideoSearchRoute,
  AppSearchKnowledgeVoiceSearchRoute: AppSearchKnowledgeVoiceSearchRoute,
}

const AppSearchKnowledgeRouteWithChildren =
  AppSearchKnowledgeRoute._addFileChildren(AppSearchKnowledgeRouteChildren)

interface AppRouteChildren {
  AppBusinessProfileRoute: typeof AppBusinessProfileRoute
  AppCompetitorsRoute: typeof AppCompetitorsRoute
  AppGoogleProductsRoute: typeof AppGoogleProductsRoute
  AppKeywordsRoute: typeof AppKeywordsRoute
  AppMobileRoute: typeof AppMobileRoute
  AppPerformanceRoute: typeof AppPerformanceRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSearchConsoleRoute: typeof AppSearchConsoleRouteWithChildren
  AppSearchKnowledgeRoute: typeof AppSearchKnowledgeRouteWithChildren
  AppSeoAnalyzerRoute: typeof AppSeoAnalyzerRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTrackingRoute: typeof AppTrackingRoute
  AppWebsiteFoundationRoute: typeof AppWebsiteFoundationRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBusinessProfileRoute: AppBusinessProfileRoute,
  AppCompetitorsRoute: AppCompetitorsRoute,
  AppGoogleProductsRoute: AppGoogleProductsRoute,
  AppKeywordsRoute: AppKeywordsRoute,
  AppMobileRoute: AppMobileRoute,
  AppPerformanceRoute: AppPerformanceRoute,
  AppReportsRoute: AppReportsRoute,
  AppSearchConsoleRoute: AppSearchConsoleRouteWithChildren,
  AppSearchKnowledgeRoute: AppSearchKnowledgeRouteWithChildren,
  AppSeoAnalyzerRoute: AppSeoAnalyzerRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTrackingRoute: AppTrackingRoute,
  AppWebsiteFoundationRoute: AppWebsiteFoundationRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
